### ISSUE TITLE
feature req: api.alert could return an object allowing alert to be edited/canceled

### ISSUE THREAD

**Issue by ntuckerxx** [kasper/phoenix#10]
I've got a nifty little binding that puts me into a mode that lets me start typing to interactively find a window I'm looking for.  E.g. I bind it to hyper-f and then I hit hyper-f,c,h,r,o and it raises the first window that matches "c", then "ch", then "chr", then "chro".  If I then hit tab it cycles to the next matching window for whatever regex i've entered so far.  I hit enter or escape when I'm done.

Anyway, the thing that's really missing is some visual feedback that A) you're in the pattern-entering mode, and B) what you've entered so far.  I have implemented it using repeated calls to api.alert, but it's pretty obnoxious to stack a whole bunch of them up, and there's no way to clear them out when exiting my mode.  I think what would be really cool is if api.alert() returned an object that had methods 'cancel' and 'setText' so that you could modify the alert in place or make it go away on demand.

What do you think?

**Comment by jasonm23** [comment]
Reference, PR #12 was merged.

**Comment by kasper** [comment]
Is this still an active issue? Please comment and I’ll reopen.
