### ISSUE TITLE
Cannot focus opened Finder window

### ISSUE THREAD

**Issue by alswl** [kasper/phoenix#101]
- Version: 2.1.1 (20)
- OS X: 10.11.4 (15E65)

Hi, I use shortcut to focus Apps. Almost apps works well with the code:

```
function launchOrFocus(appName) {
  var app = App.launch(appName);
  assert(app !== undefined);
  app.focus();
  return app;
}
```

But when I try to `launchOrFocus` Finder, it will not focused when opened window in another space.

I think, the `app.focus()` activate the `Desktop` of Finder.

How can I activate the Finder windows in another space?

Thanks.

**Comment by kasper** [comment]
Have you tried focusing the actual window in the other space (instead of the whole app)?

**Comment by kasper** [comment]
@alswl I’ll close this for now. Please comment, if focusing the actual window doesn’t work.

**Comment by alswl** [comment]
Ok, It may be works in other space, I will try to fix this by change space.
