### ISSUE TITLE
Can't anymore bind '[' and ']' keys 

### ISSUE THREAD

**Issue by josser** [kasper/phoenix#103]
- Version: 2.1.1
- OS X: 10.11.5

For some reason with update to 2.1 I can't anymore bind [ and ] keys. 
Here is my example config which worked fine before update: 
https://gist.github.com/josser/6c2667628196f7ff2c07ac457611a9fa

There is a warning in the console: 
09.06.16 16:22:54,615 Phoenix[610]: Warning: Key “[” not supported.

Thank you, and sorry for bad english

**Comment by mafredri** [comment]
Do you use shift to get `[`? If so, try to bind the underlying key and set shift as a modifier, e.g. `Phoenix.bind('7', ['shift'], );`.

**Comment by josser** [comment]
@mafredri No, I have separate keys for them. I have localized keyboard with russian symbols, but there are 33 letters in russian alphabet and so, there are some 'additional' free keys with such special symbols in english locale.

**Comment by kasper** [comment]
@josser Hi! What version did you have previously and have you used the same keyboard with both versions? Also, what character does the keyboard output with no modifiers for the key?

**Comment by josser** [comment]
@kasper I'm not sure but probably 2.0.1 
The characters are '[' and ']'. It's Apple wired aluminum keyboard which looks very similar to this one: https://www.godigi.org.au/sites/default/files/images/keyboard_mac.png

**Comment by kasper** [comment]
@josser That’s definitely weird since nothing should have changed regarding key binding that would particularly drop support if it has worked before. Have you by any chance changed your OS X locale or keyboard locale recently?

Alternatively, would you be able to test the previous versions to identify where the change has happened?

**Comment by kasper** [comment]
@josser One thing that comes to my mind is that your keyboard might be defaulting to an ASCII-layout for some reason and this would make the key unsupported.

**Comment by josser** [comment]
@kasper So, I've just installed 2.0.1 and everything started to work! No locale change, just have two apps installed in two folders (via brew cask).

**Comment by kasper** [comment]
Totally weird! Nothing should have changed regarding key translation after 2.0. Even the ASCII-fix (https://github.com/kasper/phoenix/commit/d6a7a68a8b1daad2e70d85f81aeefd877dfa236a) happened in 2.0.

**Comment by josser** [comment]
@kasper I can tell you more weird thing - it's stopped working again after reboot. Even on older versions. 
So, I think it's not related to code change but somehow to update mechanism. 

I've tried to re-add Phoenix to accessibility settings but that doesn't help

**Comment by kasper** [comment]
@josser Baffling. Phoenix asks for OS X to return the keyboard layout and translates the keys based on that. If no Unicode layout is found, it will resort to using an ASCII-layout.

So you have a Russian Apple wireless keyboard. In OS X’s keyboard settings, what is the selected layout?

**Comment by kasper** [comment]
Basically, what does this view show for you as the primary character for the key?

<img width="680" alt="keyboard" src="https://cloud.githubusercontent.com/assets/925851/16114900/72566724-33cc-11e6-8a53-730a62115a84.png">

**Comment by josser** [comment]
no, it's "wired" version. With num-pad. 

![2016-06-16 15 25 11](https://cloud.githubusercontent.com/assets/103639/16116607/8c5319f6-33d6-11e6-8d0d-5b10b44e4dae.png)
![2016-06-16 15 25 09](https://cloud.githubusercontent.com/assets/103639/16116606/8c51b066-33d6-11e6-9f9d-e637041d839a.png)

**Comment by josser** [comment]
So, I just changed bind to 'ъ' and 'х' and everything started to work. 
I think we can close this.

**Comment by kasper** [comment]
@josser Yes, you figured it out! You need to use the keys for your “default” keyboard layout, i.e. the one that is active when Phoenix’s context is loaded. This can indeed be confusing if you switch between multiple layouts. Anyway, glad we got this sorted out. 😄

**Comment by josser** [comment]
Hi again, just a small question: is there any changes around key handlers in latest 2.2.x releases? 
I'm faced with same issue again but 'reversed'. Now I can bind only in 'english' layout, like: 
Key.on(']', controlAlt, function () { ... 
and version with local layout is not working: Key.on('ъ', controlAlt, function () {
So, I'm not sure, is this expected because there a lot of changes in API, or there is something else?
Thank you!

**Comment by kasper** [comment]
@josser No changes related to this. The keys are resolved with the *active* layout, so ensure you are on the correct layout (Russian) when Phoenix starts.

**Comment by josser** [comment]
@kasper ah, got it, thank you!
