### ISSUE TITLE
Verify Phoenix works on macOS Sierra

### ISSUE THREAD

**Issue by kasper** [kasper/phoenix#106]
Verify Phoenix works on macOS Sierra (10.12).

**Comment by kasper** [comment]
@mafredri I haven’t upgraded just yet, but it seems Phoenix behaves on Sierra?

**Comment by mafredri** [comment]
Except for the mindfuck of not using caps lock (before now)  yes! Worked out of the box, so to speak. Surely haven't tested all aspects of it yet, but no problems so far 👌😁🎉

**Comment by kasper** [comment]
Good! There’s always the anxiety that something will be totally broken.

**Comment by mafredri** [comment]
I can try to test some more of the API during the weekend, I'll report back with my findings.

**Comment by kasper** [comment]
It seems everything is working fine. Please open new issues for anything related.
