### ISSUE TITLE
Name and stylistic changes to the API

### ISSUE THREAD

**Issue by kasper** [kasper/phoenix#108]
Make some name and stylistic changes to the API to make it more coherent. Many of these are remains from the refactor and have bothered me partly due to their naming, but partly due to not feeling natural.

It’s most likely reasonable to change these, but make the existing ones aliases, deprecate them and remove then in the future — so that users don’t have to make configuration changes so often?

Any others?

### Screen

1. [x] `Screen.mainScreen() -> Screen.main()`
2. [x] `Screen.screens() -> Screen.all()`
3. [x] `#visibleWindows() -> #windows({ visible: true })`

### Space

4. [x] `Space.activeSpace() -> Space.active()`
5. [x] `Space.spaces() -> Space.all()`
6. [x] `#visibleWindows() -> #windows({ visible: true })`

### App

7. [x] `App.focusedApp() -> App.focused()`
8. [x] `App.runningApps() -> App.all()`
9. [x] `#visibleWindows() -> #windows({ visible: true })`
10. [x] `#forceTerminate() -> #terminate({ force: true })`

### Window

11. [x] `Window.focusedWindow() -> Window.focused()`
12. [x] `Window.windows() -> Window.all()`
13. [x] `Window.visibleWindows() -> Window.all({ visible: true })`
14. [x] `Window.visibleWindowsInOrder() -> Window.recent()`
15. [x] `#otherWindowsOnSameScreen() -> #others({ screen: window.screen })`
16. [x] `#otherWindowsOnAllScreens() -> #others()`
17. [x] `#windowsToWest() -> #neighbors('west')`
18. [x] `#windowsToEast() -> #neighbors('east')`
19. [x] `#windowsToNorth() -> #neighbors('north')`
20. [x] `#windowsToSouth() -> #neighbors('south')`
21. [x] `#focusClosestWindowInWest() -> #focusClosestNeighbor('west')`
22. [x] `#focusClosestWindowInEast() -> #focusClosestNeighbor('east')`
23. [x] `#focusClosestWindowInNorth() -> #focusClosestNeighbor('north')`
24. [x] `#focusClosestWindowInSouth() -> #focusClosestNeighbor('south)`

**Comment by kasper** [comment]
Actually, to save development time, I will probably just delete them straight away. Since 2.2 is shaping to clarify and stabilise many other things anyway. Better evolve rapidly than not at all.

**Comment by mafredri** [comment]
I've been thinking the exact same thing. Really like most of these changes! I'm a bit torn, though, on the object configuration for the directional (west/east/...) functions. One the one hand it's more flexible, programmatically, and on the other it's maybe not as easy to type / autocomplete. Would these functions also have an action when no direction is passed?

Regarding the `#others()` function, one possibility could also be to have the actual screen as a parameter, e.g. `#others({ screen: win.screen().next() })`, might be a bit more flexible. And I think it's a ok default to return from all screens when no screen parameter is passed :).

**Comment by kasper** [comment]
Good point on passing the screen to `#others(…)`. That makes much more sense!

The directional functions are definitely the hardest to solve. I would like to avoid repeating the word “window” in them. Other options would be:

1. `#neighbors('west')`
2. `#neighborsToWest()`
3. `#focusClosestNeighbor('west')`
4. `#focusClosestNeighborInWest()`

You are right that 2. and 4. would most likely be the best choice since there are no other options to pass to the functions.

**Comment by kasper** [comment]
Also, `Window.visibleWindowsInOrder()` could also be `Window.visible({ order: 'front-most' })` or something similar.

**Comment by kasper** [comment]
Still need to verify these again to be sure, but everything should be okay. Much better!

**Comment by kasper** [comment]
Everything seems to be working as expected, please report any issues found!

**Comment by mafredri** [comment]
Haven't tried all the changed functions yet, but so far so good! Nice job, and thanks for splitting this up into separate commits, was easy to follow :)!

**Comment by kasper** [comment]
@mafredri 👍 I added the visibility optional to Window#others(...) as well. Makes sense.

**Comment by jasonm23** [comment]
Hey Kasper,

The 2.2 upgrade is an extensive piece of work, well done on getting so much into this release.

I've got a few red flags to raise unfortunately.

- `Phoenix.bind` seems to have been left out of the breaking changes (not mentioned explicitly AFAICS) - It's no longer available and there's no clear guideline for converting `Phoenix.bind(key, mods, fn)` to `new Key( 

- I think a user friendly migration guide should've been built step by step as the changes were decided on,  it'll be an unpleasant job to fish out all the info and build a migration guide retroactively. 

I understand you wanted to just get it done but It's really important to properly deprecate your API methods and not just bin them.  At the very least stub the method and show a useful message on with the alert.

TBH sad that I hadn't been watching this thread before the migration. There's now have sudden unexpected work to do refactoring my config,  

Error messages are basically of the "function undefined" variety, and with a patchy set of migration notes it's quite a laborious task. My concern is that this harms the user base at large, and damages trust.  Hopefully there's enough new goodies to counteract any disappointment.

Sorry to bitch, obviously you've put a lot of work in and it's awesome.  I just needed to point out some practical drawbacks.

**Comment by kasper** [comment]
@jasonm23 Thanks for the heads up, I understand your concerns and I’m sorry that you feel that way! That being said:

1. Every single change has been recorded to the Changelog. Even the change about `Phoenix.bind(...)`. Its under the API section. Most of the changes can be solved by just a find and replace.
2. I thought about just deprecating the old ones, but as it became clear that this would become a burden to maintain, I decided it’s just easier to drop them at this point.
3. People seems to be relatively slow to adopt new versions anyway based on the download rates in https://api.github.com/repos/kasper/phoenix/releases.
4. People can obviously choose to not upgrade.
5. People would push required changes anyway to the point were they would break.
6. I’m confident the API has now stabilised and any changes from this point forward will first be introduced and later deprecated.
7. Continuous deployment is better than no deployment at all.
8. At its core this project is more or less “hacker” oriented, so I wouldn’t be too worried about the user base.

In the end, as you most likely know, time is limited and this is an open-source project. I have new things coming up in August and I wanted to get this out of the way before that. Single-handedly working on a project requires prioritisation.

**Comment by jasonm23** [comment]
It's cool, I wanted to give an unfiltered reaction of the pain caused by hitting upgrade via the app while in the middle of working on other things.  (*in the middle of the night ;))

I don't really (theoretically) agree with simply ditching API methods instead of proper deprecation however as you point out this is a hacker project, open source (and obviously under resourced!) As such whatever you choose to do is the way it should be and must be.  If something seems like too much work overhead for little payoff I think it's fine.

That said, throwing an _API method not found_ exception for deprecated methods would've helped drive a migration path with reduced pain. Without much development overhead.  (Just a take away note for the future.)

Regardless kudos on all the extra things which are now available, and the API generally feels more coherent and sensibly named. :+1:

I will gather up the migration notes that apply to my config and put them somewhere useful. (Wiki)

**Comment by kasper** [comment]
@jasonm23 That’s alright! You’re definitely right, but as the user base is still quite small, I feel like I’m still trying to settle this project down and as such I can do experiments. This release was exactly that. Also, as much as this is a fun project, this is also a learning experience about developing and releasing software on my own.

I made a risky decision, I hope people appreciate the work I’ve put into this project more than the frustration of having to read the Changelog and API again. In the end, that’s how we get feedback.

You are also right that the JavaScriptCore-exceptions are quite lacking for this context, where trial and error is needed. I probably should’ve thought about a migration guide, but it feels the Changelog should be ok. Every change has been reported there (as well as in the description of this issue).

**Comment by jasonm23** [comment]
By the way, can you point me at the note re:

`Phoenix.bind` -> `Keys`

I'm didn't understand what the alternative syntax is now.

Is it `Keys.on`?

**Comment by jasonm23** [comment]
And your right, you have a project here which is small enough that you can take risks without mass turmoil.

Definitely nice experience to have :)

**Comment by kasper** [comment]
@jasonm23 It’s `new Key(...)` if you want to manage the handler yourself, i.e. you need to keep a reference to it. `Key.on(...)` will manage the reference for you.

**Comment by kasper** [comment]
@jasonm23 Hopefully this will help: https://github.com/kasper/phoenix/wiki/Upgrade-from-2.x-to-2.2. Feel free to update it if you see something that’s missing.

**Comment by jasonm23** [comment]
Awesome.  Thank you @kasper I think this will be a help to anyone upgrading.

**Comment by jasonm23** [comment]
Updated - I'll add tagged versions to the Wiki

**Comment by jasonm23** [comment]
https://github.com/jasonm23/Phoenix-config/commit/dedbc2f436d0dcc55dfeeb89ffe740a410b19266

**Comment by kasper** [comment]
@jasonm23 Nice!
