### ISSUE TITLE
Task.run doesn't work on latest master

### ISSUE THREAD

**Issue by mafredri** [kasper/phoenix#110]
It seems that `Task.run()` was broken during the refactor, `new Task()` works perfectly! I believe this line of code should be replaced with the `terminate` function: https://github.com/kasper/phoenix/commit/2b99d5b82da0148a7404266a4d6040625283a9d3#diff-bbcc3d63776dc2a5ef155556a5648d57R12. 

The error:

```
02/07/16 00:06:41,201 Phoenix[77195]: TypeError: Task.off is not a function. (In 'Task.off(a.hash())', 'Task.off' is undefined)
```

**Comment by kasper** [comment]
Darn, you always miss something. Thanks! :)
