### ISSUE TITLE
Add support for British alternatives to API

### ISSUE THREAD

**Issue by kasper** [kasper/phoenix#113]
I prefer to use British English and I’d presume I’m not the only one. So add support for British alternatives to API.

### Events

1. [x] `windowDidMinimise` for `windowDidMinimize`
2. [x] `windowDidUnminimise` for `windowDidUnminimize`

### Window

3. [x] `isMinimised()` for `isMinimized()`
4. [x] `maximise()` for `maximize()`
5. [x] `minimise()` for `minimize()`
6. [x] `unminimise()` for `unminimize()`
7. [x] `neighbours(String direction)` for `neighbors(String direction)`
8. [x] `focusClosestNeighbour(String direction)` for `focusClosestNeighbor(String direction)`

**Comment by kasper** [comment]
Supercalifragilisticexpialidocious!

**Comment by jasonm23** [comment]
Superlatives!
