### ISSUE TITLE
Modal keybinding implementation inquery

### ISSUE THREAD

**Issue by khalidchawtany** [kasper/phoenix#115]
- Version: 2.2 (33)
- macOS: 10.11.5

First of all this is not an issue.

I want to have a modal keybinding to operate Phoenix. Ultimately, I wan to have a mode which could be activated with a HYPER and then terminated with ESC. When inside that mode, pressing single letters should be enough to trigger phoenix actions (No HYPER press needed till ESC is pressed).

Any help is appreciated.

**Comment by kasper** [comment]
Cool! Have you tried implementing this? There’s at least to strategies you could apply here:

1. Bind HYPER, ESC and all action keys
2. Store references to the action keys (from `new Key(...)`)
3. Disable all action keys immediately
4. When HYPER is pressed, enable all action keys
5. WHEN ESC is pressed, disable all action keys

Or you could:

1. Bind HYPER and ESC keys
2. When HYPER is pressed, bind all action keys (with `new Key(...)` or `Key.on(...)`)
3. Store references to the action keys (references or identifiers)
4. When ESC is pressed, release all action keys

**Comment by khalidchawtany** [comment]
Thanks, I will try you suggestion.

I have taken a look at a modal [config](https://github.com/NsLib/phoenix-conf/). However, it was for a previous version. I was wondering if there is any new stuff that would make it easier to implement.

**Comment by khalidchawtany** [comment]
@kasper I have found that bound keys are not repeated when pressed and hold.  You have to press and release each time to make it trigger :(

**Comment by kasper** [comment]
@khalidchawtany That is by design (`kEventHotKeyPressed`). What would you use this for?

**Comment by khalidchawtany** [comment]
I want to micro-manage window movements and resizes. I want to move a window 10 pixel to the left on pressing `h`, holding `h` should move it multiples of 10 pixel.

**Comment by kasper** [comment]
@khalidchawtany Let me see if this is an easy fix.

**Comment by khalidchawtany** [comment]
I really appreciate your hard work :+1:

**Comment by kasper** [comment]
@khalidchawtany Unfortunately, there is no automated way and it seems this has to be implemented with a timer. 😭

**Comment by mafredri** [comment]
@kasper if it's any comfort, I might have some uses for this as well. I've ran into this a couple of times but thought I'd just live with it :). And like @khalidchawtany said, your work is appreciated, you've been on fire lately ^_^.

**Comment by kasper** [comment]
@mafredri @khalidchawtany Oh well. What would be a suitable interval? 60 times per second? You could then throttle that to your needs with for example `_.throttle(...)`.

**Comment by khalidchawtany** [comment]
That would be awesome :)

**Comment by mafredri** [comment]
That would be more than enough in my opinion. How fast do we think Phoenix needs to be able to respond? I think a suitable range would be between 20 - 50ms, with 20, it would be `1000 / 20 = 50` and with 50ms it would be `1000 / 50 = 20`. So maybe 50x / second and we get a nice round number (20ms)?

On the other hand, how precise would the timing be, this being JS and all, would other operations block, etc?

**Comment by kasper** [comment]
@mafredri I’ll first try with 0,05 seconds.

**Comment by kasper** [comment]
Actually, you can get it from the system with `[NSEvent keyRepeatInterval]`.

**Comment by kasper** [comment]
Issue #119.
