### ISSUE TITLE
window.others({ screen: window.screen() }) did not work as expected

### ISSUE THREAD

**Issue by alswl** [kasper/phoenix#116]
- Version: Version 2.2 (33)
- macOS: 10.11.5 (15F34)

`window.others({ screen: window.screen() }) ` did not works as expected.

It return the windows of current two displays, not only current screen.

Now I fixed with the configuration.

https://github.com/alswl/.oOo./commit/31bad3383730928f8e7901fb5b274b446c6830f3#diff-c242c5e0ce099258ad80f34cfd202858L150

**Comment by kasper** [comment]
@alswl Terribly sorry about this too!

**Comment by kasper** [comment]
Fixed. Thanks for the report!
