### ISSUE TITLE
space.next() makes Phoenix crash

### ISSUE THREAD

**Issue by alswl** [kasper/phoenix#117]
- Version: Version 2.2 (33)
- macOS: 10.11.5 (15F34)

It will crash here.

https://github.com/alswl/.oOo./blob/4a0be7836eafbe2ff922e5bcee18ae061f76cbc5/.phoenix.js#L585

**Comment by kasper** [comment]
@alswl Terribly sorry about this! I wonder why Xcode didn’t notice this. Will release an update today.

**Comment by kasper** [comment]
Fixed, thanks for the report!

**Comment by alswl** [comment]
It's so kind of you. Thanks for new version.
