### ISSUE TITLE
window.others({ screen: window.screen() }) seems duplicate some Windows

### ISSUE THREAD

**Issue by alswl** [kasper/phoenix#118]
- Version: Version 2.2 (33)
- macOS: 10.11.5 (15F34)

When I use `window.screen()`, some application will duplicate in it.

The Google Chrome will cause this case.

```
function alert(message) {
  var modal = new Modal();
  modal.message = message;
  modal.duration = 2;
  modal.show();
}

var windows = window.others({ screen: window.screen() });
alert(_.map(windows, function(x) {return x.app().name();}).join(','));
```

**Comment by kasper** [comment]
@alswl Does this happen with the master build?

**Comment by kasper** [comment]
@alswl I think this is invalid. An app can certainly have multiple windows in one screen (though they might not be visible).

**Comment by alswl** [comment]
@kasper Yes, it happen with the master build.

But in the old version Phoenix, the Google Chrome is only one windows.

I'll try with condition of visible windows.

**Comment by alswl** [comment]
You are right, add visible filter makes it works.

```
  var windows = _.filter(
	window.others({ screen: window.screen() }),
	function(x) { return x.isVisible(); }
  );
```

**Comment by kasper** [comment]
@alswl Use `window.others({ visible: true, screen: window.screen() })`. There was a misbehaviour in the previous release that caused the other windows to be determined only from the visible windows.
