### ISSUE TITLE
Ability to get active (focused) space for screen

### ISSUE THREAD

**Issue by marszall87** [kasper/phoenix#120]
In multi-monitor setup it would be useful to get the currently open space (i.e. active) for given screen. Currently you can only get the space with keyboard focus.

- Version: 2.2.1
- macOS: 10.11.5

**Comment by kasper** [comment]
@marszall87 Good point. I will see if it’s possible. Have you tried observing whether `Screen#spaces()` reflects when you change the active space in a screen? Just wondering...

**Comment by marszall87** [comment]
@kasper It looks like they're always in the arrangement order, i.e. Screen#spaces()[0] is the leftmost space, regardless of the active one.

**Comment by kasper** [comment]
@marszall87 Ok, thanks!

**Comment by kasper** [comment]
@marszall87 Thanks for the feedback! This has now been implemented in master `Screen#currentSpace()` and will be released in 2.2.2.

**Comment by pbajaria** [comment]
It would be good to have text (Desktop 1, Desktop 2, etc) or a unique id to identify the current space.

**Comment by kasper** [comment]
@pbajaria Couldn’t you use `Screen#hash()` or `Screen#isEqual(...)`?

**Comment by kasper** [comment]
Sorry, I meant `Space#hash()` or `Space#isEqual(...)`.
