### ISSUE TITLE
How can I debug my scripts?

### ISSUE THREAD

**Issue by marcob** [kasper/phoenix#123]
Where should I see `Phoenix.log` logs ?

- Version: 2.2.1 (35)
- macOS: 10.11.6

**Comment by jasonm23** [comment]
Open  Console (use Spotlight)

**Comment by marcob** [comment]
💯 

`Console != Terminal`  
![](https://media.giphy.com/media/OWpMbuG5W4r4Y/giphy.gif)

Thanks a lot @jasonm23!
