### ISSUE TITLE
Phoenix is no longer moving windows

### ISSUE THREAD

**Issue by mafredri** [kasper/phoenix#127]
I actually noticed this yesterday already, but thought macOS was acting up. After 03147b7c6a9724110f95705ac159c69250ce263d Phoenix is no longer moving any windows for me, although resizing seems to work. I reverted the commit and it started working normally again.

- Version: Build 41
- macOS: 10.11.6

**Comment by kasper** [comment]
Fix something, break something else. Thanks for testing the builds out! This should now be (properly) sorted out.

**Comment by mafredri** [comment]
Thanks for the quick fix, can confirm that it works now :)!
