### ISSUE TITLE
Unable to start phoenix

### ISSUE THREAD

**Issue by dhawal55** [kasper/phoenix#129]
- Version: 2.3.0
- macOS: 10.10.5

```
Aug 11 14:39:35  tccd[259]: Unable to verify code signing identity of org.degutis.Phoenix:  code failed to satisfy specified code requirement(s)
Aug 11 14:39:35  universalAccessAuthWarn[32317]: AccessibilityAPI: pid 34562, is not allowed to access the accessibility API. Path: /Applications/Phoenix.app/Contents/MacOS/Phoenix
```

**Comment by kasper** [comment]
@dhawal55 Hi, I’m sorry to hear that! The bundle identifier `org.degutis.Phoenix` raises a red flag. It should be `org.khirviko.Phoenix` for versions over 2.0. What version did you have previously?

Try this:

1. Go to the Accessibility settings in macOS preferences and remove any occurrences of Phoenix.
2. Go to the startup items under your account in macOS preferences and remove any occurrences of Phoenix.
3. Delete Phoenix.app from your applications.
4. Redownload, install and try again.

Let me know if it works!

**Comment by dhawal55** [comment]
I followed your instructions but same error. I also tried to install using `brew cask install phoenix` which installs v2.2.1. I get the below output in console:
```
Aug 12 12:17:26 XXXX.YYYY.net sudo[62198]:     XXXX : TTY=ttys001 ; PWD=/Users/XXXX/go/src/git.nordstrom.net/diehard ; USER=root ; COMMAND=/usr/bin/sqlite3 /Library/Application Support/com.apple.TCC/TCC.db INSERT OR REPLACE INTO access VALUES('kTCCServiceAccessibility','org.khirviko.Phoenix',0,1,1,NULL);
Aug 12 12:17:38 XXXX.YYYY.net tccd[259]: Unable to verify code signing identity of org.degutis.Phoenix:  code failed to satisfy specified code requirement(s)
Aug 12 12:17:38 XXXX.YYYY.net universalAccessAuthWarn[32317]: AccessibilityAPI: pid 62217, is not allowed to access the accessibility API. Path: /Applications/Phoenix.app/Contents/MacOS/Phoenix
```

**Comment by kasper** [comment]
It’s still logging a wrong bundle identifier (for versions below 1.5), so you might somehow have two versions installed. Cask also has 2.3, so you might want to update Cask.

Try the above one more time, but also ensure you quit all instances of Phoenix and restart your computer between steps 3.) and 4.).

**Comment by dhawal55** [comment]
I still cannot get it to work even after uninstalling, restarting and reinstalling. Here's the output on console:
```
8/15/16 9:10:35.698 PM sudo[2424]:     xxx : 1 incorrect password attempt ; TTY=ttys001 ; PWD=/Users/xxx ; USER=root ; COMMAND=/usr/bin/sqlite3 /Library/Application Support/com.apple.TCC/TCC.db INSERT OR REPLACE INTO access VALUES('kTCCServiceAccessibility','org.khirviko.Phoenix',0,1,1,NULL);
8/15/16 9:10:45.230 PM universalAccessAuthWarn[2513]: AccessibilityAPI: pid 2512, is not allowed to access the accessibility API. Path: /Applications/Phoenix.app/Contents/MacOS/Phoenix
8/15/16 9:10:45.234 PM universalAccessAuthWarn[2513]: AccessibilityAPI: pid 2512, is not allowed to access the accessibility API. Path: /Applications/Phoenix.app/Contents/MacOS/Phoenix
```

Here's my phoenix.js file:
```
Key.on('z', [ 'ctrl', 'shift' ], function () {

  var screen = Screen.main().flippedVisibleFrame();
  var window = Window.focused();

  if (window) {
    window.setTopLeft({
      x: screen.x + (screen.width / 2) - (window.frame().width / 2),
      y: screen.y + (screen.height / 2) - (window.frame().height / 2)
    });
  }
});
```

**Comment by kasper** [comment]
@dhawal55 Now the bundle identifier is correct, so you likely have the right version. The first line, where it’s trying to enable accessibility support, reports a password error. Maybe it failed? Quit Phoenix and make sure the checkbox next to Phoenix is enabled in System Preferences under Privacy/Accessibility. Then launch Phoenix again.

**Comment by dhawal55** [comment]
I'm able to proceed after installing 2.3. Now, just dealing with errors in .phoenix.js. Thank you for all the help. Can you please point me to some good examples for .phoenix.js?

**Comment by kasper** [comment]
@dhawal55 Sorry for your bad experience!
