### ISSUE TITLE
window API: unique window identifier?

### ISSUE THREAD

**Issue by ntuckerxx** [kasper/phoenix#13]
There is currently no way to compare two Window instances and determine that they refer to the same window.  I'm kind of interested in writing code which keeps some per-window state, but since it can't be attached to the Window object itself, it needs to be stored somewhere else with a reference to the Window object.  Unfortunately, two separate instances of the Window object referring to the same window can't actually be definitively compared, so this is (as far as I can tell) impossible.  One way to allow this sort of mapping would be to expose the CGWindowID as a property on Window, which would let scripts store per-window state in a structure keyed by this window id.

**Comment by jasonm23** [comment]
We use `AXUIElementRef` to id unique windows, see this SO Q/A. 

http://stackoverflow.com/questions/7422666/uniquely-identify-active-window-on-os-x

Perhaps we can expose this ref via the Window object.

**Comment by kasper** [comment]
I’ll implement this soon.

**Comment by kasper** [comment]
This is resolved in the upcoming version. KeyHandlers, Screens, Apps and Windows can now be compared with `isEqual(AnyObject object)`. You can also retrieve their `hash()`-value to map objects — for instance. See the [API](https://github.com/kasper/phoenix/blob/2.0/API.md#identifiable) for reference.
