### ISSUE TITLE
With “Displays have separate Spaces” disabled, Space#screen() does not return the screen(s) for the space

### ISSUE THREAD

**Issue by rjlasko** [kasper/phoenix#130]
- Version: 2.3.49
- macOS: 10.11.3

I have been playing with Phoenix since 2.0.1 and have recently upgraded to 2.3 (yes i followed the upgrade guide with success) to be able to use Spaces when in laptop-only mode.  However, a number of my experiences with it seems to behave not-as-expected.  Here are the biggest oddities I've encountered so far...

Let's say that I am in laptop only mode, with two spaces open, and applications across both.  Also note that in Mission Control, I have the following settings:
<img width="590" alt="screen shot 2016-08-13 at 12 25 14 pm" src="https://cloud.githubusercontent.com/assets/6244698/17644335/0bc50c4c-6151-11e6-920b-c3d7975da20b.png">
1. A screen object has the currentSpace(), but not the set of all associated spaces:

```
keys.push(
    new Key('3', altButton, function() {

        Phoenix.log("Screen.all() = " + Screen.all())
        Phoenix.log("Space.all() = " + Space.all())

        var screens = Screen.all()
        for (var i = 0; i < screens.length; i++) {
            var screen = screens[i]
            Phoenix.log("screen = " + screen)
            Phoenix.log("screen.currentSpace() = " + screen.currentSpace())
            Phoenix.log("screen.spaces() = " + screen.spaces())
        }
    })
);
```

yields the following in Console:

```
8/13/16 12:32:27.497 PM Phoenix[6463]: Screen.all() = [object NSScreen]
8/13/16 12:32:27.498 PM Phoenix[6463]: Space.all() = [object PHSpace],[object PHSpace]
8/13/16 12:32:27.498 PM Phoenix[6463]: screen = [object NSScreen]
8/13/16 12:32:27.498 PM Phoenix[6463]: screen.currentSpace() = [object PHSpace]
8/13/16 12:32:27.498 PM Phoenix[6463]: screen.spaces() = 
```

I would have expected there to be two spaces associated with the one screen (my retina display), but instead i got none.  The only thing that makes sense here is screen.currentSpace().

I'm betting that this is related to the fact that I have one space shared across all displays (for when i have multiple monitors attached)

**Comment by kasper** [comment]
Hi! Sorry to hear that. If I understood correctly — everything else, except `Screen#spaces()`, seems to be working as expected. If you enable the setting “Displays have separate Spaces”, what does the function return then?

**Comment by rjlasko** [comment]
With "Displays have separate Spaces" enabled...
```
8/13/16 12:56:49.567 PM Phoenix[7478]: Screen.all() = [object NSScreen]
8/13/16 12:56:49.568 PM Phoenix[7478]: Space.all() = [object PHSpace],[object PHSpace]
8/13/16 12:56:49.568 PM Phoenix[7478]: screen = [object NSScreen]
8/13/16 12:56:49.569 PM Phoenix[7478]: screen.currentSpace() = [object PHSpace]
8/13/16 12:56:49.570 PM Phoenix[7478]: screen.spaces() = [object PHSpace],[object PHSpace]
```
It appears to work as expected in that mode, however I tend not to use that mode because it prevents windows from spanning multiple monitors (which i frequently make use of).

**Comment by rjlasko** [comment]
Also, I just want to say that this is a great app, and that I have gotten a lot of value out of it already.

While I use it for its main purpose, OSx window management, I have found it also a great way to dip my toes into JavaScript development, as I am primarily a Java/Python/C++ developer.

**Comment by kasper** [comment]
@rjlasko Thanks! Ok, I presume, with the original setup, `Space#screen()` returns `undefined`. Right? This will cause the filtering to fail. I will see how to fix this.

Apple does not provide a public API for Spaces, so unfortunately these behaviours are the side effect of using private APIs.

A window can indeed be in multiple Spaces at the same time. If you right click on an app in the Dock, you can assign its windows to only a single space or multiple spaces.

Thanks for the kind words! It’s great to get feedback from users. :smiley:

**Comment by rjlasko** [comment]
@kasper
Yes, that is correct. 
`8/13/16 2:01:43.597 PM Phoenix[8074]: screen.currentSpace().screen = undefined`

**Comment by kasper** [comment]
@rjlasko True! You’re right with your conclusion. I will see how to fix/implement this.

Don’t use `_.isEqual(...)` for comparisons — it will only compare properties. Use `Identifiable#isEqual(...)` instead for those objects that implement the interface. So that would be `screen.isEqual(otherScreen)`.

**Comment by rjlasko** [comment]
Thanks for the `Identifiable` tip!

**Comment by kasper** [comment]
Actually, I think the current behaviour is not far from the correct one. As a space can only be on a single screen or across all screens (not a subset), the following comes to mind:

1. It seems correct that `Space#screen()` returns `undefined` when the setting is disabled. In this case a space doesn’t belong to a specific screen, but all of them.
2. If there would be a`Space#screens()`, it would return all screens in this case for every space. (I’m not sure if this adds any value.)
3. However, it seems valid to implement `Screen#spaces()` to return all spaces in this case.

Although, it might be better to have a many-to-many relationship both ways. I will have to think about this one.

**Comment by rjlasko** [comment]
I think that you are correct about the bi-directional many-to-many relationship between screens and spaces.

So, my boss at work has this design idiom, "to robustly not care".  Basically meaning that the mechanism employed, or the API exposed, is tolerant to all sorts of interpretation (and lack thereof) and works just as well in the common and corner case.

If Space#screen() was deprecated or removed in favor of `Space#screens()`, the value would be that there would only be one method that could accurately represent both modes.  Otherwise the developer needs to be cognizant of both operational modes and functions when programming.  You could take the position that `Space#screen() = undefined` is actually correct, but in that mode (shared space), it is not very useful in a vacuum.  On the flip-side, to know that `Space#screens()` returns just one screen in a multi-monitor setup (separate spaces) is simplifying.

**Comment by kasper** [comment]
Definitely a valid point of view.

**Comment by kasper** [comment]
This is now fixed in master and will be released in the next release. `Space#screen()` is now deprecated and `Space#screens()` has been added to represent the correct relationship. Sorry for the wait!
