### ISSUE TITLE
windowDidFocus doesn't fire consistently

### ISSUE THREAD

**Issue by purag** [kasper/phoenix#134]
- Version: 2.3
- macOS: 10.11.5

Using the following snippet:

```js
Event.on("windowDidFocus", function (window) {
  Phoenix.log("fired");
});
```

I expect logs every time I focus a new window, but instead, I get sporadic logs, with some windows never triggering the event upon focus.

![](http://i.imgur.com/yajPJnI.gif)

Steps to reproduce:

1. Vanilla `.phoenix.js` file.
2. Log in `windowDidFocus` callback (see snippet above).

**Comment by kasper** [comment]
Hello, `windowDidFocus` is triggered when a window was focused **within** an app. This is how Apple specifies the event. You’ve got two Terminal windows open, but only one of the others. You will probably also need to listen to `appDidActivate`. It’s up to the app to support these events, with custom windows you might not even get an event. However, it should work for the majority of apps.

**Comment by purag** [comment]
Okay, that did the trick! Using `appDidActivate` alongside `windowDidFocus` works fine. (I'm fine using the same handler for both events since the handler has state checks.)

Thanks for the help!
