### ISSUE TITLE
Unable to focus other windows for same App

### ISSUE THREAD

**Issue by dominicglenn** [kasper/phoenix#136]
I've got multiple windows for an App (Chrome) and after calling `focus()` on them, they are not `isVisible()` and do not become focused; am I doing something wrong?

They are all on the same screen and simply behind the main window.
- Version: 2.3 (49)
- macOS: 10.11.6

**Comment by mafredri** [comment]
This is most likely a problem with Chrome, do you perhaps have multiple monitors/spaces, and Chrome windows / apps across these monitors/spaces? Especially in a multi-monitor setup, Chrome and Chrome apps misbehave on OS X. They try to seem like separate processes but fail miserably :(.

If you try to focus multiple times, with a bit of delay, eventually it should focus the window. With Chrome it doesn't matter which window you try to focus, it will first need to focus the Chrome itself, and only then can it focus the specific window you want.

**Comment by dominicglenn** [comment]
I'll try it doing it with a delay, basically I'm trying to build a window switch command so you can quickly switch between windows for a given app via specific keyboard shortcuts only. I usually use Chrome with 3 separate windows and just want to switch between them easily.

**Comment by dominicglenn** [comment]
@mafredri It looks like it's an issue specifically in Chrome, do you know any way around this?

**Comment by purag** [comment]
I don't have the issue of none of the windows focusing, but sometimes when I focus one window, a different one focuses. I've only noticed this problem with Chrome. Also, it's always a window on a different monitor that gets focused.

**Comment by kasper** [comment]
Somewhat related to #148. This would likely help with Chrome: https://developer.apple.com/reference/appkit/nsaccessibilityraiseaction

**Comment by kasper** [comment]
I can’t reproduce this behaviour on macOS 10.12.1, Phoenix 2.3 and Chrome 54.0.2840.98. Maybe #151  can help with certain edge cases on Phoenix 2.4.

**Comment by swieder227** [comment]
Updated from 2.3 -> 2.5 and the focus of multiple Chrome windows appears to work much more consistently.
