### ISSUE TITLE
Any way to `use Mouse.click()`?

### ISSUE THREAD

**Issue by alswl** [kasper/phoenix#138]
- Version: 2.3
- macOS: 10.11.6 (15G31)

I want to trigger mouse click().

There is an other command named 'cliclick', but now I cannot call this command via `Command`.

**Comment by kasper** [comment]
I don’t see a the point of adding a click-action to `Mouse`, since there’s no support for getting clickable targets (or their positions).

But you can certainly use external commands. There’s no `Command`-object anymore, use `Task` instead. Maybe that’s the issue?

**Comment by alswl** [comment]
```
  Task.run('/usr/local/bin/cliclick', ['c:991,385'], function(handler) {
  });
```

works for me, thanks.
