### ISSUE TITLE
Events?

### ISSUE THREAD

**Issue by chmac** [kasper/phoenix#14]
Can I bind to any kind of events? Ideally I want to write something that will grab the position of all windows on all screens when a monitor is unplugged, and then restore them when the monitor is replugged. I'm experimenting with Cordless Dog's Stay right now, but being able to hack this shit in coffeescript would be a level of 1337ness almost too tempting to resist... :-)

PS> Thanks for releasing what looks like awesome software.

**Comment by kasper** [comment]
Indeed, I would like to see basic event support as well. Therefor my intension is to take a look into implementing support for at least some useful events. I’m currently using my time to refactor the code base. :)

**Comment by kasper** [comment]
Events that could be useful and are possible to implement:

**Screen**
- [ ] Change (i.e. screens are added or removed)

**App**
- [ ] Launched
- [ ] Terminated
- [ ] Activated
- [ ] Hidden
- [ ] Shown

**Window**
- [ ] Opened
- [ ] Closed
- [ ] Focused
- [ ] Moved
- [ ] Resized
- [ ] Minimised
- [ ] Unminimised

**Comment by kasper** [comment]
Hello! I’ve implemented basic support for events in Phoenix 2.0. Wicked! In fact `screenChange` is the first event to be supported. Adding the rest should be pretty straightforward with the framework in place. I’ll update the list above as the work progresses. You can also test binding events with the 2.0-branch.

See the [API](https://github.com/kasper/phoenix/blob/2.0/API.md#events). To bind an event to a function, you call the `on`-function for the `Phoenix`-object.

```javascript
var handler = Phoenix.on('screenChange', function () {

    Phoenix.log('Screens changed.');
});
```

**Comment by kasper** [comment]
Support for app events is now implemented.

**Comment by kasper** [comment]
Support for window events is implemented. It’s safe to say that I now have nightmares about AXObserver.

**Comment by kasper** [comment]
I implemented one additional event that gets triggered once when Phoenix has started. Event support is now stable on build 7. :smile: For additional requests, please open separate issues. Thanks!
