### ISSUE TITLE
Pheonix does not bring windows to front always

### ISSUE THREAD

**Issue by sheki** [kasper/phoenix#141]
- Version: 2.3 (49)
- macOS: 10.11.6

Let me start off by saying I love Phoenix.
I have a simple enough layout which works when I trigger it twice in a row. But it does not always work on the first trigger. 

Look at this recording: 
![](http://g.recordit.co/dOZxe9EVgE.gif)

The iterm windows get sized correctly but they do not end up in front. Quip seems to block them.
But it works when I trigger the function again.

In the demo above I am just pressing `cmd + ctrl + a`

Is this user error on my part or is this a bug with the way Quip does things?

**Comment by kasper** [comment]
Thanks for the kind words! Some apps/windows might not always behave as you would expect. It’s up to the developer to support the Accessibility API and if they do something really custom with their windows, it might have some consequences in how well we can control them.

That being said, first see the logs for any warnings or errors. Then add logging to your code and evaluate whether your actions have effect. Especially observe the returned boolean values and whether the actions change the properties.

(You can also try focusing the app first, before trying to focus individual windows.)

**Comment by kasper** [comment]
Phoenix 2.4 will have an action for raising the window underneath the focused window (#151). Maybe this will help with some edge cases.
