### ISSUE TITLE
Shared Session Item

### ISSUE THREAD

**Issue by delianides** [kasper/phoenix#142]
- Version: 2.3
- macOS: 10.11.6

While debugging my `phoenix.js` script I noticed this error kept appearing in my console.

```
9/21/16 7:30:21.877 PM Phoenix[58480]: Error: Could not copy resolved URL for session login 
item <LSSharedFileListItem(4) of 0x7fc4f0536050> BundleBinding [0x431] URL: 
file:///Users/delianides/.Trash/Google%20Photos%20Backup.app/ bundle identifier: (null) mod 
time 0 Google Photos Backup. (Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File 
not found")
```
I installed phoenix through homebrew and then reinstalled it after emptying my trash but the error persisted.

Odd.

**Comment by kasper** [comment]
Weird. Look at your login launch items in System Preferences. Maybe there’s a faulty/corrupted “Google Photos Backup” item. You could try removing it (and then adding it again if needed).

**Comment by delianides** [comment]
That was it. Sorry.

**Comment by kasper** [comment]
No worries! Glad you got it sorted out!
