### ISSUE TITLE
variable Key not defined

### ISSUE THREAD

**Issue by Pfeifenjoy** [kasper/phoenix#144]
When I run my .pheonix.js the variable Key is not defined.
Therefore the Getting started script doesn't work.

- Version: 1.2
- macOS: 10.12

**Comment by kasper** [comment]
@Pfeifenjoy Hello! The current release is 2.3, do you really have version 1.2?

**Comment by Pfeifenjoy** [comment]
@kasper yes
![bildschirmfoto 2016-10-04 um 11 35 49](https://cloud.githubusercontent.com/assets/8148840/19069338/ca57acf2-8a26-11e6-9eba-42fbf31b5788.png)

I installed it via MacPorts. Maybe the package is old.

**Comment by kasper** [comment]
Well definitely. That’s the version before I took over the project. Install Phoenix through Homebrew Cask or download it directly from https://github.com/kasper/phoenix/releases.
