### ISSUE TITLE
Look into adding Touch Bar support

### ISSUE THREAD

**Issue by kasper** [kasper/phoenix#146]
Look into adding Touch Bar support for customisable and configurable actions.

**Comment by jasonm23** [comment]
For reference https://github.com/electron/electron/issues/7781

**Comment by jasonm23** [comment]
https://github.com/loretoparisi/touchbar - cheat sheet

**Comment by kasper** [comment]
Nice! Seems these resources will be handy.

**Comment by cumanzor** [comment]
As an alternative, you can try using BetterTouchTool, setting up your usual keybindings and then adding them to a customized touchbar section.

**Comment by kasper** [comment]
I think we can safely say the Touch Bar failed. I’m enjoying my physical keys on the new MacBook Pro.
