### ISSUE TITLE
Suggestion: Window.mouseFocused()

### ISSUE THREAD

**Issue by szhu** [kasper/phoenix#149]
BetterTouchTool and similar window-management apps do a lot of operations with the window that is currently being moused over. Right now the best way to get this in Phoenix is:

```js
function within(point, rect) {
  return Math.min(
    point.x - rect.x,
    point.y - rect.y,
    rect.x + rect.width  - point.x,
    rect.y + rect.height - point.y
  );
};

function mouseFocused() {
  var mouseLocation = Mouse.location();
  var windows = Window.recent();
  for (i = 0; i < windows.length; i++)
    if (within(mouseLocation, windows[i].frame()) > 0)
      return windows[i];
}
```

This common operation takes too long to write. In addition, it queries what seems like a lot of data (`Window.recent()`) and filters it down to just one window, which makes one wonder if this is the most efficient way to do so.

My suggestion: Create `Window.mouseFocused()` to accomplish this task. Here's why:

- If there is a more efficient low-level way to do this, then I want it!
- If there's not, putting this method into the standard library (1) conveys that this is the most efficient way to do this task and (2) abstracts this common task away so that people do not write it out manually.

**Comment by mafredri** [comment]
One issue I noticed with this method (while testing #148) is that it doesn't take into account anything overlaying the current window. For example, with the event trigger from #148 it made the macOS system menu bar unusable due to the mouse being within the windows coordinates, thus focusing it and closing the menu. Perhaps something to consider? And could also be a reason for a proper API if it's possible to detect this.

Other than that, only way to make this more efficient is to (AFAIK) keep a local cache of the windows and track the creation of new windows and their sizes. But caches come with their own problems so I'd advice against it for something like this.

PS. You should initialize that `i` variable, `var i = 0;` 😜.

**Comment by szhu** [comment]
This doesn't make any progress towards solving the original problem, but here is what I currently have, which is pretty usable. It doesn't re-focus the current window if it's already in front. It also ignores movement within 10px of window borders, which solves an issue with the a delay causing flashing between windows.

```coffee
within = (point, rect) ->
  return Math.min(
    point.x - rect.x,
    point.y - rect.y,
    rect.x + rect.width - point.x,
    rect.y + rect.height - point.y,
  )

focusWindowUnderMouse = ->
  mouseLocation = Mouse.location()
  window = Window.focused()
  return unless window?
  return if within(mouseLocation, Window.focused().frame()) > 0
  for window in Window.recent()
    distWithin = within(mouseLocation, window.frame())
    if distWithin > 10
      window.focus()
      return window
    else if distWithin > -10
      return window
  return false

focusWindowUnderMouseEventId = null

Event.on 'mouseDidMove', focusWindowUnderMouse
```

Also my bad, I tried to simplify automatically-converted CoffeeScript and forgot to add back a `var` declaration :)

**Comment by kasper** [comment]
I can’t remember if there was any direct API to access this information, but I can look into it.

**Comment by kasper** [comment]
Unfortunately, there doesn’t seem to be any native APIs to accomplish this. (Which is probably logical, since accessibility devices don’t need this kind of information.)

**Comment by szhu** [comment]
That's a shame there's no API for this, but regarding your reasoning, isn't it pretty important for accessibility devices to know what you're mousing over? (for people with low vision)

**Comment by kasper** [comment]
Actually, this should be possible with `AXUIElementCopyElementAtPosition`.

**Comment by kasper** [comment]
Implemented in master and will be released in the next release! 🎉 

```javascript
Event.on('mouseDidMove', event => {
  const window = Window.at(event);
  if (window) {
    Phoenix.log(window.app().name(), ':', window.title());
  }
});
```

**Comment by szhu** [comment]
Thanks, this native solution works much better than the original one!

One bug, this doesn't seem to recognize when the mouse is over a Sublime Text 3 window for some reason. Do you know why this is?

**Comment by kasper** [comment]
@szhu Does the function return anything when over the specific window?

**Comment by szhu** [comment]
It returns undefined.

**Comment by kasper** [comment]
@szhu Any errors in the log?

**Comment by szhu** [comment]
No. Are you not able to reproduce this?

**Comment by kasper** [comment]
@szhu Haven’t had time to delve into this yet, but it would seem this is specifically related to the app since I didn’t notice any behaviour like this when testing the feature. Some apps have rather poor support for the Accessibility API. ☹️

**Comment by szhu** [comment]
Is this a bug we can file in [https://github.com/SublimeTextIssues/Core](SublimeTextIssues/Core)?
