### ISSUE TITLE
Firing automatically and not binding

### ISSUE THREAD

**Issue by julesmoretti** [kasper/phoenix#150]
Hello there:

Somehow the actions are being fired automatically and then are not able to be re-triggered... Could you please point out the obvious that I am missing here :)

Also could someone please indicate where log files (Phoenix.log('hello world')) are stored?

```
Phoenix.set({
	daemon: true,
	openAtLogin: true
});

var moveAndResize = function( numOfCol, numOfRow, rowIndex, colIndex ) {
	var screen = Screen.main().flippedVisibleFrame();
	var window = Window.focused();

	var colWidth = (screen.width / numOfCol);
	var rowWidth = (screen.height / numOfRow);

	if (window) {
		window.setTopLeft({
			x: colWidth * colIndex,
			y: rowWidth * rowIndex
		});

		window.setSize({
			width: colWidth,
			height: rowWidth
		});
	}

}

Key.on('up', [ 'shift', 'ctrl', 'alt', 'cmd' ], moveAndResize(1,1,0,0));
Key.on('-', [ 'ctrl', 'alt', 'cmd' ], moveAndResize(2,2,0,0));
Key.on('=', [ 'ctrl', 'alt', 'cmd' ], moveAndResize(2,2,0,1));
Key.on('[', [ 'ctrl', 'alt', 'cmd' ], moveAndResize(2,2,1,0));
Key.on(']', [ 'ctrl', 'alt', 'cmd' ], moveAndResize(2,2,1,1));
```

**Comment by kasper** [comment]
Hello!

1. You are calling the “moveAndResize” function immediately with arguments when binding the keys. (When it is evaluated.) Instead create a new function that calls the function eventually when the key event triggers it.

```javascript
Key.on(..., function () {
  moveAndResize(...);
});

2. Logs are outputted to the system log, which you can observe with the “Console” app.

Hope this helps!

**Comment by julesmoretti** [comment]
@kasper - Sorry but one last question when I `Phoenix.log(Window.focused());`, I get:

```
11/15/16 10:15:32.090 AM Phoenix[3838]: [object NSScreen]
```

How can I inspect the content of `[object NSScreen]`? 

I tried JSON.stringify(Window.focused()) but that did not work.

Thank you for your help :)

**Comment by kasper** [comment]
@julesmoretti `JSON.stringify(...)` works for objects with properties. Therefor it will not always work. Instead observe the output of function calls and values or try something like `JSON.stringify(Window.focused().frame())`.

**Comment by kasper** [comment]
And no worries, I’m glad you’re trying Phoenix out and we’re here to help! :smile:
