### ISSUE TITLE
Window setTopLeft => wrong screen and not exact size

### ISSUE THREAD

**Issue by julesmoretti** [kasper/phoenix#152]
Hello there:

I am trying to get the focused window be rescale within the current screen. But unfortunately when having 2 monitors those gets rescaled back into the main monitor and not remaining within the focused one.

1. Therefore how can I make sure that that window stays in the same screen?

2. And secondly how do I make sure the the rescaling is exact rather than currently off by 10 pixel or so....

Here is my function:

```
var gridMove = function(numbOfCol, numbOfRow, colIndex, rowIndex) {
	if (Window.focused()) {
		var win = Window.focused();
		var size = win.size();
		var frame = win.screen().flippedFrame();

		size.width = frame.width / numbOfCol;
		size.height = ( (win.screen().flippedFrame().height + win.screen().visibleFrame().height) / 2) / numbOfRow;

		win.setTopLeft({
			x: size.width * colIndex,
			y: size.height * rowIndex
		});
		win.setSize(size);
	}
}
``` 

Thank you :)

- Version: 2.3
- macOS: 10.10.5

**Comment by kasper** [comment]
Well, the calculation is incorrect, but I assume you already knew that. :smile: Go through your code step-by-step and observe what changes they have. (For example, why are you multiplying the height of your display by adding the values from both the frame and flippedFrame?)

**Comment by julesmoretti** [comment]
I am glad you asked.

So my MacBook Pro screen is 1440px by 900px.

I keep my dock hidden so that is not a problem but there is the top bar navigation bar (where the clock, apple icon etc.. is ) and that one is about 22px.

Looking at the Window.focused().screen().flippedFrame() I get the following data:
`{"y":0,"x":0,"width":1440,"height":900}`

on the other hand when I look at Window.focused().screen().visibleFrame() I get:
`{"y":4,"x":0,"width":1440,"height":873}`

Now neither of those are exactly the right height without the top bar as it should return 878 hence why I did this simple mean calculation...

So which one returns the exact height, excluding the top nav?

**Comment by julesmoretti** [comment]
So to recap a more accurate method using what I know is:

```
var gridMove = function(numbOfCol, numbOfRow, colIndex, rowIndex) {
	if (Window.focused()) {
		var win = Window.focused();
		var size = win.size();
		var frame = win.screen().flippedFrame();

		var topNav = 23;
		var bottomGap = 4;

		size.width = frame.width / numbOfCol;
		size.height = ( win.screen().flippedFrame().height - topNav - bottomGap ) / numbOfRow;

		win.setTopLeft({
			x: size.width * colIndex,
			y: (size.height * rowIndex) + topNav
		});
		win.setSize(size);
	}
}
```

whats missing for me now is how to get the window to persist within the current screen and or be able to send the window to another screen...

**Comment by kasper** [comment]
You should use “flippedVisibleFrame”. It reflects the current situation and gives you the correct frame when the Dock and/or Menu are visible or hidden. When the Dock is hidden it takes 4 points from the bottom of the screen, this is used for the activation area where the Dock automatically shows when you hover your mouse there. There’s no need to account for these yourself.

For keeping the window within the screen, you need to adjust the origin. When you resize the window, it will be resized from the current location. Use “setFrame” to adjust both the origin and size of the window at the same time.

**Comment by kasper** [comment]
There’s a lot of similar examples in the [Wiki](https://github.com/kasper/phoenix/wiki/). Take a look at them for guidance!

**Comment by julesmoretti** [comment]
Thank you for your help. 

I did see the wiki, but it is a bit of an overload of examples with no simply referenced/focused examples for me to relate to.

On the other hand your above points were very useful but did not seem to resolve this screen window reference. A window that is manipulated on the second screen will get resized into the main screen.

Additionally using the "flippedVisibleFrame" and the "setFrame" I did still have to shift the "y" coordinate by 23 pixels down otherwise there are over laps.

So this is the function I have now:

```
var gridMove = function(numbOfCol, numbOfRow, colIndex, rowIndex) {
	if (Window.focused()) {
		var win = Window.focused();
		var size = win.size();
		var frame = win.screen().flippedVisibleFrame();
		var topNav = 23;

		win.setFrame({
			"y": (size.height * rowIndex) + topNav,
			"x": size.width * colIndex,
			"width": frame.width / numbOfCol,
			"height": ( frame.height ) / numbOfRow
		});

		Phoenix.log( '-------------------------' );
		Phoenix.log( 'window - ' + JSON.stringify(win ));
		Phoenix.log( 'window - screen - hash - ' + JSON.stringify(win.screen().hash() ));
		Phoenix.log( 'window - size - ' + JSON.stringify( size ));
		Phoenix.log( 'window - flippedframe - ' + JSON.stringify( frame ));
		Phoenix.log( 'window - screen - visible - ' + JSON.stringify(win.screen().visibleFrame() ));
		Phoenix.log( 'spaces - ' + JSON.stringify(Space.all() ));
		Phoenix.log( 'screens all - ' + JSON.stringify(Screen.all() ));

		for ( var i = 0; i < Screen.all().length; i++ ) {
			Phoenix.log( 'screens # - ' + i + " - "+ JSON.stringify(Screen.all()[i].frame() ));
		}

		Phoenix.log( 'screens all - 1st - hash - ' + JSON.stringify(Screen.all()[0].hash() ));
		Phoenix.log( 'screens main - ' + JSON.stringify(Screen.main() ));
		Phoenix.log( 'screens main identifier - ' + JSON.stringify(Screen.main().identifier() ));
		Phoenix.log( JSON.stringify(Screen.main().visibleFrame() ));
		Phoenix.log( JSON.stringify(Screen.main().flippedFrame() ));
		Phoenix.log( JSON.stringify(win.screen().flippedFrame() ));
		Phoenix.log( JSON.stringify(win.size() ));
	}
}
```

Which outputs the following when I hit keys to do half screen right twice consecutively:

As you will see the first time, it stays in the second screen but in the wrong place because my second screen is taller then my laptop. And then on the second stroke it moves to the main screen even though focused on the second screen.

So is there a "setFrame" equivalent but for "screen"... something like "setScreen"?

```
11/21/16 10:51:07.335 PM Phoenix[709]: -------------------------
11/21/16 10:51:07.335 PM Phoenix[709]: window - {}
11/21/16 10:51:07.340 PM Phoenix[709]: window - screen - hash - 69479936
11/21/16 10:51:07.340 PM Phoenix[709]: window - size - {"width":1440,"height":873}
11/21/16 10:51:07.340 PM Phoenix[709]: window - flippedframe - {"y":23,"x":1440,"width":1680,"height":1023}
11/21/16 10:51:07.340 PM Phoenix[709]: window - screen - visible - {"y":-146,"x":1440,"width":1680,"height":1023}
11/21/16 10:51:07.340 PM Phoenix[709]: spaces - []
11/21/16 10:51:07.341 PM Phoenix[709]: screens all - [{},{}]
11/21/16 10:51:07.341 PM Phoenix[709]: screens # - 0 - {"y":0,"x":0,"width":1440,"height":900}
11/21/16 10:51:07.341 PM Phoenix[709]: screens # - 1 - {"y":-150,"x":1440,"width":1680,"height":1050}
11/21/16 10:51:07.341 PM Phoenix[709]: screens all - 1st - hash - 69733250
11/21/16 10:51:07.341 PM Phoenix[709]: screens main - {}
11/21/16 10:51:07.342 PM Phoenix[709]: screens main identifier - "6D82DCC3-ABCB-198D-A4F2-043F9EA0C091"
11/21/16 10:51:07.342 PM Phoenix[709]: {"y":-146,"x":1440,"width":1680,"height":1023}
11/21/16 10:51:07.342 PM Phoenix[709]: {"y":0,"x":1440,"width":1680,"height":1050}
11/21/16 10:51:07.342 PM Phoenix[709]: {"y":0,"x":1440,"width":1680,"height":1050}
11/21/16 10:51:07.343 PM Phoenix[709]: {"width":840,"height":1023}
11/21/16 10:51:11.368 PM Phoenix[709]: -------------------------
11/21/16 10:51:11.368 PM Phoenix[709]: window - {}
11/21/16 10:51:11.369 PM Phoenix[709]: window - screen - hash - 69733250
11/21/16 10:51:11.369 PM Phoenix[709]: window - size - {"width":840,"height":1023}
11/21/16 10:51:11.369 PM Phoenix[709]: window - flippedframe - {"y":23,"x":1440,"width":1680,"height":1023}
11/21/16 10:51:11.369 PM Phoenix[709]: window - screen - visible - {"y":0,"x":0,"width":1440,"height":877}
11/21/16 10:51:11.369 PM Phoenix[709]: spaces - []
11/21/16 10:51:11.369 PM Phoenix[709]: screens all - [{},{}]
11/21/16 10:51:11.369 PM Phoenix[709]: screens # - 0 - {"y":0,"x":0,"width":1440,"height":900}
11/21/16 10:51:11.369 PM Phoenix[709]: screens # - 1 - {"y":-150,"x":1440,"width":1680,"height":1050}
11/21/16 10:51:11.369 PM Phoenix[709]: screens all - 1st - hash - 69733250
11/21/16 10:51:11.370 PM Phoenix[709]: screens main - {}
11/21/16 10:51:11.370 PM Phoenix[709]: screens main identifier - "6D82DCC3-ABCB-198D-A4F2-043F9EA0C091"
11/21/16 10:51:11.370 PM Phoenix[709]: {"y":-146,"x":1440,"width":1680,"height":1023}
11/21/16 10:51:11.371 PM Phoenix[709]: {"y":0,"x":1440,"width":1680,"height":1050}
11/21/16 10:51:11.371 PM Phoenix[709]: {"y":0,"x":0,"width":1440,"height":900}
11/21/16 10:51:11.371 PM Phoenix[709]: {"width":840,"height":877}

```

**Comment by kasper** [comment]
Technically, all of your displays form a large rectangle. To move a window to a specific screen, you need to calculate the position within this large rectangle in relation to the coordinates provided by the screen.

**Comment by kasper** [comment]
Try this:

1. Use `Window#maximise()` to maximise a window to fill the visible frame of the screen where the window currently is.
2. Then resize the window, by dividing its width and height by the column and row count. Then multiply by the factor.
3. When you have that working, change “maximise” with the screen frame and observe that the calculations are still correct.
4. Then, you can change it to use the screen frame for the display you want the window to be. Remember that now you also need to adjust the top-left origin for the window to align in properly.

Make these in steps, log the frames and observe the behaviour. Then adjust accordingly.

**Comment by julesmoretti** [comment]
Ok so back at the office and trying on my 2 screens:

1. That works indeed using `Window.focused().maximise();` on both screens

2A. Resizing using the following works on both screen:
```
Window.focused().maximise();
var tempSize = Window.focused().size();
Window.focused().setSize({ width: tempSize.width / numbOfCol, height: tempSize.height / numbOfRow });
```

2B: moving then the screen does not work, using the following method:
```
Window.focused().maximise();
var tempSize = Window.focused().size();
Window.focused().setSize({ width: tempSize.width / numbOfCol, height: tempSize.height / numbOfRow });
Window.focused().setTopLeft({x: tempSize.width / numbOfCol * colIndex, y: (tempSize.height / numbOfRow * rowIndex ) + tempSize.y});
```

and get the following error message:

```
11/28/16 12:09:17.500 PM Phoenix[709]: Error: Could not set accessibility attribute “AXPosition” with value “<AXValue 0x60800024b7c0> {value = x:1720.000000 y:nan type = kAXValueCGPointType}” for element <AXUIElement 0x60000005e300> {pid=14733}. (-25200)
```

and if instead I use `setFrame` it works on the main screen but not on the secondary screen (from the secondary it gets pushed back to my main screen instead):

```
Window.focused().maximise();
var tempSize = Window.focused().size();
Window.focused().setFrame({
	"y": tempSize.height / numbOfRow * rowIndex,
	"x": tempSize.width / numbOfCol * colIndex,
	"width": tempSize.width / numbOfCol,
	"height": tempSize.height / numbOfRow
});
```

**Comment by kasper** [comment]
The error clearly states that your calculation for the Y-coordinate produces NaN (not a number). 

Maximise maximises the window in the screen where it currently is, to move a window to a different screen, you need to use the coordinates for the other screen in your calculations.

**Comment by julesmoretti** [comment]
Duh! Thank you for that.

So yeah I see what you mean about the screen calculations... 

The issue that I am facing is that it is not a universal solution. Because if I have screens positioned differently (say vertically see bellow) between work and home setup, then moving screen position calculations does not stick.

![screen shot 2016-11-29 at 11 29 17 am](https://cloud.githubusercontent.com/assets/744300/20725651/68a5b2d8-b627-11e6-8793-44ffffd6352e.png)

![screen shot 2016-11-29 at 11 29 48 am](https://cloud.githubusercontent.com/assets/744300/20725656/6bc41658-b627-11e6-867a-20f724d5f386.png)

Based on my main screen being: {"width":3440,"height":1413}
And my laptop one being: {"width":1440,"height":877}

For the top screenshot the code for that would be:
```
Window.focused().maximise();
var tempSize = Window.focused().size();
Window.focused().setSize({ 
	width: tempSize.width / numbOfCol, 
	height: tempSize.height / numbOfRow });
Window.focused().setTopLeft({
	x: (tempSize.width / numbOfCol * colIndex) - 1440,
	y: (tempSize.height / numbOfRow * rowIndex) + 1413 - 877});
```

But for the second screen shot I am not sure how to identify that offset in the screen alignment.

So is there a way so see where the laptop screen is relative to the Larger one?

**Comment by mafredri** [comment]
Instead of using hard-coded offsets, why not calculate the relative change?

For example, I use the following function (compiled from TypeScript) to move a window from one screen to another, whilst maintaining its relative size on that screen.

```javascript
function frameRatio(a, b) {
	var widthRatio = b.width / a.width;
	var heightRatio = b.height / a.height;
	return function (_a) {
		var width = _a.width, height = _a.height, x = _a.x, y = _a.y;
		width = Math.round(width * widthRatio);
		height = Math.round(height * heightRatio);
		x = Math.round(b.x + (x - a.x) * widthRatio);
		y = Math.round(b.y + (y - a.y) * heightRatio);
		return { width: width, height: height, x: x, y: y };
	};
}

var win = Window.focused();
var oldScreen = win.screen();
var newScreen = oldScreen.next()

var applyRatio = frameRatio(oldScreen.flippedVisibleFrame(), newScreen.flippedVisibleFrame());
win.setFrame(applyRatio(win.frame());
```

It takes into account the position of the screens by including their `x` and `y` values in the calculation.

**Comment by julesmoretti** [comment]
@mafredri - this is exactly what I was looking for.

And so along with the above the subtlety for me was the way to properly use phoenix logs:

```
var currentScreen = win.screen();
var nextScreen = currentScreen.next().flippedVisibleFrame();
Phoenix.log('test log called', nextScreen);

logs out =>> test log called
```

and same for the following:

```
var currentScreen = win.screen();
var nextScreen = currentScreen.next().flippedVisibleFrame();
Phoenix.log('test log called', JSON.stringify(nextScreen));

logs out =>> test log called
```

BUT! when you write it like this, things get properly logged!

```
var currentScreen = win.screen();
var nextScreen = currentScreen.next().flippedVisibleFrame();
Phoenix.log('test log called ' + JSON.stringify(nextScreen));

logs out =>> test log called {"y":563,"x":-1440,"width":1440,"height":877}
```

Which revealed what I was missing all along! The x and y coordinate from a macro level.. lol!

Again though thank you both and @mafredri this was the key for me :)

**Comment by kasper** [comment]
Ah, well `Phoenix.log` does not accept any parameters except for the message — as described in the API. I guess we could add the support for outputting multiple objects. Anyway, glad you figured it out!

**Comment by mafredri** [comment]
@julesmoretti glad it was of help!

Regarding `Phoenix.log`, I use my own log wrapper to get a more `console.log` like feel:

```javascript
function log(...args) {
	args = args.map((arg) => stringify(arg));
	Phoenix.log(args.join(' '));
}

function stringify(value) {
	switch (typeof value) {
		case 'object':
			return JSON.stringify(value, null, 2);
		case 'function':
			return value.toString();
		default:
			return value;
	}
}
```

I think the defined behaviour of `Phoenix.log` is easily overlooked due to the familiarity of `console.log` for most (all?) JS devs, which in turn leads to confusion. It was a long time ago, but I recall also being confused about it in the beginning, and assuming it worked like `console.log`.

**Comment by julesmoretti** [comment]
@mafredi - thank you for sharing and I do like very much and will use also your above functions :)
