### ISSUE TITLE
App.launch('ScreenSaverEngine')

### ISSUE THREAD

**Issue by julesmoretti** [kasper/phoenix#154]
I have a feeling that this is going to be a no brainer for some of you.

I am trying to have screen saver launch on keypress but when I try, the screen saver turns on for a fraction and then turns off again.

Here is my code:

```
var screenSaver = function() {
	// App.launch('itunes');
	App.launch('ScreenSaverEngine');
}

Key.on('down', allFour, function(){ screenSaver() });
```

PS I also noticed then when I was trying with iTunes, it would say `iTunes is running in safe mode`

**Comment by mafredri** [comment]
I don't know about iTunes, but I'd imagine the screensaver is reacting to the fact that you're releasing your key after it has launched.

Try this:

```javascript
Key.on('down', allFour, function(){ setTimeout(screenSaver, 1000); });
```

It slightly delays the screensaver activation, but gives you ample time to release the keys.

**Comment by julesmoretti** [comment]
@mafredri - that sure did work! 

Thank you very much.
