### ISSUE TITLE
Question: rebind 'control-n' to 'right_arrow" and have it pass through additional pressed modifiers (ala Karabiner)?

### ISSUE THREAD

**Issue by petonic** [kasper/phoenix#155]
- Version: n/a
- macOS: 10.12.1

Self-explanatory, but the use-case is that I want to map "control-{npfb}" to  the "{down, up, right, left}" arrow keys without writing every permutation of the modifier keys.

HammerSpoon almost gets it right, but the modifier string in the function must be an exact match, so that one binding that maps Control-N to Down-Arrow, does not map Shift-Control-N to Shift-Down-Arrow.

Karabiner allowed you to do that.  Love my new 3.3ghz, 1TB, 16GB MBP13", hating Sierra .. :-/

Thanks!

**Comment by kasper** [comment]
Phoenix does not support reassigning key combinations to other key combinations.

However, you can easily create a loop for all the permutations and run an external task to trigger the key event and extend Phoenix. You could use AppleScript, JavaScript automation or something like https://github.com/BlueM/cliclick/ to achieve this.
