### ISSUE TITLE
Detect mouse pressed (dragging)

### ISSUE THREAD

**Issue by mrbar42** [kasper/phoenix#159]
- Version: 2.4 (55)
- macOS: 10.11.6

It seems like there is no way to observe weather the mouse is clicked and hold.
I want to use it to create a dragging event.

Is it possible?
am i missing anything?

**Comment by kasper** [comment]
Yes, I think I should be able to add support for this event. In the meanwhile you could use a combination of the click and move events with the help of something like `_.debounce` to detect this.

**Comment by kasper** [comment]
Implemented in master and will be released in the next release.
