### ISSUE TITLE
Implement support for an input modal

### ISSUE THREAD

**Issue by kasper** [kasper/phoenix#163]
It has become clear that many use the modal for submitting text based input and commands to Phoenix. Since you need to bind every single key on your keyboard to make this work properly, it’s not really convenient. So we should really implement support for an input/prompt modal with relevant customising options and event callbacks for handling this use case.

**Comment by kasper** [comment]
Somewhat related to #158.

**Comment by calebpeterson** [comment]
I got something to work using https://github.com/chipsenkbeil/choose (`brew install choose-gui`).

I use it to jump between open windows:

```js
const OSASCRIPT_PATH = "/usr/bin/osascript";

const osascript = (script, callback = _.noop) =>
  Task.run(OSASCRIPT_PATH, ["-e", script], callback);

// Jump Between Open Windows
keys.push(
  new Key("j", ["cmd"], function () {
    const windows = Window.all({ visible: true });
    const titles = windows.map((window) => window.title()).join("\n");

    osascript(
      `do shell script "echo '${titles}' | /usr/local/bin/choose -c ff4a00 -n ${windows.length} -s 18 -m"`,
      (r) => {
        if (r.error) {
          log(`Choose failed ${r.status} ${r.error}`);
        } else {
          const selection = r.output.trim();
          const target = windows.find((window) => window.title() === selection);
          if (target) {
            log(`Focusing ${target.title()}`);
            target.app().focus();
            target.focus();
          }
        }
      }
    );
  })
);
```

cc @apazzolini

**Comment by kasper** [comment]
@calebpeterson Sounds cool!

**Comment by kasper** [comment]
Never too late! 😄 This will be released in the next version, available now for testing in master.

<img width="1011" alt="input-modal" src="https://user-images.githubusercontent.com/925851/153767160-3d89712f-8532-4f7e-9db6-cbf68c60799d.png">
