### ISSUE TITLE
Suggestion: Support modifier left and right, e.g. cmd_right cmd_left

### ISSUE THREAD

**Issue by DomiR** [kasper/phoenix#165]
Some people like me remap their hyper key combo to the right cmd...

Karabiner did it with custom kext, but this should be easily done.
https://github.com/tekezo/Karabiner/blob/master/src/core/kext/KeyCode.cpp

**reference:** http://stackoverflow.com/questions/10715910/is-there-a-way-to-differentiate-between-left-and-right-shift-keys-being-pressed

Let me know if you are interested.

**Comment by jasonm23** [comment]
UX and existing config wise, this would be best to do as modifiers cmd/opt/ctrl/shift triggered by both left and right, and introduce `cmd_left`,  `cmd_right` (etc.) as the specific keys.

**Comment by kasper** [comment]
Or you could give this information as an argument to the callback. I’ll see whether this is simple to implement with the hot key API. Might not be.

**Comment by kasper** [comment]
Based on the API, you cannot bind exclusively left or right modifiers, but we can likely return that information in the callback.

**Comment by palashkaria** [comment]
Is there a way to do this/a workaround currently? I need to target left and right shift separately @kasper

**Comment by kasper** [comment]
@palashkaria Hi! Currently no, but I have full intentions to add this to the event properties if possible.

**Comment by kasper** [comment]
Unfortunately, without some kernel hacking, this does not seem to be doable. Both left and right modifiers return the same code in modern macOS versions. Let me know if I’m wrong.

**Comment by fabiospampinato** [comment]
It would have been amazing if this was supported, as it would enable mapping the caps lock key to some useless key like the right_alt key, without using any third-party utility, just the "hidutil" from macos itself.

**Comment by RichGuk** [comment]
@kasper Is this still the case? I'm wondering how apps like [skhd](https://github.com/koekeishiya/skhd/issues/1) and [rcmd](https://lowtechguys.com/rcmd/) do this, as they seem to support right_cmd (I've tested skhd).

**Comment by kasper** [comment]
@RichGuk I haven’t been able to find a way at least with the hot key API. I think these apps are likely tapping to just normal keyboard events and not exclusively binding the key. That support could be added to events.
