### ISSUE TITLE
WIBNI I could send key-presses to programs?

### ISSUE THREAD

**Issue by kgrossjo** [kasper/phoenix#171]
- Version: 2.5 (59)
- macOS: 10.12.2

Many cool things could be done if I could send key-presses to the currently focused application.  For example, one could implement vi-like navigation (hjkl = cursor left/down/up/right).

**Comment by kasper** [comment]
I’m not entirely sure if I understand what you are trying to achieve… I guess you could use an external task to run an AppleScript/JavaScript macOS automation script or use an external process to accomplish this.

**Comment by kgrossjo** [comment]
I used to use Karabiner and I was happy.  But then Sierra happened, and now Karabiner doesn't work anymore.  Karabiner Elements exists but it doesn't do that much, yet.

Using Karabiner, I could hit a key to enter "vi mode".  Then, I could use hjkl to move the cursor.  Then I could use a different key to leave "vi mode", allowing me to actually enter things.

So I would implement a mode that listens for hjkl (and some other keys), and h is the same as pressing cursor-left, j is the same as cursor-down, and so on.

And w is like Option-right and b is like Option-left...

**Comment by kasper** [comment]
I feel tapping to key events is a bit out of the scope for this app and can require quite hacky solutions, but I can consider this.

**Comment by kasper** [comment]
I feel like we do not want to support this. For now, use AppleScript, JavaScript automation or https://github.com/BlueM/cliclick/ to achieve this by running external tasks from Phoenix. Thanks for the feedback!
