### ISSUE TITLE
Bind Event on CMD+TAB

### ISSUE THREAD

**Issue by antonbrams** [kasper/phoenix#172]
how can i fire an event by capturing the cmd+tab shortcut?
cool tool and thanks!

**Comment by kasper** [comment]
Hello! The following should work:

```javascript
Key.on('tab', [ 'cmd' ], () => {});
```

**Comment by antonkluev** [comment]
nope, unfortunately not :(

**Comment by mafredri** [comment]
Since `Cmd+Tab` is used by the system to switch between applications, I think you first need to find a way to change or remove that binding.

Alternatively, @kasper would it be possible for Phoenix to override other keybindings, like this for instance?

**Comment by kasper** [comment]
Right, totally forgot about the switcher. Nope, Phoenix is not able to register key combinations that have been exclusively registered to another app.

@antonkluev You could always add a second modifier to the shortcut.

**Comment by antonkluev** [comment]
guys, do you have any ideas how can i implement the cursor jump to the switched window with cmd+tab? I use two displays and it's annoying to pull my mouse across long distance... If i will use ctrl+tab instead, phoenix doesn't have the 'window switcher' command, that i could bind to this shortcut... any throughs?

**Comment by antonkluev** [comment]
p.s. i don't want to remove or override the cmd+tab, i wanna add cursor jump functionality... just trigger the event.

**Comment by kasper** [comment]
@antonkluev Listen to the `windowDidFocus`-event instead and use that to move the mouse?

**Comment by antonkluev** [comment]
then if i will change the focus with the mouseclick on the window and it will jump to the previous position... unfortunately it's not a good hack :(

**Comment by mafredri** [comment]
On `windowDidFocus` you could check the current mouse position. If it's on another screen, move it to the window. Or, if you want, check if the mouse not inside the window and move it there (independent of screen).

This way you can focus a new window with the mouse and the mouse will not move.

**Comment by antonkluev** [comment]
great idea :) i like that, and thanks for the propose

**Comment by antonkluev** [comment]
Here i share my result, it works perfect for me :)
Feel free to use it and thank you for your help.

```
var lastScreen  = null
var mouseCoords = {}

var handler = new Event('appDidActivate', function () {
    // get screen of the focused app
	var screen = App.focused().isActive()? App.focused().mainWindow().screen(): null
    // if the app is on the screen
    if (screen) {
        // get screen information
        var id = screen.identifier()
        var sc = screen.flippedVisibleFrame()
        var mo = Mouse.location()
        // point collision detection with the screen
        var sameScreen = sc.x<mo.x&&mo.x<sc.x+sc.width&&sc.y<mo.y&&mo.y<sc.y+sc.height
        // initialize last screen
        if (!lastScreen) lastScreen = id
        // save and restore mouse position if screen was switched
    	if (!sameScreen) {
            // save current mouse location on the old screen
            mouseCoords[lastScreen] = mo
            // restore old mouse location from the current screen
            if (mouseCoords[id]) Mouse.move(mouseCoords[id])
        }
        // save current screen to the last screen
    	lastScreen = id
    }
})
```

**Comment by kasper** [comment]
@antonkluev Great that you found the solution for your problem!
