### ISSUE TITLE
Please Support Mac Keys

### ISSUE THREAD

**Issue by brandondrew** [kasper/phoenix#173]
Phoenix looks very impressive, but has an aesthetic flaw.

OS X/macOS does not have any key named "cmd"—it has "command".   (In fact, I'm not aware of any OS that has a "cmd" key.)  Likewise, it does not have a key with "ctrl" printed on it, but rather "control".

It would be preferable for software that only runs on Macs to support the keys that Macs ship with:

* command (not "cmd")
* control (not "ctrl")
* option ("alt" can be an alias, since Apple decided that this is the key to be used for "alt" when running Windows or connecting remotely to a machine running Windows.)

Thanks!

**Comment by kasper** [comment]
Hi! I’m all for linguistics, but Apple previously shortened the keys as cmd, ctrl and alt. In the newer keyboards they aren’t anymore abbreviated. I can certainly add the full labels as aliases, but you can also do this in your configuration.

```javascript
const command = 'cmd';
const control = 'ctrl';
const option = 'alt';

Key.on('q', [ command, control ], () => {});
```

**Comment by brandondrew** [comment]
I was skeptical, but it turns out you're right about 'ctrl'.  Apple did print that as an abbreviation at one time.

**Comment by kasper** [comment]
@brandondrew LOL. You don’t have to go that far, MacBooks from a couple of years ago have it as “ctrl”.

**Comment by jasonm23** [comment]
Funny, my old apple keyboard has Control...

![](https://i.imgur.com/ZRgEMGM.jpg)

**Comment by jasonm23** [comment]
(It used to be one of these)

![](https://www.fourkitchens.com/wp-content/uploads/2017/01/keyboard2.jpg)

**Comment by kasper** [comment]
Haha, this is getting nostalgic.

**Comment by mafredri** [comment]
My MacBook Pro (Late 2013) says `cmd`, `alt`, `ctrl`. Nice try guys, I can smell the photoshop in those pictures!

**Comment by jasonm23** [comment]
> I can smell photoshop 

Sorry no you can't.  Any angle you'd like that board photographed from, I'm happy to oblige.

**Comment by jasonm23** [comment]
![](http://i.imgur.com/sB1d53d.jpg)

:)

**Comment by jasonm23** [comment]
Simulating low light CCD grain in Photoshop is tricky

**Comment by kasper** [comment]
🎺

**Comment by brandondrew** [comment]
I think the issue might be internationalization.  Several (most?) of the keyboards I found online with abbreviations were localized for some language other than English.  It's possible that this was done by some company other than Apple.   

I don't personally remember ever seeing "ctrl" on an Apple keyboard, but the evidence is online. 

Before people argue about a certain model year having or not having abbreviations, it might be useful to specify what language the keyboard was localized for.

Also, let's not let this become hostile.  ☹️    I think we all agree that Phoenix is mega-awesome.

**Comment by kasper** [comment]
Nothing hostile, I can definitely add the aliases.

**Comment by kasper** [comment]
This travesty is now sorted! Thanks for the feedback. 👍
