### ISSUE TITLE
Other way to identify windows besides title()?

### ISSUE THREAD

**Issue by Neireau** [kasper/phoenix#177]
- Version: 2.5 (59)
- macOS: 10.11.6

Is there a other way to identify windows besides title()?

I'm using a full screen toggle, to do this I save the frame before going fullscreen, the problem is I name the frame 'App()::Title()' so if the title changes the toggle doesn't work anymore.

**Comment by kasper** [comment]
Hi! Yes, a window implements [Identifiable](https://github.com/kasper/phoenix/blob/master/docs/API.md#10-identifiable). Use for example the hash value to store the window reference.

**Comment by Neireau** [comment]
Thanks! That immediately solved the problem.
