### ISSUE TITLE
How to get $HOME environment variable

### ISSUE THREAD

**Issue by gutenye** [kasper/phoenix#180]
I tried `process.env.HOME`, but got `ReferenceError: Can't find variable: process (66:14)` error

**Comment by mafredri** [comment]
`process` is a Node thing and isn't available in Phoenix.

@kasper probably knows if there's a better way, but the only way I can think of is to fetch environment info via the Task API.

```javascript
function getEnv(name = '') {
	return new Promise((resolve, reject) => {
		if (name === '') {
			return reject('no variable name provided');
		}

		Task.run('/bin/sh', ['-c', `echo "$${name}"`], (t) => {
			if (t.status === 0) {
				return resolve(t.output);
			} else {
				return reject(`could not execute command to fetch '$${name}'`);
			}
		});
	});
}

getEnv('HOME').then(v => Phoenix.log('HOME = ' + v));
// Output:
// HOME = /Users/mafredri
```

Here's we're relying on the environment available when starting `/bin/sh`, you could also replace it with `bash` or `zsh` if you use those shells instead.

**Comment by gutenye** [comment]
@mafredri Thanks, this works for me.
