### ISSUE TITLE
Feature request: Better stack traces for errors

### ISSUE THREAD

**Issue by mafredri** [kasper/phoenix#181]
Would it be possible to improve the stack traces of errors in Phoenix?

Just now I was experimenting with pretty-printing errors in Phoenix and noticed that the stack trace isn't as helpful as it could be in figuring out where/how the error happened.

By default, when calling `Phoenix.log` you would see:

```
Error: could not parse brightness
```

Now, I managed to improve it slightly (mimic:ing chrome console output):

```javascript
if (value instanceof Error) {
	let stack = '';
	if (value.stack) {
		const s = value.stack.trim().split('\n');
		s[0] += ` (:${value.line}:${value.column})`;
		const indented = s.map((line) => '\t at ' + line).join('\n');
		stack = `\n${indented}`;
	}
	return `\n${value.name}: ${value.message}${stack}`;
}
```

Now we get:

```
Error: could not parse brightness
	 at parseBrightness (:341:24)
	 at parseBrightnessWrapper
	 at promiseReactionJob@[native code]
	 at [native code]
```

Biggest issue here is that e.g. `parseBrightnessWrapper` has no line number but we also don't know from which file this originates (or do we?). Also, maybe `Phoenix.log` could be changed to print error+stack when a pure error is passed as a parameter? This could help users in figuring out where the errors are coming from.

A further improvement (if possible!) would be to support sourcemaps, right now I would have to consult my compiled JavaScript code instead of the raw TypeScript sources.

**Comment by kasper** [comment]
Yes, definitely the error handling can and should be improved. I’ll try to improve it once I have more time.

**Comment by mafredri** [comment]
> I’ll try to improve it once I have more time.

Cool, no hurry. Hoping the code in this issue can help other users in the meantime.

---

Slightly off-topic, but a bit related:

Would it be possible to expose remote debugging from Phoenix? According to my understanding, the debugging / inspector code exist in JavaScriptCore now-a-days.

The idea here would be that you could connect to Phoenix via e.g. the Safari inspector and debug / write code live inside Phoenix. Perhaps even use something like [remotedebug-ios-webkit-adapter](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter) to integrate with other editors (e.g. Visual Studio Code) and debug your applications straight from your editor 😄.

I started hacking on Phoenix a bit but I'm very lost when it comes to Objective-C and after browsing API docs I was not any wiser.

I tried the following code in `PHContext.setupContext`:

```objc
JSStringRef jsName = JSStringCreateWithUTF8CString([@"Phoenix" UTF8String]);
JSGlobalContextSetName(self.context.JSGlobalContextRef, jsName);
JSStringRelease(jsName);
```

In hopes that it would magically enable remote debugging, to no avail (AFAICT).

I've also tried reading some of the code in [JavaScriptCore/inspector](https://github.com/WebKit/webkit/tree/master/Source/JavaScriptCore/inspector) and [JavaScriptCore/debugger](https://github.com/WebKit/webkit/tree/master/Source/JavaScriptCore/debugger) but that didn't really help me. I'm also unable to find anything similar online, so figuring this out by myself seems like a lost cause.

**Comment by kasper** [comment]
It should be possible and I was also looking into it, but I couldn’t find any good references on how to set it up. I think it would be really valuable to figure out.

**Comment by kasper** [comment]
Done! When you pass an error object to the log function, this is now the output:

```
2021-04-05 21:22:49.432407+0300 Phoenix[7077:180765] Error: Something happened here!
	 at boom@file:///Users/kasper/.config/phoenix/phoenix.debug.js:2:18
	 at crash@file:///Users/kasper/.config/phoenix/phoenix.debug.js:6:7
	 at global code@file:///Users/kasper/.config/phoenix/phoenix.debug.js:10:8
```
