### ISSUE TITLE
How to close a window?

### ISSUE THREAD

**Issue by gutenye** [kasper/phoenix#184]
I've checked the API, does not found a method that close a window.

**Comment by mafredri** [comment]
Seems you are right, maybe you're the first one to need this feature 😄. But it does seem like a feature that should be present in the API.

For now you could either rely on `win.app().terminate()`, or, if that's too heavy-handed:

```js
Task.run('/usr/bin/osascript', [
	'-e',
	`tell app "${win.app().name()}" to close front window`,
]);
```

**Comment by kasper** [comment]
I guess `Cmd + W` works for most. 😂 I’ll add it to the list.

**Comment by kasper** [comment]
Implemented in master.
