### ISSUE TITLE
Add support for strict keystrokes

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#185]
I have the following handlers set up:

```js
const left = Key.on ( 'left', ['ctrl', 'alt', 'cmd', 'shift'], () => {} );
const upLeft = Key.on ( 'left', ['ctrl', 'alt', 'cmd', 'shift', 'up'], () => {} );
```

It makes sense to me to bind a `upLeft` corner action to when both `up` and `left` are pressed. But right now it conflicts with the `left` action.

There should be an option for saying: "handle this keystrokes and nothing more, if another key is also pressed just do nothing".

What do you think?

**Comment by kasper** [comment]
I’m not sure whether the macOS hot key API supports this directly, but I’ll ponder around the idea.

**Comment by kasper** [comment]
You can only bind a single key with the available set of modifiers. You could create a chain of events to achieve this (or something similar) in your configuration.

**Comment by kasper** [comment]
See #197 for ideas.
