### ISSUE TITLE
`windowDidOpen` sometimes doesn't trigger when opening a new Terminal window

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#187]
How to reproduce:
- Open a new Terminal window via Right click on its icon -> New Window
- The `windowDidOpen` event doesn't trigger

It doesn't happen always, but I wouldn't say its random either, from a point on it stops working.

Quitting Terminal or reloading Phoenix don't fix it. 

The event gets triggered when opening windows from other apps I've tried.

- Version: 2.5.0
- macOS: 10.13 beta 3

**Comment by mafredri** [comment]
I can reproduce, although `windowDidOpen` is never triggered for me, I'm on macOS Sierra 10.12.6.

```typescript
Event.on('windowDidClose', (w: Window) => {
	log('windowDidClose', w.hash(), w.app().name(), w.title());
});
Event.on('windowDidOpen', (w: Window) => {
	log('windowDidOpen', w.hash(), w.app().name(), w.title());
});
Event.on('windowDidFocus', (w: Window) => {
	log('windowDidFocus', w.hash(), w.app().name(), w.title());
});
Event.on('appDidActivate', (a: App) => {
	log('appDidActivate', a.name(), a.hash());
});
Event.on('appDidLaunch', (a: App) => {
	log('appDidLaunch', a.name(), a.hash());
});
```

I tested with the above, and none are triggered while `Terminal` is active, I can open new windows, close windows, switch between windows, nothing. Both `appDidLaunch` and `appDidActivate` are triggered when I first open `Terminal` and `appDidActivate` whenever I focus it after another app has been focused.

**Comment by fabiospampinato** [comment]
I tried restarting the system and still the event doesn't work.

It certainly worked for me yesterday, then it just broke.

**Comment by kasper** [comment]
The Accessibility API has its loose ends. This can be very app specific. Some apps don’t support it properly and other times the requests can timeout. Phoenix itself doesn’t retry a failed request. I have to get back to this and see if there’s something we can do.

**Comment by kasper** [comment]
I’m not sure if we can do much to improve this. 😞

**Comment by lwouis** [comment]
I'm also experiencing this with `Terminal.app`
