### ISSUE TITLE
Add a `spacesDidChange` event

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#189]
There's already a `screensDidChange` event, for when "screens (i.e. displays) are added, removed, or dynamically reconfigured".

An analogous `spacesDidChange` for when spaces are "added, removed or dynamically reconfigured" would be nice.

I believe It's already possible to detect this stuff by fetching `Space.all ()` in short intervals and comparing the current spaces' hashes with those saved from the previous run, but it would be better to have something easier to use and more efficient.

I'd use this for my [space switcher](https://github.com/fabiospampinato/phoenix) (bottom of the page).

**Comment by kasper** [comment]
Apple doesn’t have this event in the API. We could add a listener to the list, but then again, you can also do it in your configuration.

**Comment by fabiospampinato** [comment]
> Apple doesn’t have this event in the API

That's unfortunate, thanks for the reply.
