### ISSUE TITLE
Add a `spaceWillChange` event

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#190]
There's already a `spaceDidChange` event, a complementary `spaceWillChange` event I think will make a nice addition to it. It would be useful because we can't get windows that are only in other spaces, this event would provide a last chance to perform an action on those windows before they cannot be accessed anymore.

My use case: I've made a [space switcher](https://github.com/fabiospampinato/phoenix) (bottom of the page) which guesses spaces' names based on their windows' titles. For that it mainly uses Visual Studio Code's title, but since there's no direct event for when it changes (ie. after opening another project) I try to fetch it after `windowDidOpen`, which for some reasons gets triggered, but the title won't be updated immediately, so I schedule the same "fetch title" work at intervals of 500ms, but this won't work if the title gets updated before a "fetch title" run and right after that the user changes workspace. With a `spaceWillChange` event I could fetch the title one more time, and in this particular example it'll work.

**Comment by kasper** [comment]
Unfortunately Apple doesn’t have this event in the API.
