### ISSUE TITLE
An handler for a different shortcut can run in place of the appropriate one

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#191]
[This](https://github.com/fabiospampinato/phoenix) is my configuration, among many others I have an handler set up for <kbd>ctrl + alt + cmd + D</kbd> and another one for <kbd>ctrl + alt + cmd + I</kbd>.

If I trigger their respective shortcut "normally" both of them work as expectected, but if I:
- press <kbd>ctrl + alt + cmd</kbd>
- press <kbd>D</kbd>
- release <kbd>D</kbd>
- keep the others pressed

The handler for <kbd>ctrl + alt + cmd + I</kbd> gets triggered instead of the one for <kbd>ctrl + alt + cmd + D</kbd>.

Any Idea why this might happen?

- Version: 2.5.0
- macOS: 10.13 Beta 3

**Comment by kasper** [comment]
So with only `ctrl + alt + cmd` the other handler gets fired?

**Comment by fabiospampinato** [comment]
If I only press <kbd>ctrl + alt + cmd</kbd > nothing happens, but if I also press <kbd>D</kbd> without releasing the other three it behaves as if I pressed <kbd>I</kbd>.

**Comment by kasper** [comment]
Are you dynamically changing the key handlers or could it potentially have the wrong callback in some case?

**Comment by fabiospampinato** [comment]
My bad, the handler for <kbd>ctrl + alt + cmd  + D</kbd> triggers <kbd>alt + cmd + I</kbd>, but since I was still pressing <kbd>shift</kbd> it triggered the other handler.

Sorry.
