### ISSUE TITLE
Can't find an hidden floating window

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#193]
I use [this](https://github.com/fabiospampinato/phoenix/blob/master/helpers/find_window.js#L4) function to find a window by app name.

But it doesn't work in this particular case:
- Open [Noty](https://github.com/fabiospampinato/noty), a sticky notes app I made with Electron
- Set `Window -> Float on Top`
- Hide it: <kbd>Cmd+H</kbd>
- Calling `findWindow ( Space.active ().windows (), 'Noty' )` returns `undefined`

It otherwise works if `Float on Top` is not set, or if instead of being hidden it's visible or minimized.

Strangely enough doing the same but with the native `Stickies` app works as expected.

I guess maybe they do something different from each other for making the windows float on top, Electron provides [this](https://electron.atom.io/docs/api/browser-window/#winsetalwaysontopflag-level-relativelevel) function for doing it, and Noty calls it like `win.setAlwaysOnTop ( true )`, may it be the cause of the issue?

- Version: 2.5.0
- macOS: 10.13 Beta

**Comment by kasper** [comment]
Yes, if the app does some custom subclassing of the window hierarchy it needs to also implement the Accessibility APIs. Unfortunately some apps don’t really support this properly.

**Comment by fabiospampinato** [comment]
Thanks for the explanation.
