### ISSUE TITLE
Phoenix gets deleted from start-up items list

### ISSUE THREAD

**Issue by 3rd3** [kasper/phoenix#194]
It seems Phoenix (at least sometimes) gets deleted from the start-up items list. One can see that it is in the list, but after a restart it is gone.

- Version: Current
- macOS: Sierra clean install (but I also had this under El Capitan)

**Comment by kasper** [comment]
Intriguing, I haven’t noticed this. Could it potentially be some other app trying to edit the launch list?

**Comment by khalidchawtany** [comment]
I have this issue too. It happens rarely. When you press the shortcut you find out it is not running.

**Comment by jasonm23** [comment]
I get this all the time after reboot :(

**Comment by kasper** [comment]
Hmm… Very curious. 😿

**Comment by josser** [comment]
Have same issue for a long time. take a look:
![login_item](https://user-images.githubusercontent.com/103639/31715324-0c0d21e4-b40c-11e7-9518-025d57aa85c1.gif)

**Comment by kasper** [comment]
Does it also happen if you set it from the configuration?

**Comment by josser** [comment]
@kasper Didn't know it's possible! 
Just set it via config and now it's working.

**Comment by kasper** [comment]
Ok, well that reveals the problem then! Will investigate the menu setting. 😄

**Comment by 3rd3** [comment]
Thanks. Here is the relevant part of the docs:

https://github.com/kasper/phoenix/blob/master/docs/API.md#3-preferences

**Comment by macgyver** [comment]
FWIW, the setting also gets obliterated if you hit "Reload" from the menu extra

**Comment by kasper** [comment]
Will fix this one for the next release.

**Comment by kasper** [comment]
Fixed in master. Thanks for the report!

**Comment by jasonm23** [comment]
Using 4.0.0 and "Open at Login" on the menu is not persisting.
