### ISSUE TITLE
Add support for Open Scripting Architecture

### ISSUE THREAD

**Issue by velocityzen** [kasper/phoenix#195]
Hello,

Apple supports Javascript in [OSA](https://developer.apple.com/library/content/documentation/AppleScript/Conceptual/AppleScriptX/Concepts/osa.html) 
That would open a whole new world for Phoenix.

**Comment by kasper** [comment]
You can already run OSA by running it as an external task. Check the Task API, maybe that could help you achieve what you are aiming to do.

**Comment by velocityzen** [comment]
Hmm, I meant to expose OSA APIs to phoenix.js. It'll make possible something like this right in the config:

```js
const itunes = App.get ( 'iTunes' );
const selection = itunes.selection();
itunes.play(selection[0]);
```

**Comment by kasper** [comment]
Hi! Thanks for the feedback, but this is not in the context of this app. Use macOS AppleScript/JavaScript automation and run those as tasks from Phoenix.
