### ISSUE TITLE
Request: Support for binding key sequences/chords

### ISSUE THREAD

**Issue by berwyn** [kasper/phoenix#197]
- Version: 2.5.0
- macOS: 10.13.2

First, thanks for this project, it's really awesome!

Would it be possible to add support for key sequences/chords? For example, it'd be nice if I could press `cmd`+`ctrl`+`2` and resize/reposition a window to be 1/3 the screen, centred, and then separately have `cmd`+`ctrl`+`2`, `2` (holding `cmd`+`ctrl`, press `2` twice) resize/reposition my window to take 2/3 the screen on the right. I'm not sure how this would fit with the current `Key` API, but perhaps something like
```js
Key.on('2', ['cmd', 'ctrl'] , () => {})
Key.on(['2', '2'], ['cmd', 'ctrl'], () => {})
```
so as to have minimal impact on the existing API and existing scripts?

**Comment by fabiospampinato** [comment]
I think you can do this today:

1. Just listen for `cmd+ctrl+2`
2. The first time it gets triggered you resize the window to 1/3 of the screen
3. If it gets triggered again within 250ms or something like that you resize the window to 2/3 of the screen
4. If it doesn't get triggered within 250ms you'll treat the next event as if it is the first one

**Comment by berwyn** [comment]
Yeah, that's what I've got setup now essentially, but it would be nice if there was a more convenient way to setup/maintain these sorts of chords, especially if someone wanted to do multi-key chords, `ctrl`+`cmd`+`left` followed by `ctrl`+`cmd`+`up` for example

**Comment by jasonm23** [comment]
I think it's best to wrap it up in a convenience function(s).

It would be better if the API didn't become over complicated with things like this.  It would also serve as a nice example for others.

FYI there are a few different modal implementations in the example configs. (See the wiki)

**Comment by kasper** [comment]
I agree with @jasonm23, we definitely want to keep the API as simple as possible. This could however potentially be added as a convenience helper in the JS library. I still think there might be a place for supporting community libraries in some way.

**Comment by kasper** [comment]
I think people would tend to have very different needs for how the sequences would fire, so I’m not sure whether there is any good global solution without overcomplicating the API.

**Comment by mafredri** [comment]
I realized this was just closed, but I had an idea that would be supportive of these kinds of use cases, and others, while (supposedly) keeping the API simple.

**Idea**: A way to save/restore/disable the current key handlers on a global level, create temporary handlers (and to create a catch-all handler). For example, say you hit `Cmd + Ctrl + 2`, this handler could then disable the regular handlers and create a new one for `2` (and maybe a catch-all). Pressing 2 would trigger the chord and pressing anything else would abort the chord (catch-all). In both cases the pre-chord handlers could be easily restored / re-enabled via some mechanism.

Another use case for this would be input/search boxes where upon opening the search box, you want (temporary) handlers for keys as input (catch-all would be useful here), and perhaps a custom one to abort (esc/enter). Afterwards you'd restore the regular handlers.

Thoughts? I could move this to a separate issue if you'd prefer that @kasper. I have [code that does something similar](https://github.com/mafredri/phoenix-config/blob/d7070045a6d5ba448461fa145e2e7425e4038bc9/src/scan.ts) but requires [custom management of key handlers](https://github.com/mafredri/phoenix-config/blob/d7070045a6d5ba448461fa145e2e7425e4038bc9/src/key.ts) and could be simplified quite a bit by the suggestion above.

**Comment by kasper** [comment]
@mafredri I’m implementing input support to the modal. I don’t really see any other benefit of catching all keys. Feel free to correct if I’m wrong. 😄  For very custom behaviours, I would suggest anyway managing the handlers yourself.

**Comment by kasper** [comment]
@mafredri There’s no native way of doing chording with the hot key API. It’s single keys with modifiers. So this would have to be built on top of that anyway.

**Comment by mafredri** [comment]
All right, I thought that might be the case, sounds like a lot of work for little gain 😅.
