### ISSUE TITLE
Move window left/right one monitor

### ISSUE THREAD

**Issue by mjedmonds** [kasper/phoenix#207]
- Version: 2.6.1
- macOS: 10.13.4

I can't seem to find any documentation/example of moving a window left/right one monitor.

Is this functionality possible? I don't see anything in the Window/Screen API that indicates this is possible (perhaps through `all()`, but that wouldn't indicate which is left/right).

Excuse this if this is a basic question, but thought it would be helpful for others even if it is!

Thanks.

**Comment by mafredri** [comment]
I use a method that maintains the window size across different sized screens as well. My config is written in TypeScript, but feel free to adapt:

https://github.com/mafredri/phoenix-config/blob/5f4d7083d3e6dbc8956e63c2e010a05333e3af24/src/phoenix.ts#L29-L47

**Comment by j6k4m8** [comment]
I get a list of `Screen`s, and then sort by their frame-origins:

```js
Screens.all().sort(s => s.flippedVisibleFrame().x)
```

More context [in my config](https://github.com/j6k4m8/tao-of-spaces/blob/master/modules/custom-layouts.js#L5).

**Comment by kasper** [comment]
Don’t hesitate to ask more if this didn’t help you out.
