### ISSUE TITLE
Modal overlay won't show

### ISSUE THREAD

**Issue by yqrashawn** [kasper/phoenix#208]
- Version: 2.6.1 (65)
- macOS: 10.12.6 (16G1036)

The modal overlay won't show, other functions works fine. No log in Console.app, no exception notification.

Works on my 10.11.5 (15F34) machine fine.

**Comment by mafredri** [comment]
Are you storing the modal in a variable? There's a good chance it's being garbage collected before it has a chance to show otherwise. Perhaps JavaScriptCore on 10.12 is more aggressive than on 10.11.

**Comment by yqrashawn** [comment]
@mafredri Just tried. Won't work either.

```javascript
g = this;
const tmodal = new Modal();
g.tmodal = tmodal;
tmodal.duration = 0;
```
Full code is here.
https://gist.github.com/yqrashawn/f9d2e6beea93002ba15b89b6696036e8

**Comment by mafredri** [comment]
IIRC modals aren't re-usable, after you've closed it you should `tmodal = new Modal()`.

**Comment by yqrashawn** [comment]
@mafredri The problem is that it never show. If the modal is destroyed after the `close()` call, it will at least show before that call.

**Comment by kasper** [comment]
Closing the window will eventually also destroy the window. The window will not show until `Modal#show` is called. Not sure why it’s working differently for you on different OS versions, but I presume there is something wrong with your configuration. Will need to investigate that further once I have time.

**Comment by yqrashawn** [comment]
@kasper found it, it's the origin, the two machine have different size monitor. 😂

**Comment by kasper** [comment]
@yqrashawn Haha, glad you found the issue!
