### ISSUE TITLE
Add feature to work with the clipboard

### ISSUE THREAD

**Issue by AlexGustafsson** [kasper/phoenix#213]
- Version: 2.6.1 (65)
- macOS: 10.13.4

I think that a feature to work with the clipboard would be a much appreciated addition to the already existing functionalities - this being a automation-centered application and all. The support would be to both read and write from / to the clipboard.

The usual javascript alternatives include calling `pbcopy` or `pbpaste` through a child process (Node) or relying on the not-always-supported feature `navigator.readText()` (browser). Since JavaScriptCore does not support either child processes or the navigator, there aren't really any options left.

I think that a proper solution would be to write a Obj-C backend  function that is polyfilled towards JavaScript - a function that either exported as the `navigator.readText()` or a separate API like those for Windows, Screens, Modals etc.

**Comment by mafredri** [comment]
Have you tried using the [`Task`](https://github.com/kasper/phoenix/blob/master/docs/API.md#15-task)-API to interact with `pbcopy` / `pbpaste`?

I'm curious what your use-case is, how would clipboard control improve your Phoenix experience? Phoenix is mostly about window control, not automation per-se.

**Comment by AlexGustafsson** [comment]
Task did fit the job, which I guess makes the time required to implement an alternative pointless at the time.

Thank you for your help.

Here's a snippet for potential readers in the future.

```JavaScript
// Get content in clipboard
const task = Task.run('/usr/bin/env', ['bash', '-c', 'pbpaste'], handler => {
  const clipboard = handler.output;
});

// Set content in clipboard (text only)
const content = 'Hello World!';
const task = Task.run('/usr/bin/env' ['bash', '-c', `echo -n "${content}" | pbcopy`], handler => {
  // Clipboard is set to content
});
```

**Comment by jasonm23** [comment]
@AlexGustafsson - if you'd like a fully programmable clipboard checkout CutBox ( https://cutbox.github.io / https://github.com/cutbox/CutBox/wiki )

**Comment by AlexGustafsson** [comment]
@jasonm23 Thanks for the tip!
