### ISSUE TITLE
Space#windows return empty array if the space inactive

### ISSUE THREAD

**Issue by dwiyanr** [kasper/phoenix#214]
- Version: 2.6.1
- macOS: 10.12.6

I have several spaces. If i try to get windows from the active space it works properly, but if i try to get windows from the prev/next space it always return empty array.
```
> Space.active().windows()
< [PHWindow] (1)
> Space.active().next().windows()
< [] (0)
> Space.active().previous().windows()
< [] (0)
```

i try to access the windows from `Space.all` instead of `Space.active` but its still happening.
For example my active Space is the third one
```
> Space.all()
< [PHSpace, PHSpace, PHSpace, PHSpace, PHSpace] (5)
> Space.all()[0].windows()
< [] (0)
> Space.all()[1].windows()
< [] (0)
> Space.all()[2].windows()
< [PHWindow] (1)
> Space.all()[3].windows()
< [] (0)
> Space.all()[4].windows()
< [] (0)
```

i try using the optionals param of `Space#windows` too, but got no luck with both `true` and `false` value for `visible`.

**Comment by joeshaw** [comment]
Related to #131
