### ISSUE TITLE
Feature: API to manipulate titlebars and remove windows shadows

### ISSUE THREAD

**Issue by ngryman** [kasper/phoenix#219]
Hey,

I've built a grid system on top of Phoenix which is 👌 It's working very well but I'd like to go wilder.

I've got pre-defined apps arrangements which form a "meta-app". For example my "Organization meta-app" consists of Todoist, Calendar and Bear because I use those application in tandem. I would love that they visually appear to be more consistent. To do that I was thinking about being able to manipulate or remove their titlebar and shadows.

Do you think you could expose such an API?

Here is a resource that I found useful (being a noob in Mac OS development): http://robin.github.io/cocoa/mac/2016/03/28/title-bar-and-toolbar-showcase/

**Comment by kasper** [comment]
Hey! Cool idea, but this is up to the individual apps to decide in their layout. You cannot control it outside of the app.

**Comment by ngryman** [comment]
Hey @kasper, thanks for the quick answer. Out of curiosity, there is no way of doing so, even with the Accessibility API?

**Comment by kasper** [comment]
Only if the app provides such a feature. Such as having a toggle or menu bar item to switch between different title bar styles.

**Comment by ngryman** [comment]
Oh that's a bummer. Well thanks for the explanation!

**Comment by ngryman** [comment]
Unrelated to Phoenix, is there a way to do what I want somehow? Is it possible for me to create an app that starts and "owns" those apps somehow (same process) that would give me the ability to mask their title bars?

**Comment by kasper** [comment]
That would mean either hacking the binaries of the operating system or the apps. Then there is code signing that has been designed to prevent this. Easiest bet is to ask the developers to implement this.
