### ISSUE TITLE
Get minimum window size

### ISSUE THREAD

**Issue by izanagi1995** [kasper/phoenix#223]
Some apps can have a minimum size like Franz or Spotify. The API should reflect this, allowing to resize the window with this information as a limit.

**Comment by kasper** [comment]
It’s anyway a request based API, if you try to resize a window below the minimum size, it’s up to the app’s window constraints to decide what to do. I’m not entirely sure if you can even get the minimum size from the API…

**Comment by mafredri** [comment]
Since the setSize/setFrame methods can fail, you could try storing the size when they fail.

```js
if (!win.setSize({width: 200, height: 200})) {
  minSize[win.hash()] = win.size();
}
```

You could even store these via Storage.set/get.

**Comment by kasper** [comment]
This doesn’t seem to be possible to achieve.
