### ISSUE TITLE
Does not consistently reposition Google Chrome windows?

### ISSUE THREAD

**Issue by j6k4m8** [kasper/phoenix#224]
- Version: 2.6.2
- macOS: 10.13.6

With latest Google Chrome (69 - nice), it appears that while _some_ repositioning commands work, others — especially when run in quick combination with other commands — fail without an error logged.

Curious if others have experienced this? Perhaps a fluke, but my profile [available here](https://github.com/j6k4m8/tao-of-spaces) has worked for many version of Chrome before this one.

**Comment by j6k4m8** [comment]
The issue logged to the console is:

```
Error: Could not set accessibility attribute “AXSize” with value “<AXValue 0x60000005e960> {value = w:1920.000000 h:1080.000000 type = kAXValueCGSizeType}” for element <AXUIElement 0x60400024e6a0> {pid=11088}. (-25200)
```

**Comment by joeshaw** [comment]
I've started seeing this as well on macOS 10.14 and Chrome 69.

In my `phoenix.js` I set certain fixed screen layouts when I connect or detach an external monitor, so for me the repositioning is triggered by a `screensDidChange` event.  If I reload from the Phoenix menu item, the Chrome window is repositioned.

I see the same errors in my logs:

```
Error: Could not get process identifier for accessibility element (null). (-25201)
Error: Could not set accessibility attribute “AXPosition” with value “<AXValue 0x600002263630> {value = x:931.000000 y:0.000000 type = kAXValueCGPointType}” for element (null). (-25201)
Error: Could not set accessibility attribute “AXSize” with value “<AXValue 0x600002263630> {value = w:1629.000000 h:1417.000000 type = kAXValueCGSizeType}” for element (null). (-25201)
```

**Comment by kasper** [comment]
I would assume they broke something in their accessibility support. Still happening with newer Chrome builds?

**Comment by joeshaw** [comment]
Yes, I removed my workaround (to reposition it after 5s) and it seems to be working consistently from `screensDidChange` now.

**Comment by kasper** [comment]
@joeshaw To just clarify, newer Chrome builds work?

**Comment by joeshaw** [comment]
@kasper Yes, with Chrome 71 it appears to work for me 100% of the time now.

**Comment by kasper** [comment]
@joeshaw Great! Thanks for the information!

**Comment by joeshaw** [comment]
Unfortunately this seems to have cropped back up. 🙁 Still on Chrome 71, so I can't explain why.

**Comment by kasper** [comment]
I think this is mostly a bug in Chrome so it doesn’t support accessibility commands properly. If you find anything more, let me know.
