### ISSUE TITLE
Any way to set env PATH

### ISSUE THREAD

**Issue by alswl** [kasper/phoenix#225]
- Version: 2.6.2
- macOS: 10.13.6 (17G65)

Phoenix is auto launched by macOS, when I use `App.launch` open a Application, the env `PATH` of the application is default of system, not include PATH configuration in `.bashrc / .profile`. Is there any solution to config env PATH in Phoenix configuration?

**Comment by kasper** [comment]
Could you explain the use case for this or what app would benefit from this? Bash configurations are really only meant to be read by a bash instance.

**Comment by alswl** [comment]
@kasper When launch a application by Phoenix, for example MacVim. It's PATH is read from Phoenix's PATH, not from ~/.bashrc or ~/.zshrc.

If Phoenix launch by System login, the PATH is default pure setting.
If I launch Phoenix from Launchpad, the Phoenix read PATH from macOS system PATH.

**Comment by jasonm23** [comment]
May I ask. If you launch MacVim via Finder, Spotlight or Alfred, which path is loaded?

**Comment by jasonm23** [comment]
Could you also clarify, is it `.bashrc` or `.zshrc` you want to use?

There are different issues with both.

---

Maybe I'm guessing, but do you usually launch MacVim from a terminal session?

**Comment by jasonm23** [comment]
Thanks that's really useful info.

> I use `sudo launchctl config user path $PATH` to config macOS system PATH

This is probably the vital piece.

Usually this will be run in bashrc, so I'll assume it's being done like that.

Help me clear up a few remaining questions.

If you run MacVim from Alfred or finder do you always need to have this launchctl sequence run first (I assume yes, so lets confirm or dispose of that assumption.)

If that's the case, we need to ensure it's run before Phoenix.

**Comment by jasonm23** [comment]
If you reached the launchctl config setting the way I did you may have noticed advice to restart Dock (apps started from Dock use it's environment FYI)

We could simply do a little osascript to restart Phoenix too.

Maybe adding this to bashrc...

```
osascript -e '
tell application "Phoenix"
    quit
end tell

delay 1 -- Wait for Phoenix to close (this maybe redundant)

tell application "Phoenix" to activate
'

```

**Comment by alswl** [comment]
Now my solution is: I disabled Phoenix / Alfred run automatic in login item. After macOS system start, I will launch Phoenix / Alfred from Launchpad, so that Phoenix read right PATH configuration.

**Comment by jasonm23** [comment]
Seems like the simplest thing to do

:+1:

**Comment by jasonm23** [comment]
Suggest we close this
