### ISSUE TITLE
Use custom images for modal icons

### ISSUE THREAD

**Issue by pierre-borckmans** [kasper/phoenix#226]
Hi there!
I've been using your tool for a while now and I love it.

Is there a way to use an image from the file system as the icon of modals?
It looks to me like the only way to build an `NSImage` from the javascript API is through `App.icon()`.
I tried to look for it in the code, and also to debug to see what was obtained with `App.icon()` but without success.

If it's not possible yet, any pointers as to how to implement this?

Cheers

**Comment by kasper** [comment]
Hi, thanks! Glad you like it. 🙂 It’s not currently possible but the support could be added. Either file system or maybe Base64 encoded images as data strings.

**Comment by pierre-borckmans** [comment]
That would be great indeed. Any idea how we would go about it?

**Comment by kasper** [comment]
We would create a new Image class that would construct NSImages (from the file system or data strings) that you could then pass to the modal. Something along those lines.

**Comment by pierre-borckmans** [comment]
See #227 for a first attempt at this.

**Comment by kasper** [comment]
Implemented in build 77.
