### ISSUE TITLE
Option via the api to set position / gravity, ie. Which edge / centre etc. for alerts to use. 

### ISSUE THREAD

**Issue by nylen** [kasper/phoenix#23]
As discussed in #22, I need this because notifications appear off the right side of my screen by default.

Are you planning to implement it, or shall I?  I can give it a shot, but since I'm new to the project and to Objective-C development, a broad outline of what needs to change would be really helpful.

**Comment by nylen** [comment]
@jasonm23 ping

**Comment by jasonm23** [comment]
Hi @nylen I'll be happy to give you a few pointers.  I'm tied up most of today though.

In a nutshell this seems to be something that would be best set as a global preference.

We can just use the apple defaults engine for this, a good place to see it in action is on the MPlayerX project.

Also check the apple developer docs.

You'll probably be aware of its use is the terminal command;

    defaults write ...

As soon as I have time I'll show you some more specific examples on reading them in ObjC / Cocoa.

**Comment by jasonm23** [comment]
Looks like I didn't get any time!  Did you manage to figure it out?

**Comment by nylen** [comment]
Not yet, I'm still using phoenix and would still like to try though.  Thanks for the pointers, I think what you wrote will be enough to get me started.  Probably will be around the end of April.

**Comment by jasonm23** [comment]
Note, I've pushed a quick hacky fix for this so that alerts just come to the main screen at top left, and below.

**Comment by kasper** [comment]
Alerts are indeed a bit wonky on Yosemite. I’ll see how to improve this for the future.

**Comment by kasper** [comment]
This is resolved in the upcoming version. I’ve deprecated the idea of “Alerts” in Phoenix [2.0](https://github.com/kasper/phoenix/tree/2.0/). Instead, you can now use “Modals” to display messages as modal windows. Modals can be positioned anywhere on your screens. You can also use the Notification Center to display notifications from Phoenix. See the [API](https://github.com/kasper/phoenix/blob/2.0/API.md/) for reference.

```js
var modal = new Modal();
modal.origin = { x: 0, y: 0 };
modal.duration = 2.0;
modal.message = 'Message';
modal.show();
```
