### ISSUE TITLE
Integrity cannot be verified

### ISSUE THREAD

**Issue by tborychowski** [kasper/phoenix#241]
- Version: 2.6.2
- macOS: 10.15 Beta (19A487m) (Catalina)

<img width="532" alt="Screenshot 2019-06-25 at 09 57 17" src="https://user-images.githubusercontent.com/392513/60084560-aa6c6b80-972f-11e9-8916-0bde0329b89b.png">

I know macos 10.15 is in beta :-)

---
**Update:** I built the app from source and it works fine!

**Comment by kasper** [comment]
@tborychowski I think the apps in 10.15 have to be audited for signing. Maybe this is related. I’ll sort it out before that. 😄

**Comment by jasonm23** [comment]
So @kasper do you have to send a binary to Apple for audit?

**Comment by kasper** [comment]
@jasonm23 Yep, although as far as I know it’s some automated way of just verifying nothing malicious is going on. (Hopefully it shouldn’t/doesn’t check any private APIs or anything.)

**Comment by Viveur** [comment]
Also experiencing this on boot/login with 10.13

**Comment by kasper** [comment]
Sorry for the delay on this, I’ve been really busy at work. Will sort it out.

**Comment by Viveur** [comment]
Hey, no pressure, but figured would post a little reminder about this as been a while.  Be really nice to fix for bootup. Thanks

**Comment by kasper** [comment]
@Viveur Understandable. Just upgraded to Catalina and it’s on my todo. Thanks for the patience. :)

**Comment by kasper** [comment]
This has now been fixed in 2.6.3. What a tricky operation. Thanks for all the patience!
