### ISSUE TITLE
Could Modal support colored text?

### ISSUE THREAD

**Issue by alswl** [kasper/phoenix#242]
- Version 2.6.2 (71)
- macOS: 10.14.5 (18F132)

The modal text is grey now. Could Modal support colored text?

expected:

```
Modal.build({
...
    text: 'Some <span color="red" size="10px">text</span> here.'
...
```

**Comment by kasper** [comment]
Related to #158.

**Comment by kasper** [comment]
While not exactly what is requested here (partially modifying the text colour), the whole text colour is now modifiable with `setTextColour(...)` in modals. See more in the documentation: https://kasper.github.io/phoenix/api/modal.
