### ISSUE TITLE
Can I bind to `fn` key combination?

### ISSUE THREAD

**Issue by iexcept** [kasper/phoenix#244]
Am I able to launch Chrome, for example, holding `Fn+C`?

- Version: <latest>
- macOS: 10.14.6

**Comment by Taikuh** [comment]
`fn` isn't listed in the API doc as a valid modifier. However, if you are using the internal keyboard of a MacBook, you can look into Karabiner Elements to re-bind `fn` to a less-used combination of modifiers such as `Ctrl+Opt+Cmd+Shift`, popularly referred to as `Hyper`. Then, just use that modifier combination in your Phoenix config.

**Comment by kasper** [comment]
@Taikuh Thanks for taking the time to respond!
