### ISSUE TITLE
Warning: Key  not supported after update to 10.15.2

### ISSUE THREAD

**Issue by garciamax** [kasper/phoenix#246]
- Version: 2.6.2
- macOS: 10.15.2

After an upgrade to 10.15.2 there is a message in log:

Phoenix: Warning: Key “p” not supported.
Phoenix: Warning: Key “`” not supported.
Phoenix: Warning: Key “d” not supported.
Phoenix: Warning: Key “f” not supported.
Phoenix: Warning: Key “q” not supported.
Phoenix: Warning: Key “w” not supported.

This happens for all my `Key.on` bindings with letters they stopped working, arrows and "tab" bindings work just fine.

**Comment by kasper** [comment]
@garciamax Which version did you upgrade from?

**Comment by garciamax** [comment]
> @garciamax Which version did you upgrade from?

10.15.1

**Comment by kasper** [comment]
@garciamax Interesting that it happened on a minor version upgrade. I have not yet upgraded to Catalina, so I have not yet encountered what is not working properly there. Will definitely fix all issues before the end of the year. What keyboard layout are you using?

**Comment by garciamax** [comment]
@kasper Yes it is totally unexpected, so as why arrows, numbers or tab works. I am running "Karabin-Elements" too. My keyboard layout is ANSI US.

**Comment by varp** [comment]
@garciamax @kasper  I  also have , but all work as expected

**Comment by kasper** [comment]
I just upgraded to Catalina and keys seem to work. So might be some keyboard layout issue.

**Comment by garciamax** [comment]
Yes, I've upgraded my other macbook and it all works fine. So as on the "problem" one with the build in keyboard. So the problem only with the external keyboard. FYI it is [Matias laptop pro](https://matias.ca/laptoppro/mac/). I am closing the issue. Thank you.
