### ISSUE TITLE
App.get('Finder').windows() does not returns all Finder windows from other spaces. 

### ISSUE THREAD

**Issue by varp** [kasper/phoenix#247]
- Version: 2.6.2
- macOS: 10.15.2

1. It only returns Desktop window (which one with an empty title, I suppose) and doesn't return opened windows from other Spaces.
2. And there is another question: is there way to differentiate Finder Desktop window from opened folder browser windows?

**Comment by kasper** [comment]
Hello! For 1., see #131. It’s unfortunately a limitation of the APIs provided by Apple. For 2., try `Window#title()`.

**Comment by varp** [comment]
@kasper SFLR , thanks for replies, closing the issue.
