### ISSUE TITLE
How to resize window to 50%

### ISSUE THREAD

**Issue by olimart** [kasper/phoenix#253]
Was wondering if you could provide an example on how to move the current window (top left) & resize it to half width of the window & 100% vertically?

Great application by the way. Thanks.

- Version: 2.6.3
- macOS: 10.15.2

**Comment by kasper** [comment]
@olimart Hi! Thanks for the kind words. 😄 Of course! You could do something like this. Hope it helps.

```js
Key.on('e', ['control', 'shift'], () => {
  const window = Window.focused();
  if (window) {
    window.setFrame({
      x: 0,
      y: 0,
      width: window.size().width / 2,
      height: window.size().height,
    });
  }
});
```

**Comment by olimart** [comment]
Thank you very much.
