### ISSUE TITLE
Is there way to open/activate closed main window of an app?

### ISSUE THREAD

**Issue by varp** [kasper/phoenix#255]
- Version: 2.6.3
- macOS: 10.15.3
Okay.  There is the situation. I have an app Dash. When I closing the main window of the app by pressing CMD+W, I cannot open/activate/show it again. The console shows the following [error](https://yadi.sk/i/VHLaMahUDigWLg). Is that bug or desired behaivor of the Kasper?
The code that I'm using to activate / show the main window - [switchToApp](https://github.com/varp/phoenix/blob/fd873068cee8720b8eb915ba58da79e95cbe645d/helpers/appManager.js#L61)

**Comment by varp** [comment]
I'm also use Alfred on my Mac, and when activating the app by Alfred the app with closed main window opens and activates. That's weird... Can the both apps use different APIs?

**Comment by kasper** [comment]
@varp Hello! When you close the window, its instance is released and therefore the window does not exist anymore. You have to create a new window for the app by opening it.

**Comment by varp** [comment]
Thanks. now I use AppleScript to open an application's default window. 
The first, I just try to reopen app - [reopenApp](https://github.com/varp/phoenix/blob/c92f4b11b89790247acb97c072a84b91f94e3e19/helpers/appManager.js#L95).  In case of the Dash app and also many more it just did the trick.
The second, for other case and the specific logic - [AppleScript](https://github.com/varp/phoenix/blob/c92f4b11b89790247acb97c072a84b91f94e3e19/helpers/appSwitchers/finder.js#L85). 
I am really still confusing.... Thy the underlying API that you use in Kasper dosen't offer API for opening a new window....

**Comment by kasper** [comment]
@varp Hi! You can open up a new window by doing the following:

```js
App.launch('Mail', { focus: true });
```

**Comment by varp** [comment]
This not obvious. Anyway, thank you so much. Closing the issue.
And, AppleScript has the bonus in it - it returns all Finder windows from all Spaces - and it was important for my case.

**Comment by kasper** [comment]
@varp Thanks for the feedback, I’ll see if I can improve this!
