### ISSUE TITLE
Odd error in logs (RecordIt)

### ISSUE THREAD

**Issue by malcolmboyd** [kasper/phoenix#257]
- Version: 2.6.3
- macOS: 10.13.4

Hello, I seem to have an odd error in my logs. It looks as though Phoenix is attempting to open RecordIt. I have installed Phoenix via the homebrew cask and was wondering what this error was? 

I should note that I am unaware of anything in my config that would be triggering this. 

```2020-03-02 20:41:02.088422-0600 0x31bd     Default     0x0                  882    Phoenix: Error: Could not copy resolved URL for session login item <SFLItem: 0x600000221e00> : RecordIt - file:///private/var/folders/k6/p04hm5157_bbwmxdpmk0tt7r0000gm/T/AppTranslocation/2A6572FE-FFD3-4592-8825-64E01137F1D7/d/RecordIt.app/. (Error Domain=NSCocoaErrorDomain Code=4 "The file doesn’t exist.")```

**Comment by kasper** [comment]
@malcolmboyd Hi! That is actually caused by you having something corrupted in your “launch at login” items System Preferences. Delete “RecordIt” from the list and everything should be back to normal. Hope that helps!

**Comment by malcolmboyd-wk** [comment]
That did it thanks!

**Comment by seren** [comment]
Thanks! These errors have been a minor annoyance and I didn't realize the cause.

**Comment by malcolmboyd** [comment]
That fixed it thank you!

**Comment by kasper** [comment]
Great!
