### ISSUE TITLE
Feature Request: Automatic reload

### ISSUE THREAD

**Issue by alexmarmon** [kasper/phoenix#258]
When switching from a monitor setup at home to one on the go I have to reload for the windows to size properly. Not a big deal but it would be cool if it recognized the change and switched automatically.

**Comment by kasper** [comment]
Hi @alexmarmon! Would listening to the `screensDidChange` event and then resizing work for you in this particular case? https://github.com/kasper/phoenix/blob/2.6.3/docs/API.md#2-events

**Comment by alexmarmon** [comment]
Sorry @kasper, I didn't see your original reply. That works perfect, thank you!

**Comment by kasper** [comment]
@alexmarmon No worries, perfect!
