### ISSUE TITLE
Phoenix needs a new maintainer...

### ISSUE THREAD

**Issue by jasonm23** [kasper/phoenix#26]
I have migrated my workflow to Hammerspoon, as it can do everything Phoenix can, plus a lot more.

If you would like to take over the maintenance of Phoenix, please comment here.

**Comment by kasper** [comment]
@jasonm23 I’d be happy to take over maintaining Phoenix just to keep a JavaScript window management option available and working! For the future, I would like too see Phoenix converted to use Swift.

**Comment by kasper** [comment]
@jasonm23 Feel free to transfer the repository over, if you’re okay with it.

**Comment by jasonm23** [comment]
Hi @kasper I've given you commit access to the project, and updated the README to name you as the new maintainer.

I'll be able to contribute still, just not as the main guy.

**Comment by jasonm23** [comment]
I've set up an ownership transfer.

**Comment by jasonm23** [comment]
I'd like to remain as a contributor after transfer.

**Comment by kasper** [comment]
@jasonm23 Of course, thanks! To make things clear, any major changes by collaborators should go through a PR — if you don’t mind. I will probably freshen things up quite a bit and clean up the repository. :)

**Comment by jasonm23** [comment]
Sure thing, thanks for stepping up.
