### ISSUE TITLE
Troubleshooting Task.run('/bin/sh', ['-c', 'emacsclient -nc -a ""'])

### ISSUE THREAD

**Issue by idmyn** [kasper/phoenix#263]
- Version: 2.6.4 (86)
- macOS: 10.15.6 (19G2021)

Hi there, I'm trying to set up a trigger to launch a new `emacsclient` frame (window) if there isn't one already, but I'm struggling to figure out why `Task.run('/bin/sh', ['-c', 'emacsclient -nc -a ""'])` isn't working... 

Any ideas or tips for troubleshooting this sort of thing?

Thanks!

**Comment by mafredri** [comment]
Phoenix does not inherit your `$PATH` from the shell, so it may simply not find it. Try giving the full path to `emacsclient`, e.g. `/usr/bin/emacsclient`.

**Comment by idmyn** [comment]
That was exactly my problem 🤦🏻‍♂️

Thank you!
