### ISSUE TITLE
An Ability to receive events for an application after restart the application

### ISSUE THREAD

**Issue by varp** [kasper/phoenix#264]
- Version: 2.6.4
- macOS: 10.15.6

When an application was started before Phoenix's start, I receive events (ex. 'windowDidOpen') as expected.
When I restart the application, I lose the ability to receive further events for the application. In Phoenix's logs appears: `Error: Could not get process identifier for accessibility element (null). (-25201)`. 
I think, at the moment when the application starts, some Phoenix logic can not properly acquire permissions from `tccd` and therefore attach observer for AX events.

If I restart Phoenix, I get back the ability to receive events for the application.

**Comment by kasper** [comment]
@varp Hey! I’m sorry to hear about that! Does this happen with all apps for you or some particular app?

**Comment by varp** [comment]
Sorry for the delay. At the moment of the issue, I was working with the VS Code. Since then, because of lack of time, no made tests with other apps. Will come back, with more information ASAP.

**Comment by kasper** [comment]
@varp Thanks!

**Comment by kasper** [comment]
@varp Thanks for reporting this! The root cause for this was actually a pretty substantial issue. Phoenix was trying to register the window events too early for newly launched apps. This should now be fixed.
