### ISSUE TITLE
JSA Support

### ISSUE THREAD

**Issue by raguay** [kasper/phoenix#27]
Hi,

I have been using Mjolnir and then Hammerspoon, but I really do not like Lua. I came across Phoenix today and was excited, but it does not have all the functionality of Hammerspoon. Will it be updated to allow for remote controlling with Alfred through a RPC protocol? Also, why not use the built in JavaScript for Automation? That would be very nice to see. I tried to use JSA in the script, but it would not work. Also, what type of libraries does this have other than the windows controlling. IE: a file system access library, etc.

**Comment by kasper** [comment]
Hello @raguay! I took over this project and I’m currently refactoring and cleaning up the code to make it current. Personally, I’m committed into keeping a small, but useful JavaScript/CoffeeScript window and app management framework around. Phoenix does not have a modular library approach, such as in Mjolnir or Hammerspoon, the API documented is what you get.

Although JavaScript for Automation and Phoenix have partly similar intentions, personally, I do not like the API and partly weird use of JavaScript syntax provided in OS X by JSA. I do not see a need to support JSA directly, use the ScriptEditor in OS X to build JSA scripts and apps. However, you can run external scripts from Phoenix (therefor JSA scripts as well) — if you would like to extend the behaviour. To be honest, Alfred support is not high on the to-do list.

What I am hoping to do in the near future, is to add basic support for system, window and app events into Phoenix. Hope this answers some of your questions! :)

**Comment by NightMachinary** [comment]
@kasper Is there a way for external processes to eval some code in Phoenix?

For example, I like to be able to focus some app from my shell scripts. In hammerspoon, I can use `hs -c "some hammerspoon code..."`.

**Comment by kasper** [comment]
@NightMachinary Not currently, but it’s definitely something I would like to support in the future.

**Comment by NightMachinary** [comment]
[**@kasper**](https://github.com/kasper) commented on [Apr 18, 2021, 7:19 PM GMT+4:30](https://github.com/kasper/phoenix/issues/27#issuecomment-822003481 "2021-04-18T14:49:54Z - Replied by Github Reply Comments"):
> [@NightMachinary](https://github.com/NightMachinary) Not currently, but it’s definitely something I would like to support in the future.

Is it possible to use the popular JS REST API frameworks to manually implement RPC in the config file `.phoenix.js`? (I have no idea how that file is run ...)

**Comment by kasper** [comment]
The JavaScript context is loaded when the file changes. For dynamic commands Phoenix would need a server to listen for those.
