### ISSUE TITLE
How to make an app fullscreen on top of another app?

### ISSUE THREAD

**Issue by NightMachinary** [kasper/phoenix#270]
I am using the code from https://github.com/lukesmurray/bootstrap/blob/master/.phoenix.js to turn some apps into "hotkey popup windows." This works well except that the app's position is always below the menubar:
![image](https://user-images.githubusercontent.com/36224762/114995837-7a1d3080-9eb3-11eb-86fa-33e7c6bb14d2.png)

I tried using negative numbers for 
```
    mainWindow.setTopLeft({
      x: left,
      y: top,
    });
```
But it did not work.

`mainWindow.setFullScreen(true); ` is useless as I want the app to open on top of my existing apps, not in its own space.

**Comment by kasper** [comment]
@NightMachinary Hello! I guess you are you using the automatic hiding of the menu bar? I tried this out and you should be able to do this. Remember that the coordinate system is bottom-left focused (origo), growing as you go. Try `Window#maximise()` instead (https://github.com/kasper/phoenix/blob/2.6.7/docs/API.md#22-window). Let me know if this helps.

**Comment by NightMachinary** [comment]
@NightMachinary Weirdly, things just worked using my previous code, without using `maximise`. I don't know what was the problem.

PS: Does Phoenix store logs somewhere? I like to see the reasons my config has failed to load ...

Thanks!

**Comment by kasper** [comment]
@NightMachinary Great! Yes, check https://github.com/kasper/phoenix/blob/2.6.7/docs/API.md#logging-and-debugging.
