### ISSUE TITLE
Cannot extend Rectangle?

### ISSUE THREAD

**Issue by rcarmo** [kasper/phoenix#273]
- Version: 2.6.7
- macOS: 11.4

So I'm trying to extend Rectangle:

```
Rectangle.prototype.pad = () => {
	return new Rectangle(
		this.x + PADDING/2, 
		this.y + PADDING/2,
		this.width - PADDING,
		this.height - PADDING
	);
};
```

... and I get `ReferenceError: Can't find variable: Rectangle (Line:Column)`

Since I can hack `Screen`, shouldn't I be able to do the same for `Rectangle`, so that I can take a `Window.frame` and manipulate it directly like this?

**Comment by kasper** [comment]
Rectangle is NSRect (https://developer.apple.com/documentation/foundation/nsrect) under the hood. It’s a struct and not an object, so that’s the reason you get the error. I’m surprised nobody else has noticed this from documentation before. 😄 I’ll fix that.

**Comment by rcarmo** [comment]
Ah, ok. So I can't override it and do nice things like I do for `Window` and `Screen`. Hmmm.

**Comment by kasper** [comment]
@rcarmo You can of course pass it to functions, in a more functional approach.

```js
const pad = (rect) => ({
  ...rect,
  x: rect.x + PADDING,
});
```

**Comment by rcarmo** [comment]
Yeah, I wanted to make it smarter. Am now using something called a `Frame`, which can `.displace`, `.pad` and `.snap`, so I can do neat stuff like `foo.snap(screen, WEST).pad()`

**Comment by kasper** [comment]
I’ve clarified the documentation in this regard.
