### ISSUE TITLE
WIP: Phoenix 2.0

### ISSUE THREAD

**Issue by kasper** [kasper/phoenix#28]
Hello! I took over maintaining Phoenix a couple months ago. I’ve been hard at work and as a result the whole project has been rewritten and refactored from the ground up. See the WIP [2.0](https://github.com/kasper/phoenix/tree/2.0/)-branch. I’ve also clarified the API significantly. As a consequence this means existing configurations will not be compatible without small changes. See the [Changelog](https://github.com/kasper/phoenix/blob/2.0/CHANGELOG.md). Due to API-deprecations, Phoenix now requires OS X Yosemite (10.10) or higher.

The branch is still **work in progress**, however feel free to test it if you like. There may be still issues, so be aware of that. The existing API may still change, but mostly it’s now stable. If you notice something, please submit a new issue. For general discussion, you can use this thread. I will continue the work on 2.0 and my plan is to add basic support for events and I’ve got some ideas, features and API enhancements I’d like to see in the future before actually “releasing” 2.0.

**Comment by kasper** [comment]
Phoenix 2.0 is stable. I’ve added many useful functions to the API. Most of the related Accessibility API’s that were previously missing should now be supported. I’ll implement basic support for events before releasing Phoenix 2.0.

**Comment by kasper** [comment]
Build 5 is out. Unfortunately, I caught a nasty and tricky edge case memory leak while implementing events caused by a retention cycle when reloading (452e32714b295c7e386f3d7ee3a92eeba938dbdc). Long story short, this is now fixed, but **you must now keep a reference** to your key handlers when binding keys in order for your callbacks to get called. It seems this is the only way for JavaScriptCore to do the memory management correctly.

```javascript
var handler = Phoenix.bind('q', [ 'ctrl', 'shift' ], function () {});
```

Or a more sophisticated approach...

```javascript
var keys = [];
keys.push(Phoenix.bind('q', [ 'ctrl', 'shift' ], function () {}));
```

**Comment by kasper** [comment]
I’m currently working on implementing support for events (#14). Once complete, Phoenix 2.0 will be ready to be released.

**Comment by kasper** [comment]
Event support is now stable on build 7. 2.0 is getting close.

**Comment by khalidchawtany** [comment]
:+1: 
Thanks for the hard work.

**Comment by jasonm23** [comment]
:+1: Good work @kasper

**Comment by frantic** [comment]
Amazing work @kasper! I've just reimplemented all my favorite ShiftIt features in Phoenix 2.0 in like 30 minutes.

**Comment by kasper** [comment]
Thanks for the nice words! I really appreciate it. :)

**Comment by jasonm23** [comment]
Really excellent work @kasper

**Comment by shayne** [comment]
Do you have a hit list of bugs/features you could share in case the community can help you get to a 2.0 release?

**Comment by kasper** [comment]
@shayne Actually, your preprocessing pull request was the last big feature I wanted to add to 2.0. Otherwise all bugs and feature ideas are as issues on this repository. I think the release is very close, I only have some small tasks to complete. Hopefully, the release will happen in the coming weeks. :) I would assume all the major issues have already been reported. I’ll let you know if something can be done to help.

**Comment by kasper** [comment]
The day has come, Phoenix 2.0 is out! The entire app has been rewritten from the ground up. I would like to express my gratitude to everyone who participated in the process by testing the app and making contributions to the project. Thank you! We have added some very nice features lately: JavaScript preprocessing, additional configuration locations and Sparkle for automatic updates! See the full [Changelog](https://github.com/kasper/phoenix/blob/master/README.md).

**Comment by kasper** [comment]
I dropped some posts about the release!

- https://www.reddit.com/r/osx/comments/3umg55/phoenix_20_a_lightweight_os_x_window_and_app/
- https://news.ycombinator.com/item?id=10642279

**Comment by jasonm23** [comment]
X-posted to /r/JavaScript

**Comment by kasper** [comment]
@jasonm23 Good idea, thanks!
