### ISSUE TITLE
Q: Is there a way to get window identifiers?

### ISSUE THREAD

**Issue by jessie-ross** [kasper/phoenix#281]
Since there is no way to keep an array of window references without them becoming stale, I was wondering if there were a way to get window unique identifiers?

I am looking to be able to attach data to a specific window - i.e. I'm trying to emulate dwm and I would want to be able to tag windows.

**Comment by kasper** [comment]
@jessie-ross Hello, yes! [Window](https://github.com/kasper/phoenix/blob/master/docs/API.md#22-window) implements [Identifiable](https://github.com/kasper/phoenix/blob/master/docs/API.md#10-identifiable). Identifiable has the `hash()` function. So `window.hash()`. Hope that helps!
