### ISSUE TITLE
Is there a way to detect/react to system sleep events?

### ISSUE THREAD

**Issue by d1rewolf** [kasper/phoenix#282]
- Version: head
- macOS: Big Sur

I'd like to be able to do certain actions when my system goes to sleep. In Hammerspoon, they have https://www.hammerspoon.org/docs/hs.caffeinate.watcher.html which works very well. I'm trying to find the equivalent in Phoenix. The closest I've found screensDidChange, but this doesn't seem to fire on system sleep.

Is there a way to do this currently?

Thanks!

**Comment by d1rewolf** [comment]
Thanks for the response. For the time, I've switched back to Hammerspoon, but still hope to revisit Phoenix in the future. I'll research that approach and post back here if I reach a conclusion.

**Comment by kasper** [comment]
Sure! I’ll reopen this one still, so I can keep it as an improvement idea.

**Comment by kasper** [comment]
Added support for `deviceWillSleep` and `deviceDidWake`. Read more at https://kasper.github.io/phoenix/api/events/#device.
