### ISSUE TITLE
Build errors 

### ISSUE THREAD

**Issue by cfraizer** [kasper/phoenix#285]
- Version: 2.6.8
- macOS: 12.0.1
- clang: Apple clang version 13.0.0 (clang-1300.0.29.3)

Probably something in my environment, but I'm not sure where.  Any advice will be appreciated.

/Users/colinf/opensource/phoenix/Phoenix/PHAXUIElement.m:22:9: error: implicit declaration of function 'AXUIElementSetMessagingTimeout' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        AXUIElementSetMessagingTimeout((__bridge AXUIElementRef) self.element, 0.5);

From command:
CompileC /Users/colinf/Library/Developer/Xcode/DerivedData/Phoenix-dkulaupehvugkfcpysuestmlhfnp/Build/Intermediates.noindex/Phoenix.build/Release/Phoenix.build/Objects-normal/x86_64/PHAXUIElement.o /Users/colinf/opensource/phoenix/Phoenix/PHAXUIElement.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Phoenix' from project 'Phoenix')
    cd /Users/colinf/opensource/phoenix
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-macos10.10 -fmessage-length\=193 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fcolor-diagnostics -std\=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/Users/colinf/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/colinf/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Werror -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DCOCOAPODS\=1 -DNS_BLOCK_ASSERTIONS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility\=hidden -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -iquote /Users/colinf/Library/Developer/Xcode/DerivedData/Phoenix-dkulaupehvugkfcpysuestmlhfnp/Build/Intermediates.noindex/Phoenix.build/Release/Phoenix.build/Phoenix-generated-files.hmap -I/Users/colinf/Library/Developer/Xcode/DerivedData/Phoenix-dkulaupehvugkfcpysuestmlhfnp/Build/Intermediates.noindex/Phoenix.build/Release/Phoenix.build/Phoenix-own-target-headers.hmap -I/Users/colinf/Library/Developer/Xcode/DerivedData/Phoenix-dkulaupehvugkfcpysuestmlhfnp/Build/Intermediates.noindex/Phoenix.build/Release/Phoenix.build/Phoenix-all-target-headers.hmap -iquote /Users/colinf/Library/Developer/Xcode/DerivedData/Phoenix-dkulaupehvugkfcpysuestmlhfnp/Build/Intermediates.noindex/Phoenix.build/Release/Phoenix.build/Phoenix-project-headers.hmap -I/Users/colinf/opensource/phoenix/build/Release/include -I/Users/colinf/Library/Developer/Xcode/DerivedData/Phoenix-dkulaupehvugkfcpysuestmlhfnp/Build/Intermediates.noindex/Phoenix.build/Release/Phoenix.build/DerivedSources-normal/x86_64 -I/Users/colinf/Library/Developer/Xcode/DerivedData/Phoenix-dkulaupehvugkfcpysuestmlhfnp/Build/Intermediates.noindex/Phoenix.build/Release/Phoenix.build/DerivedSources/x86_64 -I/Users/colinf/Library/Developer/Xcode/DerivedData/Phoenix-dkulaupehvugkfcpysuestmlhfnp/Build/Intermediates.noindex/Phoenix.build/Release/Phoenix.build/DerivedSources -Wall -Wextra -F/Users/colinf/opensource/phoenix/build/Release -F/Users/colinf/opensource/phoenix/Pods/Sparkle -MMD -MT dependencies -MF /Users/colinf/Library/Developer/Xcode/DerivedData/Phoenix-dkulaupehvugkfcpysuestmlhfnp/Build/Intermediates.noindex/Phoenix.build/Release/Phoenix.build/Objects-normal/x86_64/PHAXUIElement.d --serialize-diagnostics /Users/colinf/Library/Developer/Xcode/DerivedData/Phoenix-dkulaupehvugkfcpysuestmlhfnp/Build/Intermediates.noindex/Phoenix.build/Release/Phoenix.build/Objects-normal/x86_64/PHAXUIElement.dia -c /Users/colinf/opensource/phoenix/Phoenix/PHAXUIElement.m -o /Users/colinf/Library/Developer/Xcode/DerivedData/Phoenix-dkulaupehvugkfcpysuestmlhfnp/Build/Intermediates.noindex/Phoenix.build/Release/Phoenix.build/Objects-normal/x86_64/PHAXUIElement.o
/Users/colinf/opensource/phoenix/Phoenix/PHAXUIElement.m:22:9: error: implicit declaration of function 'AXUIElementSetMessagingTimeout' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        AXUIElementSetMessagingTimeout((__bridge AXUIElementRef) self.element, 0.5);

**Comment by kasper** [comment]
@cfraizer Thanks for the report! I need to upgrade macOS and check.

**Comment by kasper** [comment]
This should now be fixed in master. It was broken by Xcode 13.1. Apparently Apple has moved the Accessibility APIs from “Foundation” to “Application Services”. Thanks @cfraizer for the fast spot! 😄

**Comment by cfraizer** [comment]
Thank you for the quick fix, @kasper. I'm too much of an Xcode/MacOS bozo to have found the solution myself, but I pulled the newest changes and it built easy-peasy!
