### ISSUE TITLE
Monterey-style icon

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#286]
I'd love if Phoenix got updated with a Monterey-style icon, which would be a square basically. The current icon sticks out as it doesn't align well with the new system design guidelines.

**Comment by kasper** [comment]
@fabiospampinato Hi! I presume you are referring to the app icon? Yes, I would like that as well, something that has been on my list. I would be more than happy if someone with app icon design experience would also contribute. 😄

**Comment by fabiospampinato** [comment]
@kasper I'm no designer but I'd be happy to try and make a new suitable icon. Do you have the PSD/raw version of the icon somewhere? The highest-resolution thing I could find is [this one](https://github.com/kasper/phoenix/blob/fc50e4d2d6df5f8793bd0e082e4331173d81a8aa/Phoenix/Images.xcassets/AppIcon.appiconset/icon_512x512%402x.png).

**Comment by kasper** [comment]
@fabiospampinato I don’t unfortunately. I would actually like to refresh the icon visually to something new at the same time.

**Comment by fabiospampinato** [comment]
Any particular ideas? I can turn the current icon into one that fits in Monterey, but I'm not sure I can draw a decent phoenix 😅

**Comment by kasper** [comment]
I think we could change the symbol completely or alternatively refresh it. Other than that, no particular ideas at the moment.

**Comment by kasper** [comment]
I asked for a new icon from https://www.parakeet.co. Let’s see what they come up with. 😁

**Comment by kasper** [comment]
Okay, I have the new icon, it looks great (at least in my opinion), but I will keep people in suspense until the update. 😄

**Comment by mafredri** [comment]
That’s awesome @kasper, can’t wait. Tried sketching one up myself on my reMarkable a while back but.. yeah no I’m no artist 🤣.


For LOLs:
![07F52ACC-F4B7-45A7-9EE7-A77E45E627CE](https://user-images.githubusercontent.com/147409/148235993-cf541565-a5d0-462f-9f1f-03482f1b437d.png)

**Comment by fabiospampinato** [comment]
@mafredri I'm not sure why but I see squirrels in your drawings 🤣

**Comment by kasper** [comment]
@mafredri Haha! Don’t they say that practice makes you better. 😄

**Comment by kasper** [comment]
I’ve updated the icon assets, hope everyone likes it!
