### ISSUE TITLE
Any way to create a standalone manager from this?

### ISSUE THREAD

**Issue by AryzenRS** [kasper/phoenix#291]
Hi, I'm not sure if I'm doing this right or if this is the appropriate place to ask. 

I'd like to know if there's any way to "publish" your window manager as something that can be easily received and downloaded by others, as if it were a whole package. 

I also would like to know if there are any licensing things to know if it is possible

**Comment by kasper** [comment]
@AryzenRS Hey! There’s no official package manager for the configurations, but what most people do is that they publish their configuration files on GitHub so people can easily download them. In the end, it can just be a single file that people can drop in the right place.

We could potentially extend the functionality of the app to provide a way of using configurations by automatically downloading them. Though there might be security implications to this.

**Comment by AryzenRS** [comment]
@kasper Hi! Thanks for the reply! 

I didn't quite mean for existing users of Phoenix to be able to download files easier, it is as easy as it gets already! 

I meant if there was any sort of way to perhaps package an installer or create a binary of Phoenix that could drop an already configured .phoenix.js on running. Or possibly have a configuration built in to the .app that it draws from instead, so the entire package can be shared as a whole

**Comment by jasonm23** [comment]
So a starter pack, but built in?

**Comment by AryzenRS** [comment]
> So a starter pack, but built in?

To a degree, yeah... A make-it-yourself starter pack that you can share that includes the Phoenix app and a user made configuration that's just drag and drop for a new user to install

I have a hard time communicating, sorry if I'm frustrating!

**Comment by jasonm23** [comment]
So the user gets a set of check boxes... 

- [ ] Foo 
- [ ] Bar
- [ ] Modal keys
- [ ] Something else...

Then they click a button and a pre-packaged `.phoenix.js` is downloaded? And placed into their home directory for them?

So they don't need to worry about the code at all.

So? What would the options be? Where will this service host? Who will manage it? Who will pay for it's infra costs?

- - -

Note the expectation here is that the feature request is owned by YOU the requester, and that YOU will deliver the bulk of the feature needs, design collaboration, code development, funding etc.
