### ISSUE TITLE
addWindows & removeWindows broken in macOS 12.2.1?

### ISSUE THREAD

**Issue by alexbepple** [kasper/phoenix#293]
Version: 2.6.8
macOS: 12.2.1

After upgrade from macOS 12.1 to 12.2.1, a handler that I have for moving windows from space to space stopped working. To me, it seems that `addWindows` and `removeWindows` don't do anything. I have not found any errors in Console.app. But maybe I did not look correctly.

My code is very similar to the docs example:
```
  const currentWindow = Window.focused()
  Space.all()[toIdx].addWindows([currentWindow])
  Space.all()[fromIdx].removeWindows([currentWindow])
  currentWindow.focus()
```

I see that with 3.0.0 there is a new `Space.moveWindows` method. From the API docs (["macOS 10.13+"](https://kasper.github.io/phoenix/api/space/#300)) it looks as though it relies an a new API and is not merely sugar. Any chance of an early release of 3.0.0?

**Comment by kasper** [comment]
Hello! Yes, this is a duplicate of #289 and is fixed in master with the new API. I’m trying release 3.0.0 in the next week or so.

**Comment by alexbepple** [comment]
Ah, yes. Thank you, @kasper. I did search the issues. But apparently not hard enough. 
Hopefully you can make the release happen. Thank you.

**Comment by kasper** [comment]
@alexbepple Released!

**Comment by alexbepple** [comment]
@kasper Works like a charm.
