### ISSUE TITLE
Navigate through Space

### ISSUE THREAD

**Issue by reynandaptr** [kasper/phoenix#294]
Hi, is there a way to navigate through space after fullscreen the current window? something like control + arrow left/right. 

Thanks in advance

**Comment by kasper** [comment]
@reynandaptr Hey! I’m not sure if I fully understand. Could you clarify a bit?

**Comment by kasper** [comment]
macOS supports the shortcuts <kbd>control</kbd> + <kbd>left/right</kbd> by default to switch between spaces. You can also switch to a specific space by focusing a window in that space.
