### ISSUE TITLE
window.setFrame intermittently unsuccessful when setting for a different screen

### ISSUE THREAD

**Issue by tobias-edwards** [kasper/phoenix#297]
- Version: 3.0.0
- macOS: 10.15.17

Calling `window.setFrame` such that the focused window is moved to another screen will intermittently fail:
https://github.com/kasper/phoenix/blob/39094643b939e5735f0e1d724139ba66190dc2b6/Phoenix/PHWindow.m#L305-L312

I made a prototype for my monitor setup:
- Screen 1: `{"y":0,"x":0,"width":1792,"height":1120}`
- Screen 2: `{"y":-320,"x":-2560,"width":2560,"height":1440}`

```
    Screen 2       Screen 1
|---------------|-------------|
|   2560x1440   |  1792x1120  |
|               |-------------|
|---------------|
```

```js
// Left-side of screen 2
Key.on('a', ['ctrl', 'option'], () => {
  const worked = Window.focused().setFrame({
    x: -2560,
    y: 23,
    width: 1280,
    height: 1417,
  });
  Phoenix.log(worked);
});

// Left-side of screen 1
Key.on('b', ['ctrl', 'option'], () => {
  const worked = Window.focused().setFrame({
    x: 0,
    y: 23,
    width: 896,
    height: 1097,
  });
  Phoenix.log(worked);
});
```

`window.setFrame` will intermittently fail when moving the window from screen 1 to screen 2. The result is the window having the correct location and width, except the height is incorrect (it seems to keep the smaller height of screen 1?).

Currently, I'm either having to put up with the issue, or run a loop to keep calling `window.setFrame` until it succeeds:

```js
Window.prototype.setFrame_ = function (args) {
  let attempts = 0;
  let success = false;
  do {
    success = Window.prototype.setFrame.call(this, args);
    attempts += 1;
  // Attempts typically between 1-5, but can be as high as 24!
  } while (!success && attempts < 30);
  return success;
};
```

Any advice on handling this issue and why it might occur only sometimes?

**Comment by tobias-edwards** [comment]
Interestingly, the same issue occurs in other window managers e.g. [Rectangle](https://github.com/rxhanson/Rectangle)

**Comment by kasper** [comment]
@tobias-edwards Hello! Does this happen to you with every app or only particular ones?

**Comment by tobias-edwards** [comment]
> @tobias-edwards Hello! Does this happen to you with every app or only particular ones?

Interesting! The issue affects:
- Firefox
- iTerm 2
- Microsoft Excel
- Spotify

But does not affect:
- Finder
- Google Chrome
- Microsoft Teams
- Microsoft Word
- Safari
- Visual Studio Code

**Comment by tobias-edwards** [comment]
I'll stick with my workaround, thanks for the insight. Apps having minimum window sizes is a pain!

Thank you very much for Phoenix, it's awesome.

**Comment by kasper** [comment]
Thanks for the kind words! 🙌
