### ISSUE TITLE
`Window.focused().topLeft()` returns `Point` relative to `Screen` with menu bar

### ISSUE THREAD

**Issue by ptrkstr** [kasper/phoenix#298]
- Version: 3.0.0 (127)
- macOS: 12.3 (21E230)

#### Steps:
1. Configure display to the following:  

![image](https://user-images.githubusercontent.com/11362913/161025504-4f762738-34fd-43fa-b9e4-15fc069e08e1.png)

2. Configure `.phoenix.js` script to the following:

```
Key.on('q', ['ctrl', 'option'], () => {
  const frame = Window.focused().topLeft();
  Phoenix.notify(`${frame.x} ${frame.y}`)
})
```

3. Drag a window to the top left of the menu bar screen

![image](https://user-images.githubusercontent.com/11362913/161025094-e5f95df4-be22-4022-8da8-945bbf0c0341.png)

4. Press ctrl+option+q and observe notification:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/11362913/161025235-4e936b46-7ee7-4d29-8d9d-4336cf16ee2d.png">

✅  0, 38 

5. Drag a window to the top left of the top screen

![image](https://user-images.githubusercontent.com/11362913/161025465-7069f7c1-b1d9-41f9-9e63-acc51a25824a.png)

6. Press ctrl+option+q and observe notification:

<img width="342" alt="image" src="https://user-images.githubusercontent.com/11362913/161025793-97da8a53-9768-4624-8b18-4999d6e77ded.png">

❌  -434, -1415

#### Expected:

0, 38 

#### Observed:

-434, -1415

#### Notes:

If the menu bar is moved to the top screen, the correct values are observed when pressing ctrl+option+q when a window is in the top screen.

**Comment by ptrkstr** [comment]
I noticed that `topLeft` access the value at `NSAccessibilityPositionAttribute` which doesn't provide much documentation.
> The position in points of the element's lower-left corner in screen-relative coordinates (NSValue).

However I believe it's the same as `kAXPositionAttribute`:
> The global screen coordinates of the top-left corner of this accessibility object. Note that the coordinates 0,0 represent the top-left corner of the screen that displays the menu bar. All accessibility objects that have a screen position (in other words, are visible on the screen) should include this attribute.

If this is the case @kasper, does Phoenix currently offer a way to convert the `Window.focused` coordinates to `Screen.main` coordinates?

**Comment by ptrkstr** [comment]
Closing the issue as I believe this is how it's meant to behave.

**Comment by kasper** [comment]
@ptrkstr Hello! So as you figured it out, all the screens together combine a massive coordinate system, depending on your display configuration. Therefore you need to calculate the positions based on the origin.

**Comment by kasper** [comment]
@ptrkstr Very simple and nice! 😄 I haven’t signed up for GitHub sponsorship yet, I would need to check what the tax implications look like. Thanks for the thought! ❤️
