### ISSUE TITLE
setFullScreen and isFullScreen not working

### ISSUE THREAD

**Issue by MatthiasGrandl** [kasper/phoenix#305]
- Version: 3.0.0
- macOS: 12.3.1

`Error: Could not set accessibility attribute “AXFullScreen” with value “0” for element <AXUIElement 0x600000651530> {pid=1664}. (-25202)`  

Phoenix has accessibility permissions and most other features seem to work.

**Comment by kasper** [comment]
@MatthiasGrandl Hello! Sorry to hear that, is this for a specific app or for everything?

**Comment by MatthiasGrandl** [comment]
It seems to be for everything. But honestly I don’t think there is anything wrong with phoenix as plain applescript also does not work.

**Comment by kasper** [comment]
@MatthiasGrandl Did you try restarting the computer? 😄

**Comment by kasper** [comment]
```objective-c
    /*! The AXUIElementRef passed to the function is invalid. */
    kAXErrorInvalidUIElement			= -25202,
```

I checked the error code. It refers to the UI element (window) being invalid. So likely it doesn’t exist anymore, it’s not a window or potentially something else.
