### ISSUE TITLE
Building with Xcode 7 throws errors

### ISSUE THREAD

**Issue by zchee** [kasper/phoenix#31]
I checkouted 2.0 branch, and run command...
```
xcodebuild build
```

but, displyed ** BUILD FAILED **

result,
```
/Users/zchee/src/github.com/kasper/phoenix/Phoenix/PHAXUIElement.m:14:17: error: method override for the designated initializer of the superclass '-init' not found [-Werror,-Wobjc-designated-initializers]
@implementation PHAXUIElement
                ^
In module 'Foundation' imported from /Users/zchee/src/github.com/kasper/phoenix/Phoenix/PHAXUIElement.h:5:
In module 'CoreFoundation' imported from /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Dispatch' imported from /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15:
In module 'os' imported from /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/dispatch/dispatch.h:48:
In module 'ObjectiveC' imported from /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/os/object.h:75:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/objc/NSObject.h:60:1: note: method marked as designated initializer of the class here
- (instancetype)init
^
1 error generated.
```

I do not edit `.xcodeproj` file.
Do you have any idea?

- OS: OS X El Capitan beta 8
- Xcode: Xcode-beta 7 beta 6 (7A192o)

**Comment by kasper** [comment]
Hello! I haven’t tested Phoenix on OS X El Capitan, so it’s not officially supported yet. Anyway, that’s actually a build warning. You can try turning “Treat Warnings as Errors” off in the build settings and building again. I’ll investigate if there’s a change regarding this warning in the betas and why this issue is raised on 10.11. Thanks for reporting!

**Comment by kasper** [comment]
@zchee Actually, could you check that you are indeed using Xcode Beta command line tools for your `xcodebuild` environment and not for example Xcode 6. It should be the path for Xcode Beta on El Capitan. If not, you should select Xcode Beta over Xcode 6.  What does the following command give for you? 

```
~ $ xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

**Comment by zchee** [comment]
Hi, thank reply.

```
$ xcode-select -p
/Applications/Xcode-beta.app/Contents/Developer
```

phoenix build need to Xcode version 6?

**Comment by kasper** [comment]
@zchee Thanks! No, Phoenix shouldn’t need Xcode 6. Your environment seems to be fine. Have you tried building on Xcode 7 GM?

**Comment by zchee** [comment]
@kasper Ok, I will try build use Xcode 7 GM.
After that, I will tell you again result :)

**Comment by zchee** [comment]
@kasper Hmm....
BUILD FAILED too.
```
/Users/zchee/src/github.com/kasper/phoenix/Phoenix/PHAXUIElement.m:14:17: error: method override for the designated initializer of the superclass '-init' not found [-Werror,-Wobjc-designated-initializers]
@implementation PHAXUIElement
                ^
In module 'Foundation' imported from /Users/zchee/src/github.com/kasper/phoenix/Phoenix/PHAXUIElement.h:5:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15:
In module 'os' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/dispatch/dispatch.h:48:
In module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/os/object.h:75:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/objc/NSObject.h:60:1: note: method marked as designated initializer of the class here
- (instancetype)init
^
1 error generated.
```

```
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

$ xcrun -f clang
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang

$ clang -v
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

Do you have any idea?

**Comment by kasper** [comment]
Darn, I don’t have El Capitan installed just yet, so I can’t debug this for now.

You can try to disable the “Treat Warnings as Errors” option from the project’s build settings. That should make the build pass. If not, remove the `NS_DESIGNATED_INITIALIZER` macro from `PHAXUIElement.h` (https://github.com/kasper/phoenix/blob/2.0/Phoenix/PHAXUIElement.h#L11) and see if that makes the error disappear. Would you be able to test these?

**Comment by kasper** [comment]
@zchee Okay, so yes. The specification for designated initialisers has definitely changed in Xcode 7. I finally found a reliable source for the change: https://forums.developer.apple.com/thread/6757. However, you should be able get round this issue for now by disabling “Treat Warnings as Errors”.

**Comment by kasper** [comment]
Indeed, unfortunately Phoenix currently does not build on Xcode 7 without turning warnings off. I’ll fix this at latest when 10.11 is released.

**Comment by zchee** [comment]
@kasper 
Thanks added 2.0 milestone :)

I do not know much of xcode. However, it seems unable to build in version 7.
but, As your instructions, by `Treat Warnings as Errors` setting to `NO`, that can be built has been confirmed :)

I hope that corresponds to when 10.11 is released.
Thanks.

**Comment by kasper** [comment]
@zchee Thanks for debugging this issue! I hope you like Phoenix. :) Please let me know if you have any questions.

**Comment by kasper** [comment]
This should now be fixed!

**Comment by zchee** [comment]
@kasper Yes! Thanks :)
