### ISSUE TITLE
Is it possible to open PDF or Word file?

### ISSUE THREAD

**Issue by seabornlee** [kasper/phoenix#311]
I tried Task, or require child_process, neither can do it.

**Comment by kasper** [comment]
Hey @seabornlee, yes! Try `Task.run('/usr/bin/open', ['file-you-want-to-open.pdf']`?

**Comment by seabornlee** [comment]
Thanks very much! It would be great if have this example in docs.

**Comment by kasper** [comment]
Good idea, I’ll add it! 👍

**Comment by seabornlee** [comment]
@kasper When path contains space, it won't open, what should I do?

**Comment by kasper** [comment]
@seabornlee Hey! The same as you would do in a terminal. Escape it or put the path in quotes. https://apple.stackexchange.com/questions/14683/how-to-cd-to-a-directory-with-a-name-containing-spaces-in-bash

**Comment by seabornlee** [comment]
Thanks!
