### ISSUE TITLE
Cannot change Modal font size (weight?)

### ISSUE THREAD

**Issue by l00sed** [kasper/phoenix#314]
- Version: 3.0.0
- macOS: 12.6, arm64

I'm trying to shrink the font size from a Modal pop-up.
```
Modal.build({
  weight: 12,
  text: 'Test',
}).show();
```
Font size remains a large size, probably the default 24 points.
Any advice?

**Comment by kasper** [comment]
@l00sed Hey, it seems like this is a regression that was introduced in 3.0.0. I’ll try to fix it as soon as possible. Thanks for the report!

**Comment by kasper** [comment]
Glad you like it, happy to hear! 😄

**Comment by kasper** [comment]
@l00sed As a workaround, set both the `font` and `weight` attributes. The bug happens only when using the default font and trying to adjust the weight.

**Comment by kasper** [comment]
Fixed in master.
