### ISSUE TITLE
Window.screen returns undefined for all windows

### ISSUE THREAD

**Issue by ordnungswidrig** [kasper/phoenix#316]
- Version: 3.0.0 (127)
- macOS: 12.6 (Monterey)

After reboot (I guess because OS update) the following expression would return `undefined` for all `window.screen` on all windows

```
Window.all().map((w) => {
    Phoenix.log(w, "->", w.screen());
})
```

**Comment by kasper** [comment]
@ordnungswidrig Hey, sorry to hear! Could you verify that you have Accessibility enabled for Phoenix in System Preferences?

**Comment by ordnungswidrig** [comment]
TFY: on a different machine running MacOS 12.6 everything is running as expected. 😕

**Comment by kasper** [comment]
@ordnungswidrig Peculiar! It’s safe to assume you have also restarted your computer?

**Comment by ordnungswidrig** [comment]
I did restart (again) and now everything is working as before. 😩 Not clear what the exact cause was and we might never know.
