### ISSUE TITLE
Support for mouseDidMiddleClick and mouseDidMiddleDrag

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#322]
- Version: 3.0.0
- macOS: 12.5.1

It'd be nice if those events could be supported.

**Comment by kasper** [comment]
Sounds like [NSOtherMouseUp](https://developer.apple.com/documentation/appkit/nsothermouseup) and [NSOtherMouseDragged](https://developer.apple.com/documentation/appkit/nsothermousedragged) would likely trigger in this case. To support, the mapping would need to be added.

**Comment by kasper** [comment]
Added `mouseDidOtherClick` and `mouseDidOtherDrag` events for tertiary click and drag events.
