### ISSUE TITLE
Ensuring input modals have a fixed width

### ISSUE THREAD

**Issue by fabiospampinato** [kasper/phoenix#324]
IMO input modals should have a fixed width, like Spotlight, otherwise interacting with them is a little weird because there's an unnecessary layout shift.

When I first open the modal I see this, not even the entire placeholder fits:

<img width="194" alt="Screen Shot 2023-02-03 at 02 51 31" src="https://user-images.githubusercontent.com/1812093/216501145-d8716c40-7978-4199-9780-e2066f379a30.png">

**Comment by fabiospampinato** [comment]
I've restarted the computer and now the width seems fixed, I'm not sure why it works differently now 🤔

**Comment by fabiospampinato** [comment]
Oh what changed is that previously I was setting `inputPlaceholder`, while now I'm only setting `text`.

**Comment by kasper** [comment]
Yes, the input modal width should be fixed. Likely the constrain doesn’t work properly if you only set `inputPlaceholder`. Thanks for reporting!

**Comment by kasper** [comment]
There was a layout issue depending on what properties were set initially. This should now be fixed in master.
