### ISSUE TITLE
brew or brew cask installer

### ISSUE THREAD

**Issue by alexg0** [kasper/phoenix#33]
Would be nice to be able to install ```phoenix``` with homebrew.  I can obviously self-build, but ```brew``` is good way to automate the process.

Previous maintainer was opposed to homebrew, and installer was removed.  Would you be willing to have it reinstated?

https://github.com/caskroom/homebrew-cask/pull/10732
https://github.com/caskroom/homebrew-cask/commit/fa81c27899feb00b1e73ce89acb401165fd5d352

**Comment by kasper** [comment]
Hi @alexg0! Definitely — my aim is to support prebuilt binaries for Phoenix. However, this probably will have to wait until 2.0 is released in the near future.

**Comment by jasonm23** [comment]
We should add a build script to produce/publishing the pre-built app bundle, also update the cask formula (and get it reinstated.)

I have some time free from Thursday this week, so I'd be happy to do it.  I'll just put these tasks here:

- [ ] build / publish script for prebuilt binaries
- [ ] reinstate brew cask formula

@kasper - Hopefully very soon we can make 2.0 the default branch. (branching master to a 1.5 maintenance branch would not be a bad idea perhaps?) - we could provide pre-built for both.

It would probably be wise to add self updating with [sparkle](http://sparkle-project.org/) too.

**Comment by kasper** [comment]
@jasonm23 Yep, I’m confident and happy, we can launch 2.0 pretty soon. I just have a few things to go through before making the decision.

I think I’ve made the decision to drop support for 1.5 entirely. The codebase has changed drastically, so it just too much of a burden to keep it supported. Let’s give 2.0 a fresh start.

I’m happy to sign the app with my own personal developer certificate to avoid Gatekeeper annoyances for users. This will obviously not enable a fully automatic build and publish phase for anyone else than me, but I’m fine with that.

The plan is to support GitHub releases for pre-built app bundles and have brew cask use these. Homebrew will obviously give one update path, but I think adding Sparkle is a good idea. Let me look into that. Maybe we should try to get it into 2.0... I’m not sure yet.

**Comment by jasonm23** [comment]
What should we do about brew cask? I assume we should wait until the 2.0 switch is done.

You should go ahead when ready of course, don't forget to drop a post on Hacker News, Reddit OSX etc.

**Comment by kasper** [comment]
We will definitely support brew cask, but we need to wait to get the app released for the correct download URL’s and hashes. I’m happy if anyone would like to contribute the pull request for brew once the app is released. I’m working on the release-script now and I’m hoping that Phoenix 2.0 will be released today!

**Comment by jasonm23** [comment]
Good stuff, I'm hitting 10pm here (Singapore time) so I look forward to seeing  some nice news in the morning.

**Comment by kasper** [comment]
@jasonm23 Sure. I’m currently in London, so that’s a good bet. :)

**Comment by kasper** [comment]
Okay, Phoenix 2.0 is out! We can now add the formula to brew cask. :smiley:

**Comment by kasper** [comment]
Hacker News and Reddit will have to wait until tomorrow. Time to get some sleep!

**Comment by jasonm23** [comment]
Great news Kasper

Copying the download path here for quick ref

https://github.com/kasper/phoenix/releases/download/2.0/phoenix-2.0.tar.gz

**Comment by jasonm23** [comment]
Cask recipe is:

```ruby
cask :v1 => 'phoenix' do
  version '2.0.0'
  sha256 'b3abae45218770cb999a2b5da35bd44ac03e38897fdf8248907e6de34a12e6b9'

  url 'https://github.com/kasper/phoenix/releases/download/2.0/phoenix-2.0.tar.gz'
  name 'Phoenix'
  homepage 'https://github.com/kasper/Phoenix'
  license :mit

  app 'Phoenix.app'

  zap :delete => '~/.phoenix.js'
end
```

Note I've set the version at `2.0.0` (I suggest we use the [semantic versioning system](http://semver.org/).)

**Comment by jasonm23** [comment]
Oh, I guess I should add the additional `.phoenix.js` locations to `zap`

**Comment by kasper** [comment]
SemVer is fine for cask. I usually, just omit the trailing patch .0 if the environment doesn’t require it. Aesthetics... So shall I make the pull request or?

**Comment by kasper** [comment]
The homepage should be lowercased: `https://github.com/kasper/phoenix/`.

**Comment by jasonm23** [comment]
I have a fork, but I think you should add PR

**Comment by kasper** [comment]
Ok, sure!

**Comment by kasper** [comment]
All right, the cask for Phoenix is awaiting review.

**Comment by adityadalal924** [comment]
Closed via https://github.com/caskroom/homebrew-cask/pull/15461 & https://github.com/caskroom/homebrew-cask/pull/15462.

Added to readme with https://github.com/kasper/phoenix/pull/56

**Comment by kasper** [comment]
Thanks, this is now solved!

**Comment by jasonm23** [comment]
:+1:
