### ISSUE TITLE
Link to https://github.com/kasper/phoenix/workflows/CI/badge.svg in README is broken

### ISSUE THREAD

**Issue by hboon** [kasper/phoenix#337]
Link to https://github.com/kasper/phoenix/workflows/CI/badge.svg in README is broken:

<img width="322" alt="Screenshot 2023-08-28 at 11 04 32 AM" src="https://github.com/kasper/phoenix/assets/56189/5aef1b94-7a3c-458f-826e-9d03d67b27a2">

**Comment by kasper** [comment]
@hboon Thanks for reporting!
