### ISSUE TITLE
Get app by bundleIdentifier ?

### ISSUE THREAD

**Issue by dan-phantom** [kasper/phoenix#343]
- Version: 4.0.0
- macOS: Sonoma 14.2.1

Hi, is it possible to get an app by bundleIdentifier and not the name?

I have a weird case when two apps have the same name "Simulator" but they are different and I guess Phoenix tries to maximise the wrong one.

Thank you 🤗 

<img width="1009" alt="Screenshot 2024-02-09 at 20 40 37" src="https://github.com/kasper/phoenix/assets/148761039/f4298d15-6c26-4b32-a9a2-fc39ddb0b42a">

**Comment by kasper** [comment]
Hi @dan-phantom! If the app is already running, you can do something like the following.

```js
const match = App.all().find(app => app.bundleIdentifier() === 'identifier');
```

**Comment by dan-phantom** [comment]
I don't know why I didn't think of this, thank you  🙏
