### ISSUE TITLE
Is it possible to get window created time?

### ISSUE THREAD

**Issue by gutenye** [kasper/phoenix#344]
`app.windows()`, `Window.all()`, `Window.recent()` all return windows in recent order. But I want to get the windows in fixed order. If there's a window created time, then I can sort the windows.

**Comment by kasper** [comment]
@gutenye Hey! At the moment, there is nothing in the API that would give this to you directly. You could use events for this, something like the following.

```js
Event.on('windowDidOpen', (window) => {
  window.createdAt = new Date();
});
```
