### ISSUE TITLE
Call function on drag click with modifier key

### ISSUE THREAD

**Issue by l16r** [kasper/phoenix#353]
- Version: 4.0.1
- macOS: Sonoma 14.6.1

I want to implement functionality that allows the window to be moved without clicking the title bar. My idea is to register a drag click while hovering over a window and a modifier key (e.g. "command") being pressed and then move the window position relative to the mouse position in comparison to the start. The behavior is similar to the one implement by [dwm](https://dwm.suckless.org/).
However, I don't want to require any key to be pressed other than the command modifier key. Trying to achieve this behavior in the following manner does not work:

```
Key.on("command", [], () => console.log("command"))
```

And how can I connect this to the `mouseDidLeftDrag` event?

**Comment by kasper** [comment]
Hi @l16r! Sorry for the delay. You cannot bind an empty set of keys. So unfortunately, you will need to specify some key in addition to the command modifier.

For combining the drag event, you can do something like this:

```js
Key.on('command', 'q', () => {
  Event.once('mouseDidLeftDrag', () => {
    // Move window
  });
});
```

**Comment by mafredri** [comment]
@l16r if it helps, feel free to use my implementation for inspiration: https://github.com/mafredri/phoenix-config/blob/af7ee9657a14eb70cb69652ccd1849faf327dc09/src/phoenix.ts#L26-L146

It works like this:

- `hyper` = `cmd+ctrl+alt`
- Press `hyper + a` and keep holding `hyper` to activate window movement
- Press `hyper + shift + a` and keep holding `hyper + shift` to activate window resize
- Whilst active and holding `hyper`, you can release or press `shift` to swap between move and resize

I never polished it, so it has some rough edges but works pretty well most of the time.
