### ISSUE TITLE
Phoenix supported ElCapitan SplitView?

### ISSUE THREAD

**Issue by zchee** [kasper/phoenix#37]
Hi, @kasper .
Thank you kindly reply in this issue https://github.com/kasper/phoenix/issues/31 :)

===

I usually use a El Capitan new feature Split View when writing code.

Phoenix work fine with state of the Split View. Wonderful :)
but, It does occasionally behave strangely.

e.g.
```js

var Frame = {
  width: 1,
  height: 1,
  half: {
    width: 0.5,
    height: 0.5
  },
};

// omit...

keys.push(Phoenix.bind('h', controlShift, function() {
  Window.focusedWindow() && Window.focusedWindow().grid(Frame.half.width, Frame.height);
}));

keys.push(Phoenix.bind('l', controlShift, function() {
  Window.focusedWindow() && Window.focusedWindow().reverseGrid(Frame.half.width, Frame.height);
}));
```

On Split View mode,
e.g.
```
|< Full display size  >|
    30%        70%

|        |             |
| Chrome |    iTerm    |
|        |             |
```
Pressed `Ctrl+Shift+h`, focused window(`Chrome`) resized half display size and move to **left** side on display. OK.
```
     50%         50%

|           |          |
|  Chrome   |   iTerm  |
|           |          |
```

Pressed `Ctrl+Shift+l`, resized and move to **right** side on display.
but, already exists some window(`iTerm`) right side on display.
So, `Chrome` was move to the background of the `iTerm`.
```
     50%         50%

|           |          |
|           |   iTerm  | <- background Chrome
|           |          |
```

I hope that the location of windows to switch.
Are there any good methods for that?

**Comment by zchee** [comment]
FYI, I use Phoenix `2.0` latest.

**Comment by kasper** [comment]
@zchee Got it. What a descriptive report! Unfortunately, as far as I know, there does not seem to be an API to recognise when an app is using El Capitan’s split view feature nor is there an Accessibility API to interact with it directly. So unfortunately you would probably need to bind a separate key to handle a split view situation and flip the windows (origins) around in the reverse grid situation.

**Comment by zchee** [comment]
@kasper 
If possible when API has been published apple?

**Comment by kasper** [comment]
@zchee Unfortunately, as it stands, Apple has not even added Spaces support to the Accessibility API. So I would not expect Split View support to be added any time soon. :(

**Comment by kandros** [comment]
wonder if sierra made some improvements for Accessibility api and split view

**Comment by kasper** [comment]
Unfortunately no. Nothing new regarding this.

**Comment by ngryman** [comment]
👋 Anything new in 2018?

**Comment by fabiospampinato** [comment]
@kasper by any chance the required APIs have been added in Catalina?
