### ISSUE TITLE
Sometimes app.focus() has a very long delay

### ISSUE THREAD

**Issue by frantic** [kasper/phoenix#38]
Pheonix 2.0

It's quite hard to reproduce this issue, but it happens to me from time to time. I have a keybinding that is supposed to activate an app.

Config:

```javascript
function focusApp(name) {
  Phoenix.log('About to focus ' + name);
  App.runningApps().forEach(function(app) {
    if (app.name() === name) {
      Phoenix.log('Found and focusing ' + name);
      Phoenix.log(app.focus());
      Phoenix.log('Done focusing ' + name);
    }
  });
}

var handlers = [];
var mod = ['ctrl', 'cmd', 'alt'];

// ...more stuff

handlers.push(Phoenix.bind('w', mod, function () {
  focusApp('Google Chrome');
}));

// ...more stuff
```

Most of the times it works. However, sometimes when I press `Ctrl+Cmd+Alt+w` nothing happens for a few seconds and the Chrome pops up.

Logs:

<img width="374" alt="screen shot 2015-10-22 at 3 00 51 pm" src="https://cloud.githubusercontent.com/assets/192222/10680814/14cfe1ac-78d8-11e5-9ec3-842d22a6701b.png">

I can confirm logs are added instantly when I press the shortcut, it's `app.focus()`'s effect that is delayed.

@kasper  any ideas what's going on or how can I further debug the issue?

**Comment by kasper** [comment]
@frantic Hello! Are you sure it is caused by the actual focus-action or by searching the app by looping? Is the log output an example of a situation when it takes too much time? You could try `App.launch` — if the app is already running it will return its instance. (Perhaps I could even add a wrapper for this, such as `App.get`.)

The actual focus action is just a single framework call as itself… In that case, the issue probably is caused by Chrome not responding immediately or OS X is throttling the events. I will see if I can spot something.

**Comment by frantic** [comment]
@kasper I looked up microsecond timestamps in logs and looks like the loop takes at most 10-20ms, so it's not the issue. Probably OSX itself is causing it. I can try to reproduce this in Mjolnir or another similar app.

Nice trick about `App.launch`, will try that too!

**Comment by kasper** [comment]
@frantic Yes, I indeed doubted the looping scenario, but you never know. Sometimes OS X’s Accessibility API is a bit fragile. If the app is unresponsive, it will simply fail. Currently, Phoenix does not retry when this happens.

**Comment by kasper** [comment]
@frantic By the way, have you noticed if this is happening with only particular apps or just sometimes regardless of the app?

**Comment by shayne** [comment]
This works consistently for me.

```javascript
keyHandlers.push(Phoenix.bind('c', mod1, () => {
  const app = App.launch("Google Chrome");
  app.focus();
}));
```

**Comment by frantic** [comment]
@kasper Chrome works fine, Sublime Text and iTerm2 are not getting focused. Have tried assigning different shortcuts, key combination is not an issue. Very weird.

@shayne unfortunately `App.launch` didn't work for me :( `app.focus()` consistently returns `0`.

**Comment by kasper** [comment]
@frantic Are you up-to-date with the 2.0-branch? There was an issue that was fixed with ae20e1f that might be related.

**Comment by frantic** [comment]
@kasper just pulled new changes and the bug is gone! Thank you :)

**Comment by kasper** [comment]
Brilliant, sorry about that! :)
