### ISSUE TITLE
Preprocessor output is clipped

### ISSUE THREAD

**Issue by jasonm23** [kasper/phoenix#46]
It seems the the output of a preprocessor is being clipped.  When the output is read, it's start point appears to be set to the length of the shebang string.

This is a bit odd to me, which preprocessors are spitting out their shebang line that needs to be cut out?

For me this is messing badly with the output from coffee / lit-coffee, which (as expected) has no shebang in the output and so has it's opening function wrapper and var declarations mangled.

I'm working on a fix for this now, and will have a PR ready in a little while.

**Comment by kasper** [comment]
@jasonm23 Good catch!

**Comment by kasper** [comment]
Should be fixed by #48.
