### ISSUE TITLE
Sparkle support

### ISSUE THREAD

**Issue by kasper** [kasper/phoenix#50]
Use Sparkle-framework (with CocoaPods) to enable automatic software updates.

**Comment by kasper** [comment]
We can probably use GitHub for the appcast. I’m working on this and I think this will be the last feature to be included to 2.0 before release.

**Comment by jasonm23** [comment]
Ok sounds good

**Comment by kasper** [comment]
Since Sparkle is downloading executable code to users’ systems, here’s a security check that we will conform to http://sparkle-project.org/documentation/#segue-for-security-concerns:

- We will be serving the appcast over https through this repository 
- We will be serving the updates over https through GitHub releases
- Phoenix will be signed with my Apple Developer ID to retain integrity
- Update archives will be signed with a DSA signature
- It should be fine to keep the DSA public key in this repository
- I will keep the DSA private key secure and share when required

Sparkle support should be implemented in the `add-sparkle-support`-branch. I’ll test it out before merging.

**Comment by jasonm23** [comment]
Sounds good

**Comment by kasper** [comment]
Well look at that! Sparkle support is integrated, tested and ready for the launch. :)

**Comment by jasonm23** [comment]
Decent :) :+1:
