### ISSUE TITLE
Mouse.location() bug

### ISSUE THREAD

**Issue by alswl** [kasper/phoenix#58]
I use `save_mouse_position_for_window()` to save mouse postion, and `restore_mouse_position_for_window()` to restore mouse postion.

It works good for phoenix 1.0, and in phoenix 2.0, it always restore with a wrong postion.

After comare, I found, `Mouse.location()` and `Mouse.moveTo()`'s result sum is 800px - the height of Macbook Pro screen height.

My fix in config file is here:
https://github.com/alswl/.oOo./commit/bdd84c7a4b558a5ef3694de3b66b96687f7a6d5b

**Comment by alswl** [comment]
And more infomations, I use two monitors.

**Comment by kasper** [comment]
Thanks for reporting! I’ll look into this.

**Comment by kasper** [comment]
@alswl Indeed, there seems to be an issue with a mismatch of NSRect and flipped CGRect coordinates.

**Comment by kasper** [comment]
@alswl Thanks! This is now fixed in master and will be released in 2.0.1.
