### ISSUE TITLE
Continuous prompt to Enable Accessibility

### ISSUE THREAD

**Issue by mkdjns** [kasper/phoenix#59]
With 2.0, no matter how many times I enable accessibility for Phoenix, I get prompted to enable it. I follow the steps, relaunch and am prompted again. Each time accessibility for Phoenix seems to be disabled when I open Security & Privacy.

This does not happen with Phoenix 1.5.

**Comment by kasper** [comment]
Weird, I’m sorry to hear that! Please try the following: quit Phoenix (whichever version), go to Security & Privacy and remove the entry entirely, and finally restart your computer. After these steps, try to launch Phoenix 2.0 once more and see what happens. Thanks!

**Comment by mkdjns** [comment]
Sigh... of course that worked. The old "turn it off and on again".

Thanks!

**Comment by kasper** [comment]
Your welcome! OS X can get a little misbehaved sometimes. ;)

**Comment by jasonm23** [comment]
Reopening as this seems to be routine when replacing Phoenix `1.x.x` with `2.x.x` 

Restarting (logging out doesn't cut it) is required to move past the Enable Security Accessibility prompts.
