### ISSUE TITLE
How to set focus on application on another Space

### ISSUE THREAD

**Issue by gwww** [kasper/phoenix#6]
Have 2 spaces, 1 and 2.
Chrome is running, not minimized in Space 1.
Currently on Space 2.

How to switch to Space 1 and focus Chrome? I can find Chrome using findAppByTitle (from one of the sample configs). I cannot find any windows using app.allWindows() or Windows.allWindows().

Not sure if this is a feature request, user error, or bug.

**Comment by kasper** [comment]
Is this still an active issue? Please comment and I’ll reopen.
