### ISSUE TITLE
Add screenshot, animated GIF or video to README

### ISSUE THREAD

**Issue by kasper** [kasper/phoenix#64]
Based on the feedback on [Reddit](https://www.reddit.com/r/osx/comments/3umg55/phoenix_20_a_lightweight_os_x_window_and_app/) and [Hacker News](https://news.ycombinator.com/item?id=10642279) it seems some people would like to see a screenshot, animated GIF or video to describe what Phoenix is. Obviously this is a bit tricky since out-of-the-box Phoenix doesn’t do anything. I’m open to ideas and suggestions!

**Comment by jasonm23** [comment]
Simply linking people to the wiki to try out config examples is enough.

A video could possibly show a basic config being built, but that would be much too dry for the people who would want such a thing.

There has to be a cut off point, Phoenix isn't really a good fit for someone who cannot be bothered to read the API docs.

**Comment by kasper** [comment]
@jasonm23 Yes, I agree with you! I’ve been thinking about these comments and I’ve not found a good way that would provide any useful additional information. I did add a “Key Features” list to the README for those who want a TLDR overview.

Obviously — as time goes by — any blog posts, tutorials and examples will provide good resources to which we can link to.

**Comment by jasonm23** [comment]
Yep, allow the community to provide this sort of resource.

Hammerspoon does have this ...

https://youtube.com/watch?v=yrCjQu76rqY

**Comment by kasper** [comment]
Closing this for now.
