### ISSUE TITLE
bind()s not working if Phoenix is started when Input Source is non-English

### ISSUE THREAD

**Issue by edkolev** [kasper/phoenix#66]
Hi, and thank you for this project! I literally use it every day.

I've noticed this issue:
- if Phoenix is started when Bulgarian (or another non-US) Input Source is enabled, bind()-ins are NOT working at all.

However, if Phoenix is started when U.S. Input Source is enabled, Phoenix bind()-ings are working OK.

To reproduce:
1. set this minimal example in .phoenix.js
```
var handler = Phoenix.bind( 'd', [ 'cmd' ], function() {
  focusApplicationIfRunning('VLC')
});

function focusApplicationIfRunning ( title ) {
  var app = App.get( title );
  if ( app ) {
    App.launch( title ).focus();
  }
}
```
2. stop Phoenix
3. switch Bulgarian Input Source (I've reproduced the issue with Bulgarian and also Hebrew; I couldn't reproduce with U.S. or British)
4. start Phoenix
5. The Command-D binding (set in .phoenix.js) doesn't work

Thanks

**Comment by kasper** [comment]
Hello! I’m sorry to hear that. I’m using Phoenix with a Finnish locale and everything is working as expected. A quick question: with a Bulgarian locale, does the keyboard actually output a `d`-character, when you press the `d`-key?

Phoenix uses local keyboard layouts and you need to bind against these. So, if your keyboard has a `ä`-key, you can bind it. Obviously this key represents a different character for instance in the British-layout.

**Comment by edkolev** [comment]
In Bulgarian locale, the `d`-key produces д

**Comment by kasper** [comment]
@edkolev You’re most welcome and thanks for supporting Phoenix! It’s true that this might be confusing especially when using Latin-based keyboards with non-Latin locales.
