### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by zjfroot** [kasper/phoenix#69]
Maybe it is already implemented but it would be great to have logs, especially when developing or trying out other people's .phonex.js

**Comment by jasonm23** [comment]
Not sure this is available, last time I needed it I recompiled a patched version.

+1 for this

**Comment by kasper** [comment]
Do you need something more specific than `Phoenix.log(String message)` which logs to the system log? (https://github.com/kasper/phoenix/blob/master/API.md#4-phoenix)

**Comment by zjfroot** [comment]
@kasper Thanks for pointing that out. I think Phonex.log(String message) should be enough for me.

**Comment by kasper** [comment]
@zjfroot Great! Also, `JSON.stringify()` can be useful when logging objects.

**Comment by jasonm23** [comment]
Doh! I have only needed logging when I was hacking on the Phoenix source. 

 `Phoenix.log` plus `JSON.Stringify` should be plenty.

BTW if you require CSON you get the awesome `CSON.stringify` (Nice clean CoffeeScript style object dumps.)
