### ISSUE TITLE
Function bound to key dies, and I don't know how to investigate

### ISSUE THREAD

**Issue by kgrossjo** [kasper/phoenix#72]
I am trying to replicate the functionality of Divvy.  Divvy allows me to hit a prefix key (Alt-Space, say), pops up a little window, waits for me to hit another key (I'll call it the suffix key), and then moves the window to a preset position/size based on the key.  Let's say the H key moves it to the left half of the screen, the L key moves it to the right half of the screen.

So I wrote procedural code that works, but when trying to convert it to an OO style, it's failing.  And I have no idea how to investigate.  How do I investigate?

The procedural code does the following:

* There is an entry point, bound to Alt-Space (the prefix key).  The entry point enables handlers for H and L.  The entry point also shows a modal explaining that the user has to hit H or L next.
* The H and L handlers move the window to the right spot, then close the modal and disables the H and L handlers.

So I thought I could encapsulate the concept of a prefix key with its suffix keys, but it's not working at all :-(

```javascript
/* New-style prefix keys, WIP */
function PrefixKey(key, modifiers, description) {
    this.modal = centered_modal(description);
    this.suffixes = [];
    var that = this;
    this.prefix = Phoenix.bind(key, modifiers, function () {
        that.enableSuffixes();
        that.modal.show();
    });
}
PrefixKey.prototype.enableSuffixes = function () {
    this.suffixes.forEach(function (x) {
        x.enable();
    });
};
PrefixKey.prototype.disableSuffixes = function () {
    this.suffixes.forEach(function (x) {
        x.disable();
    });
};
PrefixKey.prototype.addSuffix = function (key, modifiers, cb) {
    var that = this;
    var result = Phoenix.bind(key, modifiers, function () {
        cb(); // ***
        that.modal.close();
        that.disableSuffixes();
    });
    result.disable();
    this.suffixes.push(result);
    return result;
}
var gPrefix = new PrefixKey('g', ['alt'], "new style");
var gLeft = gPrefix.addSuffix('h', [], function () {
    move_window({x: 0, y: 0, width: 0.5, height: 1.0});
});
```

So I hit Alt-G, the centered modal shows up saying "new style".  I hit H.  The window moves to the right spot, so I know that the `cb();` call works.  (I've annotated it with "***", above.)

But the modal doesn't close, and the suffixes aren't disabled.

How do I figure out what happens after that `cb();` call?

**Comment by kasper** [comment]
Hi! There’s currently a bug in callback handlers which prevents errors being reported properly. Unfortunately that might hide a syntax or logic error. This will be fixed in the near future.

With a quick look, I can’t see any major issues with your strategy. However, what you can do is manually log to debug and to try to understand what is happening. For example, in your annotated location, try to log the modal or its properties with `Phoenix.log(that.modal)` and check the output from the Console app to get any clues. If this doesn’t help you, I can look into this more thoroughly once I have time.

**Comment by kgrossjo** [comment]
Thank you, @kasper.  I am trying your suggestion, and I don't know how to interpret the result.

I added log statements to `addSuffix` as follows, and the string explains what happens.

{code:javascript}
PrefixKey.prototype.addSuffix = function (key, modifiers, cb) {
    Phoenix.log("this gets logged when Phoenix loads the init file");
    var that = this;
    var result = Phoenix.bind(key, modifiers, function () {
        Phoenix.log("this never appears in the log, I expected it after hitting the key");
        cb();
        that.modal.close();
        that.disableSuffixes();
    });
    result.disable();
    this.suffixes.push(result);
    return result;
}
{code}

**Comment by kgrossjo** [comment]
Now I got it working, but this just causes me to understand failure at a higher level.

I had two implementations: One procedural implementation with global variables.  It had a prefix key Alt-Space and used H for left half and L for right half.  The other was my OO implementation, with a prefix key Alt-G and it also used H for left half and L for right half.

I am guessing that the two bindings for H with no modifiers conflicted.  Anyway, after using Alt-G (for the OO implementation), it seems hitting H caused the "procedural H" to be fired instead of the "OO H".

But the whole point of the OO approach was that I could have multiple prefix keys with potentially different behavior for the same suffix key.  Duh.

Now I am guessing that I shouldn't just enable/disable the suffixes, but rather I should be removing the bindings entirely.

**Comment by kgrossjo** [comment]
Just in case, I've put this config up here:
https://github.com/kgrossjo/phoenix-config

**Comment by kgrossjo** [comment]
Can I use this strategy for multiple prefix keys, with the same suffix keys?

Say prefix key <kbd>alt-space</kbd> makes <kbd>H</kbd> and <kbd>L</kbd> move the window to the left / right half of the screen.
But prefix key <kbd>alt-G</kbd> makes <kbd>H</kbd> and <kbd>L</kbd> move the window to the previous / next monitor.

**Comment by kasper** [comment]
Glad to hear! I like what you are trying to achieve! So as described in the API documentation, KeyHandlers are kept alive and the key combination bound as long as you keep a reference to it. Once this reference is released, the handler and key combination will be released. You may disable and enable keys while you still have you reference to the KeyHandler. This still keeps the handler alive, but the key combination is released. Binding the same key combination again from anywhere will however release any previous handlers (enabled or disabled) with the same combination. You also cannot bind keys that are exclusively bound to other applications, the result handler will be `undefined`.

Keeping this in mind, I think you could achieve what you want if the key combinations are available. You would first bind the prefix keys, then assign their callbacks to bind handlers for the suffix keys and finally release these suffix keys once pressed. You can bind individual keys with no modifiers by supplying an empty modifiers list.

To get an idea, you could do something like this:

```javascript
var prefix = Phoenix.bind('space', [ 'alt' ], function () {
    var suffixes = [];
    suffixes.push(Phoenix.bind('h', [], function () { // do what you want and release the suffixes by emptying the list afterwards });
    suffixes.push(Phoenix.bind('l', [], function () { // as above });
}

**Comment by kasper** [comment]
By looking at your code, you pretty much have implemented this spot on. Couldn’t you just use two PrefixKeys to achieve your desired behaviour? However, you would either need to store the suffixes globally or in another object. You could also add the suffixes only after the prefix key has been pressed, as above. I think the trick you need is to bind and release the suffixes dynamically to change their behaviour.

**Comment by kgrossjo** [comment]
Yes.  Thank you very much.  I have now done this:

* In `addSuffix`, I just record which keys need to be bound to which callbacks.
* When the prefix key is hit, all the keys added with `addSuffix` actually get bound.
* When a suffix key is pressed, I first disable all the suffix bindings, then I remove the reference to them.  Then I execute the callback.

New code is pushed: https://github.com/kgrossjo/phoenix-config

With a little bit of luck, this should enable me to create more than one prefix.  But I haven't tested it yet.

**Comment by kasper** [comment]
@kgrossjo Excellent, looks good! If you have any further questions, please don’t hesitate to ask. Once done, would you mind adding a link to your configuration to the Wiki?

**Comment by kgrossjo** [comment]
I've added the link to the Wiki, even though I will be tweaking the config as I learn more.

Thank you for your wonderful encouragement!
