### ISSUE TITLE
Q: Show an interactive window?

### ISSUE THREAD

**Issue by kgrossjo** [kasper/phoenix#73]
I have been thinking of creating a window switcher.  You press a key, you get a popup with a search box at the top and a list of window names below.  You enter some characters into the search box, the list of window names gets shortened to the matching windows.  You move up and down in the result list, select the window you want, and then you go there.

Is there a way for me to somehow interact between Phoenix and such a popup?

**Comment by kgrossjo** [comment]
I found the following, but it makes my head spin :-)
http://tylergaw.com/articles/building-osx-apps-with-js

I have no idea how to do what I need, given that I don't now Cocoa and also there is no code completion...

Phoenix could call it as an app, I guess.

**Comment by kasper** [comment]
You wouldn’t probably need or benefit from Phoenix as an app as such for this as there’s no support for app-to-app communication. That being said, if you want to learn Swift or Cocoa, you can definitely use parts of the code to achieve the window switching. You would still need to implement the UI.

I also wouldn’t be surprised if there’s already some app that works in the way you described. Not sure…

**Comment by kgrossjo** [comment]
There is Contexts: https://contexts.co

It's pretty cool and looks nice and is featureful and all that...

Please close this question if you like.

**Comment by kasper** [comment]
Cool, a nice find!
