### ISSUE TITLE
feature req: bring back "alert"

### ISSUE THREAD

**Issue by ontucker** [kasper/phoenix#76]
Presumably you don't find this feature all that useful so you didn't bother reimplementing it in the rewrite, but I'd like to make a case for the alert() functionality (slightly modified) from v1 being quite useful for doing slightly more advanced user-specified functionality.  To demonstrate, I'm attaching a video of my "findmode" phoenix script in action.  It basically lets you bind a key that puts you in a mode where you can do typeahead-like window switching.  Being able to have some sort of annunciator that you're in this mode is critical (in the video, you can see that phoenix 1 makes a transparent text overlay in the center of the screen).  It doesn't necessarily need to be in the middle of the screen (the menu bar would probably be ok).  Note that when the pattern you type matches multiple windows, you can then tab cycle through them (e.g. in the video when I type "fire" and cycle through firefox windows) as well as have a separate key binding to raise all found windows instead of just the selected one (bring all firefox windows to the top).

I actually find this method of window switching so efficient that I've almost completely stopped using the standard mac command-tab switching.

![phoenix_findmode_loop](https://cloud.githubusercontent.com/assets/17346502/13198882/b55e96cc-d7c9-11e5-8a7a-d5405870b32c.gif)

**Comment by kasper** [comment]
Hi! You can still definitely do this. I replaced the concept of “alerts” with “modals”. Modals also give you more control over how you can use them — such as controlling their position and duration. See the [API](https://github.com/kasper/phoenix/blob/master/API.md#11-modal). :)

**Comment by ontucker** [comment]
Awesome.  I missed that since I was looking for it in the top level Phoenix object and figured you'd replaced it with notify().   I'll give this a try.  If you're interested in having a 'contrib'-style user script repository I think my FindMode would make a pretty good candidate.

**Comment by ontucker** [comment]
BTW, modals work perfectly for what I'm doing.  It's great that I can even update their text without having to destroy/create them as I type, unlike with Phoenix 1.

**Comment by jasonm23** [comment]
I think re: reusable libraries for Phoenix, you/we can just add them to the wiki for now.  Keep their repos independent.

I don't see much need for a Phoenix contrib repo, though.

**Comment by jasonm23** [comment]
Kasper has the final word on this of course!

**Comment by kasper** [comment]
@ontucker Great! Feel free to add your configuration to the Wiki. I agree with @jasonm23 that there probably isn’t need for a contrib repo. However, I’ve been thinking of creating a way to load reusable libraries in a similar way as loading files with `require()` straight from GitHub, for example `use('username/repository')`. This does have some security risks though, especially related to running commands.

**Comment by mafredri** [comment]
@ontucker how are you listening to the keyboard presses after showing your modal? Do you rebind all keys while displaying the modal and then unbind them again, or do you have a better method?

Sorry for commenting on an old issue, I'm just interested in trying it out myself 😄.

**Comment by ontucker** [comment]
Yes, I maintain three sets of bindings:
1) the main normally-active bindings that can cause the "mode" to be entered.  These must be disabled when entering the mode.
2) the bindings that are active when in the mode.  These are all created the first time the mode is entered, and from that point on they're all disabled when exiting the mode and re-enabled when entering the mode again.
3) a set of external bindings which are passed into the module, that will be disabled when entering the mode and re-enabled when exiting the mode.  These are really just like the bindings in (1) but the idea is that other modules might create a binding that collides with something in (2) and needs to be managed.

**Comment by mafredri** [comment]
Thanks for the detailed explanation @ontucker, just tried it out and it seems to work quite well :)!

**Comment by ontucker** [comment]
BTW, I have had some trouble when attempting to have two separate "modal" modules that do lots of binding and unbinding en masse.  I have yet to really debug it to figure out the issue, but for example, I have two different modules where set (2) includes bindings for all keys a-z unmodified and shifted.  Either one of these modules is able to enter and exit its own mode cleanly without any ill effects, but when I try to activate one, then the other, then the first one again, most of the first set of bindings never actually work again.  I haven't gotten a simple repro case, but it seems to me there are issues around binding a key, disabling that binding, creating another binding to that same key, disabling the second binding, then re-enabling the original one.  If this is the case, the answer may be for my modules to manage their own shared proxy binding, which gets a bit more complicated.

**Comment by mafredri** [comment]
Do you bind any of the same keys across the two modules? If yes, do you store separate key handlers for these modules?

From [API](https://github.com/kasper/phoenix/blob/master/API.md#5-phoenix) documentation:

> binding overrides any previous handlers for the same key combination

As I understand this, you cannot have two different key handlers bound to the same key without one invalidating the other. This is probably why it would not work to try and re-enable a KeyHandler that has been overridden by a new one.

**Comment by ontucker** [comment]
> Do you bind any of the same keys across the two modules? If yes, do you store separate key handlers for these modules?

Yes, and yes.

I did see that wording in the docs about a binding overriding previous handlers, but the meaning isn't entirely clear about whether the override necessarily permanently breaks the previous handler, or if you should be able to un-bind the newer one and have the overridden handler become able to be made active again.

**Comment by mafredri** [comment]
I started writing a generic input scanner (you can find it [here](https://github.com/mafredri/phoenix-config/blob/f5f4b07724dc4e3a2ea9ec737418b65168eacd87/src/scan.ts) if you're interested). With this I created two scanner instances, and alternate between calling them. I can clearly see that the keybindings are not "destroyed", BUT their callbacks have been replaced.

So first we initialize scanner1, then scanner2. By initializing scanner2 all of scanner1's keybinding callbacks have been replaced by scanner2's callbacks. So even when we're telling scanner1 to activate, scanner2 will respond.

**Comment by mafredri** [comment]
Oh, I just made an interesting observation about `Phoenix.bind`. If you have disabled a KeyHandler, and you rebind that key with `Phoenix.bind` it will not automatically re-enable! So what you're seeing @ontucker might be a combination of replaced callbacks and disabled KeyHandlers.

**Comment by kasper** [comment]
Indeed, basically rebinding a key will only change the callback if the handler is still alive in the context.

**Comment by mafredri** [comment]
API docs suggest that the `handler` is overridden though, which to me sounds like it would invalidate the old and create a new one. We could probably specify more clearly what happens. And it might even make sense to reset the enabled state when a handler is rebound.

**Comment by kasper** [comment]
Valid points. You fellows are pushing the use cases out of the original intent. :)

**Comment by mafredri** [comment]
Hehe, sorry about that! ^_^

**Comment by kasper** [comment]
#99

**Comment by szhu** [comment]
Hey @ontucker, do you mind sharing the script for your find-window feature? It looks really cool!

(Please forgive me for reviving an old issue, I have no other way to contacting @ontucker.)

**Comment by ontucker** [comment]
Sure, here you go: https://gist.github.com/ontucker/9f51d990631ac19f46d92beea0c1e3e6
It's still a little unpolished, but I use it anyway :)
