### ISSUE TITLE
feature request: setTimeout

### ISSUE THREAD

**Issue by ontucker** [kasper/phoenix#77]
There doesn't seem to be any mechanism for doing something on a delay in Phoenix.  Exposing something like setTimeout would do the trick.  What do you think?

**Comment by kasper** [comment]
I like the idea! Natively no timing functions have been implemented in JavaScriptCore, but it shouldn’t be that hard to achieve.

**Comment by ontucker** [comment]
Thanks, a specific use case is that I'd like my "Find Mode" module to be able to time out.  Since switching to Phoenix 2.0, the little modal indicator is a lot more subtle, and I find myself forgetting it's there and wondering why it's eating my keystrokes. If it timed out after 10 seconds this might happen a lot less. :)  So my thought is that I'd set/reset a timeout on every input keystroke and exit the mode if the timer ever fires.

**Comment by kasper** [comment]
It sounds like a perfect use case.

**Comment by kasper** [comment]
You can now create timers to achieve delays and timed events! See the functions `Phoenix.after(double interval, Function callback)` and `Phoenix.every(double interval, Function callback)` in the [API](https://github.com/kasper/phoenix/blob/master/API.md#5-phoenix). This will be released in the next update. @ontucker I hope this opens more possibilities for you!
