### ISSUE TITLE
Occasional "Could not register key"

### ISSUE THREAD

**Issue by aaronjensen** [kasper/phoenix#83]
While working on my config, occasionally I get:

> Mar 24 22:25:32 aaronmbp Phoenix[93822]: Error: Could not register key 34 (48) with modifiers 6912. (-9878)
> Mar 24 22:25:32 aaronmbp Phoenix[93822]: Error: Could not register key 4 (49) with modifiers 768. (-9878)

I wonder if it has to do with saving too frequently?

**Comment by kasper** [comment]
@aaronjensen Intriguing! The most likely case is that those keys have been already exclusively registered to another app. I’ve never seen this happen while saving the configuration too frequently. All keys should be released before loading the new context. However, I will look into this.

**Comment by kasper** [comment]
@aaronjensen Yes, you’re right! It seems unbinding keys is not always synchronous and if you save your configuration *very* often, this will result in the error you provided. I adjusted the latency of context reloads on configuration file changes to improve this. However, this won’t get rid of the race conditions completely.
