### ISSUE TITLE
windows are not properly sized when moved to another screen

### ISSUE THREAD

**Issue by aaronjensen** [kasper/phoenix#84]
For some reason this only appears to apply to some windows. For me, emacs is one such window that cannot be moved to another screen and resized at the same time.

To repro, you need two monitors of different sizes (I have a dell 30" and a 15" Retina MBP). My laptop is to the left of my monitor and positioned about 300px down from the top of the 30"

Using this code:

```js
function p(obj) {
  Phoenix.log(JSON.stringify(obj))
  return obj
}

function move_window(rect, screen) {
  screen = screen || Window.focusedWindow().screen()
  var scr = screen.visibleFrameInRectangle();
  p(scr)
  var r = {
    x: Math.round(scr.x + rect.x * scr.width),
    y: Math.round(scr.y + rect.y * scr.height),
    width: Math.round(scr.width * rect.width),
    height: Math.round(scr.height * rect.height),
  };
  p(r)
  var before = Window.focusedWindow().frame()
  p(before)
  Window.focusedWindow().setFrame(r);
  var after = Window.focusedWindow().frame()
  p("after:")
  p(after)

  if (isRectEqual(before, after)) {
    move_window(rect, screen.next())
  }
}

function isRectEqual(a, b) {
  return a.x === b.x &&
    a.y === b.y &&
    a.width === b.width &&
    a.height === b.height
}

keys.push(Phoenix.bind('h', ['cmd', 'ctrl'], function () {
  move_window({ x: 0, y: 0, width: 0.5, height: 1.0 })
}))
```

Open Emacs, press cmd+ctrl+h twice. The second press should move to the other monitor, and it should only be taking half the width, but instead it maintains the same width it had on the 30" monitor.

I'm on El Capitan

Logs:

```
Mar 25 08:10:47 aaronmbp Phoenix[99758]: {"y":23,"x":0,"width":2560,"height":1573}
Mar 25 08:10:47 aaronmbp Phoenix[99758]: {"x":0,"y":23,"width":1280,"height":1573}
Mar 25 08:10:47 aaronmbp Phoenix[99758]: {"y":25,"x":127,"width":1276,"height":1566}
Mar 25 08:10:47 aaronmbp Phoenix[99758]: "after:"
Mar 25 08:10:47 aaronmbp Phoenix[99758]: {"y":23,"x":0,"width":1276,"height":1566}
Mar 25 08:10:48 aaronmbp Phoenix[99758]: {"y":23,"x":0,"width":2560,"height":1573}
Mar 25 08:10:48 aaronmbp Phoenix[99758]: {"x":0,"y":23,"width":1280,"height":1573}
Mar 25 08:10:48 aaronmbp Phoenix[99758]: {"y":23,"x":0,"width":1276,"height":1566}
Mar 25 08:10:48 aaronmbp Phoenix[99758]: "after:"
Mar 25 08:10:48 aaronmbp Phoenix[99758]: {"y":23,"x":0,"width":1276,"height":1566}
Mar 25 08:10:48 aaronmbp Phoenix[99758]: {"y":311,"x":-1440,"width":1440,"height":900}
Mar 25 08:10:48 aaronmbp Phoenix[99758]: {"x":-1440,"y":311,"width":720,"height":900}
Mar 25 08:10:48 aaronmbp Phoenix[99758]: {"y":23,"x":0,"width":1276,"height":1566}
Mar 25 08:10:49 aaronmbp Phoenix[99758]: "after:"
Mar 25 08:10:49 aaronmbp Phoenix[99758]: {"y":311,"x":-1440,"width":1276,"height":1306}
```

One curious thing is that once the Emacs window has moved, I cannot resize it horizontally by dragging unless I first resize it vertically and move it up so that the bottom of the window is visible. This could be a bug in Emacs, but I have a very similar config with slate.js and it does not have this problem.

For what it's worth, slate.js appears to resize the window prior to moving to the other screen.

**Comment by kasper** [comment]
I’ve indeed wondered on numerous cases when resizing before moving would be required and haven’t personally found any of these cases. This is why I removed the secondary resize on refactor. Obviously you may have found a case and maybe this should be reinstated.

What I’ve however noticed, that some apps (mainly Adobe) do not support the Accessibility API properly and do weird things that can affect resizing. If Emacs works in Slate.js, this shouldn’t be the case.

Could you try out your theory? Use `setTopLeft()` and `setSize()` to simulate a `setFrame()`. Particularly in the sequence: 1. setSize, 2. setTopLeft and again 3. setSize.

**Comment by aaronjensen** [comment]
Hi, I believe I tried that and it didn't actually work. It seemed like it happened too quickly. I'll try it again when I get home. I'll also try w/ two different bindings to see if it indeed a race condition thing

**Comment by kasper** [comment]
@aaronjensen Great, thanks! It’s a shame that Apple hasn’t implemented a way to set the frame in one API-call, which would solve these types of issues.

**Comment by aaronjensen** [comment]
That worked! I guess I hadn't tried exactly that.

**Comment by kasper** [comment]
@aaronjensen Nice! I’ll fix this in the next release. Thanks for the extremely thorough report and debugging. It always helps. :)

**Comment by kasper** [comment]
This is now fixed in master.
