### ISSUE TITLE
Unbinding keys

### ISSUE THREAD

**Issue by longouyang** [kasper/phoenix#85]
First off -- great tool, great documentation!

I'm trying to implement some modal keyboard shortcuts like vim has (e.g., first have to press escape to enter command mode, then can press some other keys to issue commands and go back to editing mode).

I think for this to work requires the ability to unbind keys. Would you guys mind implementing this?

**Comment by longouyang** [comment]
FWIW, I think I can hack my modal idea in using `Phoenix.reload` but this feels hacky:

```js
keys.push(Phoenix.bind('escape',['ctrl'], function() {
  alert('phx')

  keys.push(Phoenix.bind('q', [], function() {
    alert('todo: do something here')
    Phoenix.reload();
  }))
}))
```

**Comment by longouyang** [comment]
Oh, never mind -- the docs clearly say you can unbind by calling `KeyHandler.disable()`

**Comment by kasper** [comment]
@longouyang Hi, thanks for the nice words! You can certainly achieve what you are trying to do. A few options: 1.) release the reference to the handler and it will be unbound (i.e. remove it from the array), 2.) `disable()` the key and it will be unbound or 3.) bind a new handler with the same key combination and the previous will be overridden. I hope this helps!
