### ISSUE TITLE
Cant make space style fullscreen from an app

### ISSUE THREAD

**Issue by AttilaForgacs** [kasper/phoenix#86]
That is when it owns a space or desktop.
Tried both SetFullScreen in window, spaces... No luck.
Is it possible at all ? 
I have displays have separate space turned on.
BetterTouchTools seems to be the only app that can do this currenlty.
My understanding of spaces/desktops etc. is limited, i knew some MFC/.NET/WIN32, script fails silently, 
anyways this is what i tried

```
    var w = Window.focusedWindow();
    w.setFullScreen(true);
```

**Comment by kasper** [comment]
@AttilaForgacs Just to make sure that you’ve built Phoenix 2.1 from source? The latest release (2.0.1) doesn’t support this yet.

**Comment by kasper** [comment]
@AttilaForgacs I’ve now released Phoenix 2.1. If you’re still having issues, please let me know!

**Comment by ngryman** [comment]
Hey @kasper, I think I have a similar issue.

This code fails to set the window to fullscreen:
```js
const app = App.launch(name)
const appWindow = app.mainWindow()
appWindow.setFullScreen(true)
```

It gives the following error in the Console:

![](https://cdn.zapier.com/storage/photos/9effdaf5d851985baea1cf712f43dd72.png)

However, setting a small timeout makes it work:
```js
const app = App.launch(name)
const appWindow = app.mainWindow()
setTimeout(() => appWindow.setFullScreen(true), 100)
```

**Comment by mafredri** [comment]
@ngryman I think that's just because the app is taking it's sweet time to launch / open it's main window. You could try launching with `App.launch(name, {focus: true})` to speed up the launch, or you could wait for the `appDidLaunch` or `windowDidOpen` event before issuing fullscreen.

I do realize that's a bit inconvenient though. Maybe we could create some promise wrapper/API around some of these commands that synchronizes with the events 😄.

**Comment by ngryman** [comment]
I was expecting `App.launch` to be blocking somehow, but it's not, and depending on the app the main window can take a while before it's available (ie. Slack for example has a pretty long splash screen).

@mafredri I will definitely try the `focus: true`, and `appDidLaunch` / `windowDidOpen`, thanks for the suggestion!

**Comment by kasper** [comment]
`Event.once` might be handy helper for this.

**Comment by mafredri** [comment]
I've been thinking about doing something like this for a while so I ended up doing a bit of prototyping on this 😅. But this won't work on e.g. Slack because it's main window isn't ready and it doesn't produce any window events 😞.

```typescript
function appLaunch(name: string, focus: boolean = true): Promise<App> {
	return new Promise((resolve, reject) => {
		let bundleId = '';
		let done = false;

		Event.once('appDidLaunch', evApp => {
			if (!done && evApp.bundleIdentifier() === bundleId) {
				resolve(evApp);
				return;
			}
			return done;
		});
		setTimeout(() => {
			done = true;
			reject(`timeout launching ${name}`);
		}, 1000);

		const app = App.launch(name, {focus});
		if (!app) {
			reject(`could not launch ${name}`);
			return;
		}
		bundleId = app.bundleIdentifier();
	});
}

Key.on('t', hyper, (_: Key, repeated: boolean) => {
	appLaunch('Terminal').then(app => app.mainWindow().setFullScreen(true));
});
```

**Comment by mafredri** [comment]
Ok, just realized we're posting on an old issue, so I'll try not to bump this further. This is what I came up with as a fix for Slack (the splash is titled just `'Slack'` whereas it becomes `'Slack - [Workspace]'` once ready).

An alternative approach would be to wait for `setFullScreen` to return true, but this has the unfortunate side-effect of spamming the the Console with Phoenix errors.

Sidenote: @kasper would it be possible to catch the Phoenix errors in JavaScript? I tried but it had no effect, still prints the same errors @ngryman posted in his screenshot.

```typescript
function waitWindow(predicate: (win: Window) => boolean, timeout = 5000) {
	return (app: App): Promise<App> => {
		return new Promise((resolve, reject) => {
			if (timeout <= 0) {
				reject(`timeout waiting for ${app.name()} window`);
				return;
			}
			if (app.windows().find(predicate)) {
				resolve(app);
				return;
			}
			const retry = waitWindow(predicate, timeout - 20);
			setTimeout(() => resolve(retry(app)), 20);
		});
	};
}

Key.on('m', hyper, (_: Key, repeated: boolean) => {
	appLaunch('Slack')
		.then(waitWindow(w => w.isMain() && w.title() !== 'Slack'))
		.then(app => app.mainWindow().setFullScreen(true))
		.catch(log);
});
```

**Comment by kasper** [comment]
Regarding the side note, you would need to explicitly throw the errors from the Objective-C API (as we do with `require`). Makes sense in some cases.
