### ISSUE TITLE
Preprocessing fails when $SHELL is fish.

### ISSUE THREAD

**Issue by bobthecow** [kasper/phoenix#88]
- Version: 2.1
- OS X: 10.11.4

When my $SHELL is set to fish, $PATH is [exported as space delimited here](https://github.com/kasper/phoenix/blob/5b464149e702500049485932ff8d099babee7f9b/Phoenix/NSTask%2BPHExtension.m#L14-L17), but bash [expects it to be colon delimited here](https://github.com/kasper/phoenix/blob/5b464149e702500049485932ff8d099babee7f9b/Phoenix/PHShebangPreprocessor.m#L39-L42). Can we use the same shell in both places so preprocessing works?

Thanks! 😄

**Comment by kasper** [comment]
Damn! Good catch, I will release an update today. :smiley:

**Comment by bobthecow** [comment]
Great, thanks!

**Comment by kasper** [comment]
@bobthecow Thanks for the short and detailed explanation! This is now fixed and 2.1.1 has been released. It should sort things out.

**Comment by bobthecow** [comment]
Thanks for the quick response :)
