### ISSUE TITLE
Consider replacing underscore with lodash

### ISSUE THREAD

**Issue by ttonyh** [kasper/phoenix#89]
Please consider replacing underscore with lodash.
Lodash is a drop-in replacement to underscore, but is updated more often, contains more features, and, I believe is more performant (generally).

**Comment by kasper** [comment]
It seems there has been quite a heated discussion about Underscore vs. lodash — even discussion about merging the projects jashkenas/underscore#2182. You also seem to be right about the performance gains, generally speaking. Although in this context the speed difference would likely be small. Any particular reasons or examples for your preference?

**Comment by jasonm23** [comment]
There are a few incompatibilities with Lodash / Underscore that could affect users configs.

Performance gains for this application would be negligible too.

I'm a big fan of LoDash over Underscore, but for this context it's really not worth breaking people's configs, for no real gain.

**Comment by sallar** [comment]
I actually wanted to go ahead and send a PR that replaces underscore with lodash. Good thing I searched first. I still like to do that though :)
I like lodash: its more performant, more often updated and includes great tools for functional programming, etc. Generally lodash is accepted as a great replacement to underscore.

**Comment by jasonm23** [comment]
Purely on the basis of relative governance styles of the two projects

:+1: Lodash vs Underscore.

**Comment by kasper** [comment]
I have no preference over one or the other. I was first introduced to Underscore and only later to Lodash. (Not surprising.) I guess you could try to require Lodash in your configuration and see if you can override Underscore. (I wonder what would happen.)

I can definitely see the performance gains, though it’s unlikely you will have so many elements to deal with in Phoenix.

Practically speaking, I guess we could make it an option on which (Underscore or Lodash) would be loaded. Obviously this would add some complexity. (Or we could replace it at some point, but it seems there are still fans for Underscore as well.)

**Comment by mafredri** [comment]
There was plans for a merger of the two projects a year back, which had begun a year before that. Ultimately they decided not to merge the projects, however, some of the core underscore team work on lodash now-a-days I believe. Looking at underscore today, the project seems somewhat stale (last update over a year ago), however, on GitHub it does seem to have some activity, bug fixes and the like.

I personally don't feel strongly about this, if anything, I think that perhaps Phoenix shouldn't bundle either one. Also, replacing the bundled underscore is simple enough, it's just a matter of overriding the `window._` property.

You can even tell underscore to disable itself with `_.noConflict()`, this will set `window._ = undefined` (because there was no previous `window._` when underscore was initialised) :P.

**Comment by jasonm23** [comment]
I have a feeling removing completely makes the most sense.

It'd be a trivial migration to include it in the user config instead.

**Comment by mafredri** [comment]
I believe kasper uses underscore internally to provide some of the features implemented in JavaScript, so removing it would require rewriting those functions.

**Comment by kasper** [comment]
@mafredri Oh, nice. I hadn’t noticed the `_.noConflict()`-function. It seems lodash has this feature as well.

I feel there’s a strong argument that either one adds a fare bit of value to bare JavaScript. Not everyone might know the existence of these frameworks, so it’s rather helpful to have something bundled. It also encourages the use of these helpers for clean code.

The JavaScript build environment in `library/src/` uses Underscore in a few places. Obviously those could easily be migrated. So I think the most rational thing might be to switch to lodash. Users with a strong preference for Underscore could ask lodash to release the the `_`-variable and then require Underscore instead.

**Comment by jasonm23** [comment]
Given there are dependencies LoDash makes the most sense to me too.

**Comment by kasper** [comment]
Thanks for the discussion. The next release will replace Underscore.js with Lodash.
