### ISSUE TITLE
Command.run() is broken or ...

### ISSUE THREAD

**Issue by khalidchawtany** [kasper/phoenix#95]
- Version: 2.0.2
- OS X: 10.11.4

either Command.run() is broken or ....

I tried the following and nothing is printed in the **Console**.
```js
if(Comamnd.run("rm ~/file.txt", "")){
Console.log("File deleted");
}
else
Console.log("Fail");
```
I tried this variant too.
```js
if(Comamnd.run("rm", "~/file.txt"))
```

I want to launch **nvim-qt** using *Command.run*. I read from the description of command.run that *it waits for the command to finish*. However, **nvim-qt** is a gui application (Without proper app for OS X, launched from a terminal) and I want it to stay running. Is it possible to add a third argument to command.run so that it does not wait for the task to end.

**Comment by mafredri** [comment]
A couple of problems:

* As far as I know, Phoenix doesn't do path resolution, so paths must be absolute, `/bin/rm`, not `rm`.
* The second argument is of type string array, meaning it's not `run(cmd, param1, param2)`, it's `run(cmd, [param1, param2])`
* And third: `~` is dependent on shell expansion and you are not running the command in a shell, so again, the path must be absolute. Can't be `~/file.txt`, `$HOME/file.txt`. Instead it must be `/Users/user/file.txt`.
* There is no `Console` object in Phoenix. To log you need to use `Phoenix.log(string)`

Hope this helps :)!

**Comment by mafredri** [comment]
Ah I missed the last part, and to be honest I don't know of a good way to do it, maybe @kasper has a better idea, but one option is to create a shell script that spawns it.

`/usr/local/bin/launch-nvim-qt`:

```sh
#!/usr/bin/env bash
nvim-qt &
```

And then launch `/usr/local/bin/launch-nvim-qt` with `Command.run`.

**Comment by khalidchawtany** [comment]
Sorry for the worst bug report ever.

This was just an example. This is actually what I want to do:
```js
keys.push(Phoenix.bind('\\', mash, function () {

  if(!App.get('nvim-qt')){
    Phoenix.log('Not running');
    //App.launch('nvim-qt');   //Cannot do this as nvim-qt does not have a proper App
    if(Command.run("/Volumes/Home/bin/nvim-qt", ""))
      Phoenix.log('success');
    else
      Phoenix.log('fails');
  }
  else
    App.get('nvim-qt').focus();
}));

```


The second parameter was my bug. It is an array :)

Thanks @mafredri

**Comment by khalidchawtany** [comment]
@mafredri just a small question, if you don't mind.

Is there anyway to set PATH for the command that is being executed?

**Comment by khalidchawtany** [comment]
nevermind found it

**Comment by mafredri** [comment]
Not sure how you solved it, but I would've done it e.g. by running the commands through `env`.

```js
Command.run('/usr/bin/env', ['ls', '/']);
```

**Comment by khalidchawtany** [comment]
Now I am back to the above suggestion again :)


```js
keys.push(Phoenix.bind('\\', mash, function () {
  var nvim_qt = App.get('nvim-qt');
  if(!nvim_qt)
    //App.launch('nvim-qt');
    Command.run('/bin/sh', ['/Volumes/Home/bin/nvq']);
  else
    nvim_qt.focus();
}));

```

This runs the application. However, after if it looses focus, it does not gain it.

if I run **/Volumes/Home/bin/nvq** from the terminal. Then the above code can give it focus. I am pretty sure that it is due to waiting for the command to exit as described in the documentation

**Comment by mafredri** [comment]
Not quite sure what you mean the problem is, I did provide a suggestion above how to work around the fact that Phoenix waits for the command to exit.

**Comment by khalidchawtany** [comment]
Ouch, I thought that the above suggestion was to set PATH for the command. Let me try.

**Comment by mafredri** [comment]
I'm talking about [this comment](https://github.com/kasper/phoenix/issues/95#issuecomment-219218257)

**Comment by khalidchawtany** [comment]
I am really sorry, I missed that one :( 

It works, thank you very much :)

**Comment by kasper** [comment]
@mafredri :+1:

**Comment by gutenye** [comment]
In case others found this

```javascript
Task.run('/bin/sh', ['-c', 'PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin CMD ARGUMENT'], () => {})
```
