### ISSUE TITLE
Default modal placement is off-screen

### ISSUE THREAD

**Issue by mafredri** [kasper/phoenix#96]
Modal placement is a bit weird in my opinion. Since it starts from the bottom left corner (0, 0) it does not follow the same logic as window placement. This also behaves weirdly on the main screen (the one with the dock).

The problem is, `(0, 0)` is actually off-screen on the y-axis due to the dock removing some of the screens `visibleFrameInRectangle` size. `(0, 2)` would show up in the expected location.

[Here's an example](https://github.com/mafredri/phoenix-config/blob/77ab5fe87aada9959c8dde6f2aa88412745040f4/src/coffee.ts#L44-L53) of how I needed to position a modal to get it into the bottom right corner (with a 2px indentation, so to speak).

* Version: 2.1.1
* OS X: 10.11.4

**Comment by kasper** [comment]
@mafredri NSRect and CGRect have different coordinate systems, NSRect has the origin in the bottom left, CGRect is flipped and the origin is on the top left. The Accessibility API uses CGRects and as modals are higher level windows, they use NSRects.

Basically, modals have no default placement. They are set to the origin of the coordinate system (NSZeroPoint). (0, 0) shouldn’t be off-screen, the Dock reserves two points (presumably) as a hot corner for showing and hiding the Dock automatically — if enabled.

The user is expected to set modals wherever desired. I therefor would be inclined to say the origin is the best place to default.

**Comment by mafredri** [comment]
Hey @kasper, I must apologize. My issue proved to be an optical illusion. Due to the dock sizing windows slightly smaller it seems like the modal is two pixels off (under the screen) when it in fact is perfectly contained in the screen.

My "workaround" above gives a better experience visually, but by no means is the current implementation wrong.

Thanks for the explanation about NSRect and CGRect, not very experienced with Objective-C so it's interesting to know.

**Comment by kasper** [comment]
@mafredri No worries at all. I wish there would be an official explanation for what’s the point for the two point margin in `visibleFrame`.
